apiVersion: v2
name: infernix
description: Repo-owned Helm chart for the Infernix local HA platform.
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: harbor
    version: 1.18.3
    repository: https://helm.goharbor.io
    condition: upstreamCharts.harbor.enabled
  - name: pg-operator
    alias: postgresOperator
    version: 2.9.0
    repository: https://percona.github.io/percona-helm-charts
    condition: upstreamCharts.postgresOperator.enabled
  - name: pg-db
    alias: harborpg
    version: 2.9.0
    repository: https://percona.github.io/percona-helm-charts
    condition: upstreamCharts.harborpg.enabled
  - name: pulsar
    version: 4.5.0
    repository: https://pulsar.apache.org/charts
    condition: upstreamCharts.pulsar.enabled
  - name: minio
    version: 17.0.21
    repository: https://charts.bitnami.com/bitnami
    condition: upstreamCharts.minio.enabled
  - name: gateway-helm
    alias: envoyGateway
    version: v1.7.2
    repository: oci://docker.io/envoyproxy
    condition: upstreamCharts.envoyGateway.enabled
