#!/bin/sh
set -eu

SELF_DIR=$(CDPATH= cd -- "$(dirname "$0")" && pwd)
BUILD_DIR="${INFERNIX_CABAL_BUILDDIR:-$SELF_DIR/.build/cabal}"

for arg in "$@"; do
  case "$arg" in
    --builddir|--builddir=*)
      exec cabal "$@"
      ;;
  esac
done

exec cabal --builddir="$BUILD_DIR" "$@"
