apiVersion: apps/v1
kind: Deployment
metadata:
  name: infernix-edge
  namespace: platform
spec:
  replicas: {{ .Values.edge.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: infernix-edge
  template:
    metadata:
      labels:
        app.kubernetes.io/name: infernix-edge
    spec:
      containers:
        - name: infernix-edge
          image: "{{ .Values.service.image.repository }}:{{ .Values.service.image.tag }}"
          imagePullPolicy: {{ .Values.service.image.pullPolicy }}
          command:
            - infernix
          args:
            - edge
          env:
            - name: INFERNIX_BIND_HOST
              value: "0.0.0.0"
            - name: INFERNIX_PORT
              value: "8080"
            - name: INFERNIX_SERVICE_UPSTREAM
              value: infernix-service.platform.svc.cluster.local:80
            - name: INFERNIX_WEB_UPSTREAM
              value: infernix-web.platform.svc.cluster.local:80
            - name: INFERNIX_HARBOR_UPSTREAM
              value: infernix-harbor.platform.svc.cluster.local:80
            - name: INFERNIX_MINIO_UPSTREAM
              value: infernix-minio-gateway.platform.svc.cluster.local:80
            - name: INFERNIX_PULSAR_UPSTREAM
              value: infernix-pulsar.platform.svc.cluster.local:80
          ports:
            - containerPort: 8080
