{{- if .Values.repoGateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: infernix-edge
  namespace: platform
spec:
  gatewayClassName: infernix-gateway
  infrastructure:
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: infernix-edge
  listeners:
    - name: http
      protocol: HTTP
      port: {{ .Values.gateway.listenerPort }}
      allowedRoutes:
        namespaces:
          from: Same
{{- end }}
