apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.service.dataPvc.name }}
  namespace: platform
  labels:
    infernix.io/release: infernix
    infernix.io/workload: service
    infernix.io/ordinal: "0"
    infernix.io/claim: data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.service.dataPvc.size }}
  storageClassName: {{ .Values.service.dataPvc.storageClassName }}
