apiVersion: v1
kind: Service
metadata:
  name: infernix-service
  namespace: platform
spec:
  selector:
    app.kubernetes.io/name: infernix-service
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.service.port }}
