apiVersion: v1
kind: Service
metadata:
  name: infernix-edge
  namespace: platform
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: infernix-edge
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: {{ .Values.edge.nodePort }}
