{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TypeApplications #-}

module Infernix.Substrate.Internal
  ( decodeSubstrateConfigFile,
    decodeCompiledRuntimePlanFile,
    decodeRawRuntimeConfigFile,
    demoConfigGeneratedBanner,
    demoConfigGeneratedBannerLine,
    encodeSubstrateConfig,
    renderSubstrateConfigSchema,
    renderSubstrateConfig,
    resolveRuntimeModeFromSubstrateFile,
  )
where

import Control.Exception (SomeException, displayException, try)
import Data.ByteString.Lazy qualified as Lazy
import Data.Char (isAlphaNum, toLower)
import Data.List (intercalate)
import Data.Maybe (fromMaybe)
import Data.Text (Text)
import Data.Text qualified as Text
import Data.Text.Encoding qualified as TextEncoding
import Data.Text.IO qualified as TextIO
import Dhall qualified
import Dhall.Core qualified as DhallCore
import GHC.Generics (Generic)
import Infernix.DhallSchema.Reflection (renderDecoderExpected)
import Infernix.ExecutionPlan (CompiledRuntimePlan, ConfigErrors, compileRuntimePlan)
import Infernix.ExecutionPlan.Internal (RawRuntimeConfig (..))
import Infernix.Types
import Numeric.Natural (Natural)

demoConfigGeneratedBannerLine :: String
demoConfigGeneratedBannerLine = "{- Auto-generated by infernix substrate materialization -}"

demoConfigGeneratedBanner :: String
demoConfigGeneratedBanner = demoConfigGeneratedBannerLine <> "\n"

encodeSubstrateConfig :: DemoConfig -> Lazy.ByteString
encodeSubstrateConfig demoConfig =
  Lazy.fromStrict
    ( TextEncoding.encodeUtf8
        (Text.pack (demoConfigGeneratedBanner <> renderSubstrateConfig demoConfig))
    )

decodeSubstrateConfigFile :: FilePath -> IO DemoConfig
decodeSubstrateConfigFile filePath = do
  RawRuntimeConfig config <- decodeRawRuntimeConfigFile filePath
  pure config

-- | Decode the generated Dhall into the opaque untrusted input accepted by the
-- execution-plan compiler.  New routing and launch consumers use this boundary
-- and cannot inspect the raw record.
decodeRawRuntimeConfigFile :: FilePath -> IO RawRuntimeConfig
decodeRawRuntimeConfigFile filePath = do
  decodedValue <- try (Dhall.inputFile Dhall.auto filePath :: IO DhallDemoConfig)
  case decodedValue of
    Left err -> do
      -- Phase 8 Sprint 8.9: a payload written by a pre-union generator fails
      -- the schema with a raw structural Dhall type error that says nothing
      -- about what to do. Name the retired shape and the command that replaces
      -- it before falling back to the generic diagnostic.
      legacyShape <- classifyRetiredSubstrateShape filePath
      ioError
        ( userError
            ( "invalid generated substrate Dhall: "
                <> maybe "" (<> "\n") legacyShape
                <> displayException (err :: SomeException)
            )
        )
    Right rawConfig ->
      case demoConfigFromDhall rawConfig of
        Left message -> ioError (userError ("invalid generated substrate Dhall: " <> message))
        Right demoConfig -> pure (RawRuntimeConfig demoConfig)

-- | Phase 8 Sprint 8.9 — recognise the retired flat, text-discriminated
-- execution-plan payloads and name them. Every generated @.dhall@ is produced
-- by this binary and is never version-controlled, so a payload carrying one of
-- these retired shapes is always a stale file left by an older binary, and the
-- fix is always to regenerate it. The check reads the file as text and looks
-- only for retired *field* spellings, so it cannot misfire on a current
-- payload: the union arms carry no @kind@ discriminator and no flat
-- @podLimitMib@ / @inferenceRamBudgetMib@ scalar, the enum fields are matched
-- together with the opening quote a union value never has, and @edgePort@ is no
-- longer emitted at all.
classifyRetiredSubstrateShape :: FilePath -> IO (Maybe String)
classifyRetiredSubstrateShape filePath = do
  contents <- try (TextIO.readFile filePath)
  pure $
    case contents of
      Left (_ :: SomeException) -> Nothing
      Right payload ->
        case [description | (marker, description) <- retiredSubstrateMarkers, marker `Text.isInfixOf` payload] of
          [] -> Nothing
          description : _ ->
            Just
              ( "this file carries the retired "
                  <> description
                  <> ". Every enum-like choice in the generated execution-plan"
                  <> " language is now a Dhall union rather than a Text tag, and no"
                  <> " `.dhall` is version-controlled: delete it and re-run"
                  <> " `infernix init` (or `infernix test init` for the harness input)"
                  <> " to regenerate it with the current binary."
              )

retiredSubstrateMarkers :: [(Text, String)]
retiredSubstrateMarkers =
  [ ("inferenceRamBudgetMib", "flat `inferenceRamBudgetMib` scalar budget"),
    ("kind =", "text-discriminated `kind =` inference-memory-budget record"),
    ("podLimitMib", "flat `podLimitMib` inference-memory-budget field"),
    -- Phase 8 Sprint 8.9 retired the remaining text-tagged enums. Match the
    -- retired spellings with their surrounding `field = "` so a current payload
    -- — which now writes `runtimeMode = < … >.LinuxCpu` — cannot match, and so
    -- a stale file reports the migration instead of a bare Dhall type error.
    -- `daemonRole` is listed first among these because it is the one field whose
    -- retired aliases (`frontend`, `cluster`, `host`) a union cannot express at
    -- all, so its stale payloads have no other diagnosis.
    ("daemonRole = \"", "text-tagged `daemonRole` field"),
    ("runtimeMode = \"", "text-tagged `runtimeMode` field"),
    ("runtimeLane = \"", "text-tagged `runtimeLane` field"),
    ("subscription = \"", "text-tagged engine-pool `subscription` field"),
    ("pulsarConnectionMode = \"", "text-tagged `pulsarConnectionMode` field"),
    ("adapterType = \"", "text-tagged engine-binding `adapterType` field"),
    ("fieldType = \"", "text-tagged request-shape `fieldType` field"),
    ("edgePort = ", "retired generated `edgePort` field, which no consumer ever read")
  ]

decodeCompiledRuntimePlanFile :: FilePath -> IO (Either ConfigErrors CompiledRuntimePlan)
decodeCompiledRuntimePlanFile filePath =
  compileRuntimePlan <$> decodeRawRuntimeConfigFile filePath

resolveRuntimeModeFromSubstrateFile :: FilePath -> IO RuntimeMode
resolveRuntimeModeFromSubstrateFile filePath =
  configRuntimeMode <$> decodeSubstrateConfigFile filePath

renderSubstrateConfigSchema :: Either String Text
renderSubstrateConfigSchema =
  renderDecoderExpected (Dhall.auto @DhallDemoConfig)

data DhallDemoConfig = DhallDemoConfig
  { dhallConfigRuntimeMode :: DhallRuntimeMode,
    dhallConfigMapName :: Text,
    dhallGeneratedPath :: Text,
    dhallMountedPath :: Text,
    dhallDemoUi :: Bool,
    dhallDaemonRole :: DhallDaemonRole,
    dhallCoordinator :: DhallDaemonConfig,
    dhallWebapp :: DhallDaemonConfig,
    dhallEngineDaemons :: [DhallDaemonConfig],
    dhallEnginePools :: [DhallEnginePool],
    dhallEngineMembers :: [DhallEngineMember],
    dhallConfigRequestTopics :: [Text],
    dhallConfigResultTopic :: Text,
    dhallModelsBucket :: Text,
    dhallModelBootstrapTopic :: Text,
    dhallEngines :: [DhallEngineBinding],
    dhallModels :: [DhallModelDescriptor],
    dhallInferenceMemoryBudget :: DhallInferenceMemoryBudget
  }
  deriving (Generic)

instance Dhall.FromDhall DhallDemoConfig where
  autoWith _ = Dhall.genericAutoWith dhallInterpretOptions

data DhallDaemonConfig = DhallDaemonConfig
  { dhallRole :: DhallDaemonRole,
    dhallLocation :: Text,
    dhallMemberId :: Maybe Text,
    dhallDaemonRequestTopics :: [Text],
    dhallDaemonResultTopic :: Text,
    dhallPulsarConnectionMode :: DhallPulsarConnectionMode
  }
  deriving (Generic)

instance Dhall.FromDhall DhallDaemonConfig where
  autoWith _ = Dhall.genericAutoWith dhallInterpretOptions

data DhallEnginePool = DhallEnginePool
  { dhallPoolId :: Text,
    dhallPoolRuntimeMode :: DhallRuntimeMode,
    dhallPoolModelIds :: [Text],
    dhallPoolMemberIds :: [Text],
    dhallPoolSubscriptionType :: DhallConsumerSubscription,
    dhallMaxInflightPerMember :: Natural
  }
  deriving (Generic)

instance Dhall.FromDhall DhallEnginePool where
  autoWith _ = Dhall.genericAutoWith dhallInterpretOptions

data DhallEngineMember = DhallEngineMember
  { dhallMemberConfigId :: Text,
    dhallMemberRuntimeMode :: DhallRuntimeMode,
    dhallMemberLocation :: Text,
    dhallMemberPoolIds :: [Text]
  }
  deriving (Generic)

instance Dhall.FromDhall DhallEngineMember where
  autoWith _ = Dhall.genericAutoWith dhallInterpretOptions

data DhallEngineBinding = DhallEngineBinding
  { dhallEngine :: Text,
    dhallAdapterId :: Text,
    dhallAdapterType :: DhallEngineAdapterType,
    dhallAdapterLocator :: Text,
    dhallAdapterEntrypoint :: Text,
    dhallSetupEntrypoint :: Text,
    dhallProjectDirectory :: Text,
    dhallPythonNative :: Bool
  }
  deriving (Generic)

instance Dhall.FromDhall DhallEngineBinding where
  autoWith _ = Dhall.genericAutoWith dhallInterpretOptions

data DhallModelDescriptor = DhallModelDescriptor
  { dhallMatrixRowId :: Text,
    dhallModelId :: Text,
    dhallDisplayName :: Text,
    dhallFamily :: Text,
    dhallDescription :: Text,
    dhallArtifactType :: Text,
    dhallReferenceModel :: Text,
    dhallDownloadUrl :: Text,
    dhallSelectedEngine :: Text,
    dhallRequestShape :: [DhallRequestField],
    dhallModelRuntimeMode :: DhallRuntimeMode,
    dhallRuntimeLane :: DhallRuntimeLane,
    dhallRequiresGpu :: Bool,
    dhallNotes :: Text,
    dhallModelRamFootprintMib :: Natural
  }
  deriving (Generic)

instance Dhall.FromDhall DhallModelDescriptor where
  autoWith _ = Dhall.genericAutoWith dhallInterpretOptions

-- | The generated execution-plan budget is a proper union. An arm carries only
-- its applicable fields, so the retired text discriminator plus zero-filled
-- fields cannot be represented.
data DhallInferenceMemoryBudget
  = HostEnforced DhallHostMemoryBudget
  | SubstrateEnforced DhallSubstrateMemoryBudget
  | DualEnforced DhallDualMemoryBudget
  deriving (Generic)

instance Dhall.FromDhall DhallInferenceMemoryBudget

data DhallHostMemoryBudget = DhallHostMemoryBudget
  { dhallBudgetPhysicalMib :: Natural,
    dhallBudgetVmReserveMib :: Natural,
    dhallBudgetHeadroomMib :: Natural
  }
  deriving (Generic)

instance Dhall.FromDhall DhallHostMemoryBudget where
  autoWith _ = Dhall.genericAutoWith dhallInterpretOptions

data DhallSubstrateMemoryBudget = DhallSubstrateMemoryBudget
  { dhallBudgetResource :: DhallInferenceMemoryResource,
    dhallBudgetSource :: DhallPodMemoryLimitSource,
    dhallBudgetLimitMib :: Natural
  }
  deriving (Generic)

instance Dhall.FromDhall DhallSubstrateMemoryBudget where
  autoWith _ = Dhall.genericAutoWith dhallInterpretOptions

-- | Phase 6 Sprint 6.44 — the @linux-gpu@ arm. It reuses the substrate limit
-- record for both halves, so the two limits are structurally identical and the
-- arm names which is which rather than encoding it in a discriminator field.
data DhallDualMemoryBudget = DhallDualMemoryBudget
  { dhallBudgetPodLimit :: DhallSubstrateMemoryBudget,
    dhallBudgetVramLimit :: DhallSubstrateMemoryBudget
  }
  deriving (Generic)

instance Dhall.FromDhall DhallDualMemoryBudget where
  autoWith _ = Dhall.genericAutoWith dhallInterpretOptions

data DhallRequestField = DhallRequestField
  { dhallName :: Text,
    dhallLabel :: Text,
    dhallFieldType :: DhallRequestFieldType
  }
  deriving (Generic)

instance Dhall.FromDhall DhallRequestField where
  autoWith _ = Dhall.genericAutoWith dhallInterpretOptions

-- | Phase 8 Sprint 8.9 — the generated wire's enum-like choices are Dhall
-- unions, not @Text@ refined after decode.
--
-- Each mirror below carries a type-specific Haskell constructor prefix, because
-- several of them name an alternative the domain type also names and Haskell
-- has one constructor namespace per module. 'dhallEnumInterpretOptions' strips
-- that prefix, so the /wire/ alternative is exactly the suffix. Alternatives are
-- identifier-shaped (@AppleSilicon@, not @apple-silicon@) because a Dhall
-- alternative is a label rather than a string — which is the whole point of
-- retiring the text tags. Refinement is a total case match: an unsupported
-- spelling is now a structural type error at decode rather than a
-- post-decode @parseEnum@ failure.
--
-- One consequence is deliberate and recorded rather than incidental:
-- 'parseDaemonRole' accepts three retired aliases (@frontend@, @cluster@,
-- @host@) that the renderer has never emitted. A union cannot express an alias,
-- so a stale @.dhall@ carrying one is now a decode failure. The retired-shape
-- classifier names it.
dhallEnumInterpretOptions :: Text -> Dhall.InterpretOptions
dhallEnumInterpretOptions constructorPrefix =
  Dhall.defaultInterpretOptions
    { Dhall.constructorModifier =
        \constructorName ->
          fromMaybe constructorName (Text.stripPrefix constructorPrefix constructorName)
    }

-- | The rendered spelling of an enum-only union. Both the value renderer and
-- every record-type annotation that contains the field select from one of these
-- values, so an annotation cannot drift from the value it annotates.
dhallEnumUnionType :: [String] -> String
dhallEnumUnionType alternatives =
  "< " <> intercalate " | " alternatives <> " >"

dhallEnumValue :: String -> String -> String
dhallEnumValue unionType alternative = unionType <> "." <> alternative

data DhallRuntimeMode
  = DhallRuntimeModeAppleSilicon
  | DhallRuntimeModeLinuxCpu
  | DhallRuntimeModeLinuxGpu
  deriving (Generic)

instance Dhall.FromDhall DhallRuntimeMode where
  autoWith _ = Dhall.genericAutoWith (dhallEnumInterpretOptions "DhallRuntimeMode")

runtimeModeFromDhall :: DhallRuntimeMode -> RuntimeMode
runtimeModeFromDhall rawRuntimeMode = case rawRuntimeMode of
  DhallRuntimeModeAppleSilicon -> AppleSilicon
  DhallRuntimeModeLinuxCpu -> LinuxCpu
  DhallRuntimeModeLinuxGpu -> LinuxGpu

runtimeModeAlternative :: RuntimeMode -> String
runtimeModeAlternative runtimeModeValue = case runtimeModeValue of
  AppleSilicon -> "AppleSilicon"
  LinuxCpu -> "LinuxCpu"
  LinuxGpu -> "LinuxGpu"

runtimeModeUnionType :: String
runtimeModeUnionType = dhallEnumUnionType (map runtimeModeAlternative allRuntimeModes)

renderRuntimeMode :: RuntimeMode -> String
renderRuntimeMode = dhallEnumValue runtimeModeUnionType . runtimeModeAlternative

data DhallDaemonRole
  = DhallDaemonRoleCoordinator
  | DhallDaemonRoleEngine
  | DhallDaemonRoleWebapp
  deriving (Generic)

instance Dhall.FromDhall DhallDaemonRole where
  autoWith _ = Dhall.genericAutoWith (dhallEnumInterpretOptions "DhallDaemonRole")

daemonRoleFromDhall :: DhallDaemonRole -> DaemonRole
daemonRoleFromDhall rawRole = case rawRole of
  DhallDaemonRoleCoordinator -> Coordinator
  DhallDaemonRoleEngine -> Engine
  DhallDaemonRoleWebapp -> Webapp

daemonRoleAlternative :: DaemonRole -> String
daemonRoleAlternative role = case role of
  Coordinator -> "Coordinator"
  Engine -> "Engine"
  Webapp -> "Webapp"

daemonRoleUnionType :: String
daemonRoleUnionType =
  dhallEnumUnionType (map daemonRoleAlternative [Coordinator, Engine, Webapp])

renderDaemonRole :: DaemonRole -> String
renderDaemonRole = dhallEnumValue daemonRoleUnionType . daemonRoleAlternative

data DhallConsumerSubscription
  = DhallConsumerSubscriptionShared
  | DhallConsumerSubscriptionExclusive
  | DhallConsumerSubscriptionFailover
  deriving (Generic)

instance Dhall.FromDhall DhallConsumerSubscription where
  autoWith _ =
    Dhall.genericAutoWith (dhallEnumInterpretOptions "DhallConsumerSubscription")

consumerSubscriptionFromDhall :: DhallConsumerSubscription -> ConsumerSubscriptionType
consumerSubscriptionFromDhall rawSubscription = case rawSubscription of
  DhallConsumerSubscriptionShared -> ConsumerShared
  DhallConsumerSubscriptionExclusive -> ConsumerExclusive
  DhallConsumerSubscriptionFailover -> ConsumerFailover

consumerSubscriptionAlternative :: ConsumerSubscriptionType -> String
consumerSubscriptionAlternative subscription = case subscription of
  ConsumerShared -> "Shared"
  ConsumerExclusive -> "Exclusive"
  ConsumerFailover -> "Failover"

consumerSubscriptionUnionType :: String
consumerSubscriptionUnionType =
  dhallEnumUnionType
    (map consumerSubscriptionAlternative [ConsumerShared, ConsumerExclusive, ConsumerFailover])

renderConsumerSubscription :: ConsumerSubscriptionType -> String
renderConsumerSubscription =
  dhallEnumValue consumerSubscriptionUnionType . consumerSubscriptionAlternative

data DhallPulsarConnectionMode
  = DhallPulsarConnectionModeConfiguredTransport
  | DhallPulsarConnectionModePublicationEdgeAutoDiscovery
  deriving (Generic)

instance Dhall.FromDhall DhallPulsarConnectionMode where
  autoWith _ =
    Dhall.genericAutoWith (dhallEnumInterpretOptions "DhallPulsarConnectionMode")

pulsarConnectionModeFromDhall :: DhallPulsarConnectionMode -> PulsarConnectionMode
pulsarConnectionModeFromDhall rawMode = case rawMode of
  DhallPulsarConnectionModeConfiguredTransport -> ConfiguredTransport
  DhallPulsarConnectionModePublicationEdgeAutoDiscovery -> PublicationEdgeAutoDiscovery

pulsarConnectionModeAlternative :: PulsarConnectionMode -> String
pulsarConnectionModeAlternative connectionMode = case connectionMode of
  ConfiguredTransport -> "ConfiguredTransport"
  PublicationEdgeAutoDiscovery -> "PublicationEdgeAutoDiscovery"

pulsarConnectionModeUnionType :: String
pulsarConnectionModeUnionType =
  dhallEnumUnionType
    ( map
        pulsarConnectionModeAlternative
        [ConfiguredTransport, PublicationEdgeAutoDiscovery]
    )

renderPulsarConnectionMode :: PulsarConnectionMode -> String
renderPulsarConnectionMode =
  dhallEnumValue pulsarConnectionModeUnionType . pulsarConnectionModeAlternative

data DhallRuntimeLane
  = DhallRuntimeLaneAppleSiliconHost
  | DhallRuntimeLaneKindLinuxCpu
  | DhallRuntimeLaneKindLinuxGpuGpu
  | DhallRuntimeLaneKindLinuxGpuShared
  deriving (Generic)

instance Dhall.FromDhall DhallRuntimeLane where
  autoWith _ = Dhall.genericAutoWith (dhallEnumInterpretOptions "DhallRuntimeLane")

runtimeLaneFromDhall :: DhallRuntimeLane -> RuntimeLane
runtimeLaneFromDhall rawLane = case rawLane of
  DhallRuntimeLaneAppleSiliconHost -> AppleSiliconHost
  DhallRuntimeLaneKindLinuxCpu -> KindLinuxCpu
  DhallRuntimeLaneKindLinuxGpuGpu -> KindLinuxGpuGpu
  DhallRuntimeLaneKindLinuxGpuShared -> KindLinuxGpuShared

runtimeLaneAlternative :: RuntimeLane -> String
runtimeLaneAlternative lane = case lane of
  AppleSiliconHost -> "AppleSiliconHost"
  KindLinuxCpu -> "KindLinuxCpu"
  KindLinuxGpuGpu -> "KindLinuxGpuGpu"
  KindLinuxGpuShared -> "KindLinuxGpuShared"

runtimeLaneUnionType :: String
runtimeLaneUnionType =
  dhallEnumUnionType
    ( map
        runtimeLaneAlternative
        [AppleSiliconHost, KindLinuxCpu, KindLinuxGpuGpu, KindLinuxGpuShared]
    )

renderRuntimeLane :: RuntimeLane -> String
renderRuntimeLane = dhallEnumValue runtimeLaneUnionType . runtimeLaneAlternative

-- | The one mirror that cannot use the generic derivation.
--
-- @genericAutoWith@ dispatches on the datatype's GHC-Generics shape, and a
-- single-constructor type has no @:+:@ at all, so it derives as a /record/ —
-- here the empty record @{}@ — rather than as a one-alternative union. Building
-- the union decoder explicitly keeps the wire shape @< TextField >@, so adding
-- a second request-field type later is a wire addition rather than a wire
-- rewrite. The round-trip through the real decode boundary is what catches this;
-- the annotation and the decoder are otherwise unrelated.
data DhallRequestFieldType
  = DhallRequestFieldTypeTextField

instance Dhall.FromDhall DhallRequestFieldType where
  autoWith _ =
    Dhall.union (DhallRequestFieldTypeTextField <$ Dhall.constructor "TextField" Dhall.unit)

requestFieldTypeFromDhall :: DhallRequestFieldType -> RequestFieldType
requestFieldTypeFromDhall rawFieldType = case rawFieldType of
  DhallRequestFieldTypeTextField -> TextRequestField

requestFieldTypeAlternative :: RequestFieldType -> String
requestFieldTypeAlternative fieldTypeValue = case fieldTypeValue of
  TextRequestField -> "TextField"

requestFieldTypeUnionType :: String
requestFieldTypeUnionType =
  dhallEnumUnionType [requestFieldTypeAlternative TextRequestField]

renderRequestFieldType :: RequestFieldType -> String
renderRequestFieldType =
  dhallEnumValue requestFieldTypeUnionType . requestFieldTypeAlternative

data DhallEngineAdapterType
  = DhallEngineAdapterTypeNativeProcessRunner
  | DhallEngineAdapterTypePythonStdio
  deriving (Generic)

instance Dhall.FromDhall DhallEngineAdapterType where
  autoWith _ = Dhall.genericAutoWith (dhallEnumInterpretOptions "DhallEngineAdapterType")

engineAdapterTypeFromDhall :: DhallEngineAdapterType -> EngineAdapterType
engineAdapterTypeFromDhall rawAdapterType = case rawAdapterType of
  DhallEngineAdapterTypeNativeProcessRunner -> NativeProcessRunner
  DhallEngineAdapterTypePythonStdio -> PythonStdio

engineAdapterTypeAlternative :: EngineAdapterType -> String
engineAdapterTypeAlternative adapterType = case adapterType of
  NativeProcessRunner -> "NativeProcessRunner"
  PythonStdio -> "PythonStdio"

engineAdapterTypeUnionType :: String
engineAdapterTypeUnionType =
  dhallEnumUnionType
    (map engineAdapterTypeAlternative [NativeProcessRunner, PythonStdio])

renderEngineAdapterType :: EngineAdapterType -> String
renderEngineAdapterType =
  dhallEnumValue engineAdapterTypeUnionType . engineAdapterTypeAlternative

data DhallInferenceMemoryResource
  = DhallInferenceMemoryResourceUnifiedHostRam
  | DhallInferenceMemoryResourcePodRam
  | DhallInferenceMemoryResourceGpuVram
  deriving (Generic)

instance Dhall.FromDhall DhallInferenceMemoryResource where
  autoWith _ =
    Dhall.genericAutoWith (dhallEnumInterpretOptions "DhallInferenceMemoryResource")

inferenceMemoryResourceFromDhall :: DhallInferenceMemoryResource -> InferenceMemoryResource
inferenceMemoryResourceFromDhall rawResource = case rawResource of
  DhallInferenceMemoryResourceUnifiedHostRam -> UnifiedHostRam
  DhallInferenceMemoryResourcePodRam -> PodRam
  DhallInferenceMemoryResourceGpuVram -> GpuVram

inferenceMemoryResourceAlternative :: InferenceMemoryResource -> String
inferenceMemoryResourceAlternative resource = case resource of
  UnifiedHostRam -> "UnifiedHostRam"
  PodRam -> "PodRam"
  GpuVram -> "GpuVram"

inferenceMemoryResourceUnionType :: String
inferenceMemoryResourceUnionType =
  dhallEnumUnionType
    (map inferenceMemoryResourceAlternative [UnifiedHostRam, PodRam, GpuVram])

renderInferenceMemoryResource :: InferenceMemoryResource -> String
renderInferenceMemoryResource =
  dhallEnumValue inferenceMemoryResourceUnionType . inferenceMemoryResourceAlternative

data DhallPodMemoryLimitSource
  = DhallPodMemoryLimitSourceClusterEnginePodMemoryLimit
  | DhallPodMemoryLimitSourceLinuxGpuVramBudget
  deriving (Generic)

instance Dhall.FromDhall DhallPodMemoryLimitSource where
  autoWith _ =
    Dhall.genericAutoWith (dhallEnumInterpretOptions "DhallPodMemoryLimitSource")

podMemoryLimitSourceFromDhall :: DhallPodMemoryLimitSource -> PodMemoryLimitSource
podMemoryLimitSourceFromDhall rawSource = case rawSource of
  DhallPodMemoryLimitSourceClusterEnginePodMemoryLimit -> ClusterEnginePodMemoryLimit
  DhallPodMemoryLimitSourceLinuxGpuVramBudget -> LinuxGpuVramBudget

podMemoryLimitSourceAlternative :: PodMemoryLimitSource -> String
podMemoryLimitSourceAlternative limitSource = case limitSource of
  ClusterEnginePodMemoryLimit -> "ClusterEnginePodMemoryLimit"
  LinuxGpuVramBudget -> "LinuxGpuVramBudget"

podMemoryLimitSourceUnionType :: String
podMemoryLimitSourceUnionType =
  dhallEnumUnionType
    ( map
        podMemoryLimitSourceAlternative
        [ClusterEnginePodMemoryLimit, LinuxGpuVramBudget]
    )

renderPodMemoryLimitSource :: PodMemoryLimitSource -> String
renderPodMemoryLimitSource =
  dhallEnumValue podMemoryLimitSourceUnionType . podMemoryLimitSourceAlternative

-- | Convert a wire 'Natural' into the platform 'Int' the domain types use.
--
-- Phase 8 Sprint 8.9 moved every generated quantity from Dhall @Integer@ to
-- @Natural@, so a negative quantity is no longer representable in the wire
-- language at all rather than being rejected after decode. What @Natural@ does
-- not bound is the top: fail closed on a value the platform integer cannot hold
-- instead of wrapping it into a small positive one.
naturalToInt :: String -> Natural -> Either String Int
naturalToInt fieldPath value
  | toInteger value > toInteger (maxBound :: Int) =
      Left (fieldPath <> " exceeds the supported integer range: " <> show value)
  | otherwise = Right (fromIntegral value)

dhallInterpretOptions :: Dhall.InterpretOptions
dhallInterpretOptions =
  Dhall.defaultInterpretOptions {Dhall.fieldModifier = dhallFieldName}

dhallFieldName :: Text -> Text
-- Phase 8 Sprint 8.9 removed the @legacyDhall@ prefix branch: the pre-union
-- decoder it served is gone and no field carried that prefix any more, so the
-- branch was dead compatibility residue rather than a supported spelling.
dhallFieldName rawFieldName =
  maybe rawFieldName dhallFieldSuffixName (Text.stripPrefix "dhall" rawFieldName)

dhallFieldSuffixName :: Text -> Text
dhallFieldSuffixName suffix =
  case suffix of
    "ConfigRuntimeMode" -> "runtimeMode"
    "ConfigRequestTopics" -> "request_topics"
    "ConfigResultTopic" -> "result_topic"
    "DaemonRequestTopics" -> "request_topics"
    "DaemonResultTopic" -> "result_topic"
    "ModelRuntimeMode" -> "runtimeMode"
    "DemoUi" -> "demo_ui"
    "RequestTopics" -> "request_topics"
    "ResultTopic" -> "result_topic"
    "MemberId" -> "memberId"
    "ModelsBucket" -> "models_bucket"
    "ModelBootstrapTopic" -> "model_bootstrap_topic"
    "InferenceMemoryBudget" -> "inferenceMemoryBudget"
    "BudgetResource" -> "resource"
    "BudgetSource" -> "source"
    "BudgetPhysicalMib" -> "physicalMib"
    "BudgetVmReserveMib" -> "vmReserveMib"
    "BudgetHeadroomMib" -> "headroomMib"
    "BudgetLimitMib" -> "limitMib"
    "BudgetPodLimit" -> "podLimit"
    "BudgetVramLimit" -> "vramLimit"
    "EnginePools" -> "enginePools"
    "EngineMembers" -> "engineMembers"
    "PoolId" -> "id"
    "PoolRuntimeMode" -> "runtimeMode"
    "PoolModelIds" -> "models"
    "PoolMemberIds" -> "members"
    "PoolSubscriptionType" -> "subscription"
    "MemberConfigId" -> "id"
    "MemberRuntimeMode" -> "runtimeMode"
    "MemberLocation" -> "location"
    "MemberPoolIds" -> "pools"
    other -> lowerInitial other

lowerInitial :: Text -> Text
lowerInitial value =
  case Text.uncons value of
    Nothing -> value
    Just (firstCharacter, rest) -> Text.cons (toLower firstCharacter) rest

demoConfigFromDhall :: DhallDemoConfig -> Either String DemoConfig
demoConfigFromDhall rawConfig = do
  let runtimeModeValue = runtimeModeFromDhall (dhallConfigRuntimeMode rawConfig)
      activeDaemonRoleValue = daemonRoleFromDhall (dhallDaemonRole rawConfig)
  coordinatorDaemonValue <- withDefaultConsumerSubscriptionType runtimeModeValue <$> daemonConfigFromDhall (dhallCoordinator rawConfig)
  webappDaemonValue <- withDefaultConsumerSubscriptionType runtimeModeValue <$> daemonConfigFromDhall (dhallWebapp rawConfig)
  parsedEngineDaemonValues <- traverse (fmap (withDefaultConsumerSubscriptionType runtimeModeValue) . daemonConfigFromDhall) (dhallEngineDaemons rawConfig)
  enginePoolValues <- traverse enginePoolFromDhall (dhallEnginePools rawConfig)
  engineMemberValues <- traverse engineMemberFromDhall (dhallEngineMembers rawConfig)
  engineValues <- traverse engineBindingFromDhall (dhallEngines rawConfig)
  modelValues <- traverse modelDescriptorFromDhall (dhallModels rawConfig)
  memoryBudgetValue <- inferenceMemoryBudgetFromDhall (dhallInferenceMemoryBudget rawConfig)
  let engineDaemonValues =
        if null parsedEngineDaemonValues
          then deriveEngineDaemonConfigs runtimeModeValue enginePoolValues engineMemberValues (dhallConfigResultTopic rawConfig)
          else parsedEngineDaemonValues
  pure
    DemoConfig
      { configRuntimeMode = runtimeModeValue,
        configMapName = dhallConfigMapName rawConfig,
        generatedPath = Text.unpack (dhallGeneratedPath rawConfig),
        mountedPath = Text.unpack (dhallMountedPath rawConfig),
        demoUiEnabled = dhallDemoUi rawConfig,
        activeDaemonRole = activeDaemonRoleValue,
        coordinatorDaemon = coordinatorDaemonValue,
        webappDaemon = webappDaemonValue,
        engineDaemons = engineDaemonValues,
        enginePools = enginePoolValues,
        engineMembers = engineMemberValues,
        requestTopics = dhallConfigRequestTopics rawConfig,
        resultTopic = dhallConfigResultTopic rawConfig,
        modelsBucket = dhallModelsBucket rawConfig,
        modelBootstrapTopic = dhallModelBootstrapTopic rawConfig,
        engines = engineValues,
        models = modelValues,
        inferenceMemoryBudget = memoryBudgetValue
      }

inferenceMemoryBudgetFromDhall :: DhallInferenceMemoryBudget -> Either String InferenceMemoryBudget
inferenceMemoryBudgetFromDhall rawBudget =
  case rawBudget of
    HostEnforced hostBudget -> do
      physicalMib <-
        naturalToInt "inferenceMemoryBudget.physicalMib" (dhallBudgetPhysicalMib hostBudget)
      vmReserveMib <-
        naturalToInt "inferenceMemoryBudget.vmReserveMib" (dhallBudgetVmReserveMib hostBudget)
      headroomMib <-
        naturalToInt "inferenceMemoryBudget.headroomMib" (dhallBudgetHeadroomMib hostBudget)
      HostEnforcedBudget <$> mkHostMemoryPartition physicalMib vmReserveMib headroomMib
    SubstrateEnforced substrateBudget ->
      SubstrateEnforcedBudget <$> podMemoryLimitFromDhall "inferenceMemoryBudget" substrateBudget
    DualEnforced dualBudget ->
      DualEnforcedBudget
        <$> podMemoryLimitFromDhall "inferenceMemoryBudget.podLimit" (dhallBudgetPodLimit dualBudget)
        <*> podMemoryLimitFromDhall "inferenceMemoryBudget.vramLimit" (dhallBudgetVramLimit dualBudget)

podMemoryLimitFromDhall ::
  String ->
  DhallSubstrateMemoryBudget ->
  Either String PodMemoryLimit
podMemoryLimitFromDhall fieldPath substrateBudget = do
  limitMib <- naturalToInt (fieldPath <> ".limitMib") (dhallBudgetLimitMib substrateBudget)
  -- @Natural@ already excludes a negative limit on the wire; zero is still
  -- representable, so the positivity check stays.
  if limitMib <= 0
    then Left (fieldPath <> ".limitMib must be positive")
    else
      pure
        PodMemoryLimit
          { podMemoryLimitResource =
              inferenceMemoryResourceFromDhall (dhallBudgetResource substrateBudget),
            podMemoryLimitSource =
              podMemoryLimitSourceFromDhall (dhallBudgetSource substrateBudget),
            podMemoryLimitMib = limitMib
          }

deriveEngineDaemonConfigs :: RuntimeMode -> [EnginePool] -> [EngineMember] -> Text -> [DaemonConfig]
deriveEngineDaemonConfigs runtimeMode pools members resultTopicValue =
  map engineDaemonConfigForMember members
  where
    engineDaemonConfigForMember member =
      DaemonConfig
        { daemonConfigRole = Engine,
          daemonConfigLocation = engineMemberLocation member,
          daemonConfigMemberId = Just (engineMemberId member),
          daemonConfigRequestTopics = derivedEngineMemberRequestTopics runtimeMode pools member,
          daemonConfigResultTopic = resultTopicValue,
          daemonConfigPulsarConnectionMode =
            if runtimeMode == AppleSilicon
              then PublicationEdgeAutoDiscovery
              else ConfiguredTransport,
          daemonConfigConsumerSubscriptionType = Just ConsumerShared
        }

derivedEngineMemberRequestTopics :: RuntimeMode -> [EnginePool] -> EngineMember -> [Text]
derivedEngineMemberRequestTopics runtimeMode pools member =
  [ derivedEnginePoolTopicForMode runtimeMode (enginePoolId pool) modelIdValue
  | pool <- pools,
    enginePoolId pool `elem` engineMemberPoolIds member,
    engineMemberId member `elem` enginePoolMemberIds pool,
    modelIdValue <- enginePoolModelIds pool
  ]

derivedEnginePoolTopicForMode :: RuntimeMode -> Text -> Text -> Text
derivedEnginePoolTopicForMode runtimeMode poolId modelIdValue =
  "persistent://infernix/demo/inference.batch."
    <> runtimeModeId runtimeMode
    <> ".pool."
    <> topicSegment poolId
    <> ".model."
    <> topicSegment modelIdValue

topicSegment :: Text -> Text
topicSegment =
  Text.map replaceInvalid
  where
    replaceInvalid character
      | isAlphaNum character || character == '-' || character == '_' || character == '.' = character
      | otherwise = '-'

daemonConfigFromDhall :: DhallDaemonConfig -> Either String DaemonConfig
daemonConfigFromDhall rawConfig = do
  let roleValue = daemonRoleFromDhall (dhallRole rawConfig)
      connectionModeValue =
        pulsarConnectionModeFromDhall (dhallPulsarConnectionMode rawConfig)
  pure
    DaemonConfig
      { daemonConfigRole = roleValue,
        daemonConfigLocation = dhallLocation rawConfig,
        daemonConfigMemberId = dhallMemberId rawConfig,
        daemonConfigRequestTopics = dhallDaemonRequestTopics rawConfig,
        daemonConfigResultTopic = dhallDaemonResultTopic rawConfig,
        daemonConfigPulsarConnectionMode = connectionModeValue,
        daemonConfigConsumerSubscriptionType = Nothing
      }

enginePoolFromDhall :: DhallEnginePool -> Either String EnginePool
enginePoolFromDhall rawPool = do
  maxInflight <-
    naturalToInt
      ("enginePools." <> Text.unpack (dhallPoolId rawPool) <> ".maxInflightPerMember")
      (dhallMaxInflightPerMember rawPool)
  pure
    EnginePool
      { enginePoolId = dhallPoolId rawPool,
        enginePoolRuntimeMode = runtimeModeFromDhall (dhallPoolRuntimeMode rawPool),
        enginePoolModelIds = dhallPoolModelIds rawPool,
        enginePoolMemberIds = dhallPoolMemberIds rawPool,
        enginePoolSubscriptionType =
          consumerSubscriptionFromDhall (dhallPoolSubscriptionType rawPool),
        enginePoolMaxInflightPerMember = maxInflight
      }

engineMemberFromDhall :: DhallEngineMember -> Either String EngineMember
engineMemberFromDhall rawMember =
  pure
    EngineMember
      { engineMemberId = dhallMemberConfigId rawMember,
        engineMemberRuntimeMode = runtimeModeFromDhall (dhallMemberRuntimeMode rawMember),
        engineMemberLocation = dhallMemberLocation rawMember,
        engineMemberPoolIds = dhallMemberPoolIds rawMember
      }

withDefaultConsumerSubscriptionType :: RuntimeMode -> DaemonConfig -> DaemonConfig
withDefaultConsumerSubscriptionType runtimeMode daemonConfig =
  daemonConfig
    { daemonConfigConsumerSubscriptionType =
        case daemonConfigConsumerSubscriptionType daemonConfig of
          Just subscriptionType -> Just subscriptionType
          Nothing -> Just (defaultConsumerSubscriptionType runtimeMode daemonConfig)
    }

defaultConsumerSubscriptionType :: RuntimeMode -> DaemonConfig -> ConsumerSubscriptionType
defaultConsumerSubscriptionType runtimeMode daemonConfig
  | runtimeMode == AppleSilicon
      && daemonConfigRole daemonConfig == Engine
      && daemonConfigLocation daemonConfig == "control-plane-host" =
      ConsumerShared
  | otherwise = ConsumerShared

engineBindingFromDhall :: DhallEngineBinding -> Either String EngineBinding
engineBindingFromDhall rawBinding =
  pure
    EngineBinding
      { engineBindingName = dhallEngine rawBinding,
        engineBindingAdapterId = dhallAdapterId rawBinding,
        engineBindingAdapterType = engineAdapterTypeFromDhall (dhallAdapterType rawBinding),
        engineBindingAdapterLocator = dhallAdapterLocator rawBinding,
        engineBindingAdapterEntrypoint = dhallAdapterEntrypoint rawBinding,
        engineBindingSetupEntrypoint = dhallSetupEntrypoint rawBinding,
        engineBindingProjectDirectory = Text.unpack (dhallProjectDirectory rawBinding),
        engineBindingPythonNative = dhallPythonNative rawBinding
      }

modelDescriptorFromDhall :: DhallModelDescriptor -> Either String ModelDescriptor
modelDescriptorFromDhall rawModel = do
  let runtimeModeValue = runtimeModeFromDhall (dhallModelRuntimeMode rawModel)
      runtimeLaneValue = runtimeLaneFromDhall (dhallRuntimeLane rawModel)
  requestShapeValue <- traverse requestFieldFromDhall (dhallRequestShape rawModel)
  -- Phase 4 Sprint 4.31: the footprint is required and positive; a model whose
  -- Dhall row carries an absent/zero footprint fails the decode closed.
  footprintMib <-
    naturalToInt
      ("models." <> Text.unpack (dhallModelId rawModel) <> ".modelRamFootprintMib")
      (dhallModelRamFootprintMib rawModel)
  footprintValue <- mkModelMemoryFootprint footprintMib
  pure
    ModelDescriptor
      { matrixRowId = dhallMatrixRowId rawModel,
        modelId = dhallModelId rawModel,
        displayName = dhallDisplayName rawModel,
        family = dhallFamily rawModel,
        description = dhallDescription rawModel,
        artifactType = dhallArtifactType rawModel,
        referenceModel = dhallReferenceModel rawModel,
        downloadUrl = dhallDownloadUrl rawModel,
        selectedEngine = dhallSelectedEngine rawModel,
        requestShape = requestShapeValue,
        runtimeMode = runtimeModeValue,
        runtimeLane = runtimeLaneValue,
        requiresGpu = dhallRequiresGpu rawModel,
        notes = dhallNotes rawModel,
        modelRamFootprint = footprintValue
      }

requestFieldFromDhall :: DhallRequestField -> Either String RequestField
requestFieldFromDhall rawField =
  pure
    RequestField
      { name = dhallName rawField,
        label = dhallLabel rawField,
        fieldType = requestFieldTypeFromDhall (dhallFieldType rawField)
      }

renderSubstrateConfig :: DemoConfig -> String
renderSubstrateConfig demoConfig =
  unlines
    [ "{ runtimeMode = " <> renderRuntimeMode (configRuntimeMode demoConfig),
      ", configMapName = " <> dhallText (configMapName demoConfig),
      ", generatedPath = " <> dhallFilePath (generatedPath demoConfig),
      ", mountedPath = " <> dhallFilePath (mountedPath demoConfig),
      ", demo_ui = " <> dhallBool (demoUiEnabled demoConfig),
      ", daemonRole = " <> renderDaemonRole (activeDaemonRole demoConfig),
      ", coordinator = " <> renderDaemonConfig (coordinatorDaemon demoConfig),
      ", webapp = " <> renderDaemonConfig (webappDaemon demoConfig),
      ", engineDaemons = " <> dhallList daemonConfigType renderDaemonConfig (engineDaemons demoConfig),
      ", enginePools = " <> dhallList enginePoolType renderEnginePool (enginePools demoConfig),
      ", engineMembers = " <> dhallList engineMemberType renderEngineMember (engineMembers demoConfig),
      ", request_topics = " <> dhallList "Text" dhallText (requestTopics demoConfig),
      ", result_topic = " <> dhallText (resultTopic demoConfig),
      ", models_bucket = " <> dhallText (modelsBucket demoConfig),
      ", model_bootstrap_topic = " <> dhallText (modelBootstrapTopic demoConfig),
      ", engines = " <> dhallList engineBindingType renderEngineBinding (engines demoConfig),
      ", models = " <> dhallList modelDescriptorType renderModelDescriptor (models demoConfig),
      ", inferenceMemoryBudget = " <> renderInferenceMemoryBudget (inferenceMemoryBudget demoConfig),
      "}"
    ]

-- | The single rendered spelling of the generated budget union. Every renderer
-- arm selects from this one value, so a new arm cannot be added to the Haskell
-- ADT and its decoder while some renderer keeps emitting a stale union type.
inferenceMemoryBudgetUnionType :: String
inferenceMemoryBudgetUnionType =
  "< HostEnforced : { physicalMib : Natural, vmReserveMib : Natural, headroomMib : Natural }"
    <> " | SubstrateEnforced : "
    <> substrateMemoryBudgetRecordType
    <> " | DualEnforced : { podLimit : "
    <> substrateMemoryBudgetRecordType
    <> ", vramLimit : "
    <> substrateMemoryBudgetRecordType
    <> " } >"

substrateMemoryBudgetRecordType :: String
substrateMemoryBudgetRecordType =
  "{ resource : "
    <> inferenceMemoryResourceUnionType
    <> ", source : "
    <> podMemoryLimitSourceUnionType
    <> ", limitMib : Natural }"

renderInferenceMemoryBudget :: InferenceMemoryBudget -> String
renderInferenceMemoryBudget budget =
  case budget of
    HostEnforcedBudget partition ->
      inferenceMemoryBudgetUnionType
        <> ".HostEnforced "
        <> "{ physicalMib = "
        <> dhallNatural (hostPartitionPhysicalMib partition)
        <> ", vmReserveMib = "
        <> dhallNatural (hostPartitionVmReserveMib partition)
        <> ", headroomMib = "
        <> dhallNatural (hostPartitionHeadroomMib partition)
        <> " }"
    SubstrateEnforcedBudget podLimit ->
      inferenceMemoryBudgetUnionType
        <> ".SubstrateEnforced "
        <> renderPodMemoryLimit podLimit
    DualEnforcedBudget podLimit vramLimit ->
      inferenceMemoryBudgetUnionType
        <> ".DualEnforced "
        <> "{ podLimit = "
        <> renderPodMemoryLimit podLimit
        <> ", vramLimit = "
        <> renderPodMemoryLimit vramLimit
        <> " }"

renderPodMemoryLimit :: PodMemoryLimit -> String
renderPodMemoryLimit podLimit =
  "{ resource = "
    <> renderInferenceMemoryResource (podMemoryLimitResource podLimit)
    <> ", source = "
    <> renderPodMemoryLimitSource (podMemoryLimitSource podLimit)
    <> ", limitMib = "
    <> dhallNatural (podMemoryLimitMib podLimit)
    <> " }"

renderDaemonConfig :: DaemonConfig -> String
renderDaemonConfig daemonConfig =
  "{ role = "
    <> renderDaemonRole (daemonConfigRole daemonConfig)
    <> ", location = "
    <> dhallText (daemonConfigLocation daemonConfig)
    <> ", memberId = "
    <> dhallOptional "Text" dhallText (daemonConfigMemberId daemonConfig)
    <> ", request_topics = "
    <> dhallList "Text" dhallText (daemonConfigRequestTopics daemonConfig)
    <> ", result_topic = "
    <> dhallText (daemonConfigResultTopic daemonConfig)
    <> ", pulsarConnectionMode = "
    <> renderPulsarConnectionMode (daemonConfigPulsarConnectionMode daemonConfig)
    <> " }"

renderEnginePool :: EnginePool -> String
renderEnginePool pool =
  "{ id = "
    <> dhallText (enginePoolId pool)
    <> ", runtimeMode = "
    <> renderRuntimeMode (enginePoolRuntimeMode pool)
    <> ", models = "
    <> dhallList "Text" dhallText (enginePoolModelIds pool)
    <> ", members = "
    <> dhallList "Text" dhallText (enginePoolMemberIds pool)
    <> ", subscription = "
    <> renderConsumerSubscription (enginePoolSubscriptionType pool)
    <> ", maxInflightPerMember = "
    <> dhallNatural (enginePoolMaxInflightPerMember pool)
    <> " }"

renderEngineMember :: EngineMember -> String
renderEngineMember member =
  "{ id = "
    <> dhallText (engineMemberId member)
    <> ", runtimeMode = "
    <> renderRuntimeMode (engineMemberRuntimeMode member)
    <> ", location = "
    <> dhallText (engineMemberLocation member)
    <> ", pools = "
    <> dhallList "Text" dhallText (engineMemberPoolIds member)
    <> " }"

renderEngineBinding :: EngineBinding -> String
renderEngineBinding engineBinding =
  "{ engine = "
    <> dhallText (engineBindingName engineBinding)
    <> ", adapterId = "
    <> dhallText (engineBindingAdapterId engineBinding)
    <> ", adapterType = "
    <> renderEngineAdapterType (engineBindingAdapterType engineBinding)
    <> ", adapterLocator = "
    <> dhallText (engineBindingAdapterLocator engineBinding)
    <> ", adapterEntrypoint = "
    <> dhallText (engineBindingAdapterEntrypoint engineBinding)
    <> ", setupEntrypoint = "
    <> dhallText (engineBindingSetupEntrypoint engineBinding)
    <> ", projectDirectory = "
    <> dhallFilePath (engineBindingProjectDirectory engineBinding)
    <> ", pythonNative = "
    <> dhallBool (engineBindingPythonNative engineBinding)
    <> " }"

renderModelDescriptor :: ModelDescriptor -> String
renderModelDescriptor model =
  "{ matrixRowId = "
    <> dhallText (matrixRowId model)
    <> ", modelId = "
    <> dhallText (modelId model)
    <> ", displayName = "
    <> dhallText (displayName model)
    <> ", family = "
    <> dhallText (family model)
    <> ", description = "
    <> dhallText (description model)
    <> ", artifactType = "
    <> dhallText (artifactType model)
    <> ", referenceModel = "
    <> dhallText (referenceModel model)
    <> ", downloadUrl = "
    <> dhallText (downloadUrl model)
    <> ", selectedEngine = "
    <> dhallText (selectedEngine model)
    <> ", requestShape = "
    <> dhallList requestFieldType renderRequestField (requestShape model)
    <> ", runtimeMode = "
    <> renderRuntimeMode (runtimeMode model)
    <> ", runtimeLane = "
    <> renderRuntimeLane (runtimeLane model)
    <> ", requiresGpu = "
    <> dhallBool (requiresGpu model)
    <> ", notes = "
    <> dhallText (notes model)
    <> ", modelRamFootprintMib = "
    <> dhallNatural (modelMemoryFootprintMib (modelRamFootprint model))
    <> " }"

renderRequestField :: RequestField -> String
renderRequestField requestField =
  "{ name = "
    <> dhallText (name requestField)
    <> ", label = "
    <> dhallText (label requestField)
    <> ", fieldType = "
    <> renderRequestFieldType (fieldType requestField)
    <> " }"

dhallList :: String -> (a -> String) -> [a] -> String
dhallList itemType renderItem values =
  case values of
    [] -> "([] : List " <> itemType <> ")"
    _ -> "[ " <> intercalate ", " (map renderItem values) <> " ]"

dhallOptional :: String -> (a -> String) -> Maybe a -> String
dhallOptional itemType renderItem value =
  case value of
    Nothing -> "None " <> itemType
    Just item -> "Some " <> renderItem item

dhallBool :: Bool -> String
dhallBool value
  | value = "True"
  | otherwise = "False"

-- | Render a generated quantity as a Dhall @Natural@ literal.
--
-- Every call site renders a value whose non-negativity was already established
-- by a checked constructor or a compiler check: 'mkHostMemoryPartition' rejects
-- a non-positive physical size and negative reserve/headroom,
-- 'mkModelMemoryFootprint' requires a positive footprint, @InvalidPoolMaxInflight@
-- rejects a non-positive inflight bound, and 'podMemoryLimitFromDhall' plus
-- config validation require a positive limit. A negative value would render as
-- an @Integer@ literal and fail the very next decode rather than round-tripping
-- silently.
dhallNatural :: Int -> String
dhallNatural = show

dhallFilePath :: FilePath -> String
dhallFilePath = dhallText . Text.pack

dhallText :: Text -> String
dhallText value =
  Text.unpack ("\"" <> DhallCore.escapeText value <> "\"")

enginePoolType :: String
enginePoolType =
  "{ id : Text, runtimeMode : "
    <> runtimeModeUnionType
    <> ", models : List Text, members : List Text, subscription : "
    <> consumerSubscriptionUnionType
    <> ", maxInflightPerMember : Natural }"

daemonConfigType :: String
daemonConfigType =
  "{ role : "
    <> daemonRoleUnionType
    <> ", location : Text, memberId : Optional Text, request_topics : List Text, result_topic : Text, pulsarConnectionMode : "
    <> pulsarConnectionModeUnionType
    <> " }"

engineMemberType :: String
engineMemberType =
  "{ id : Text, runtimeMode : "
    <> runtimeModeUnionType
    <> ", location : Text, pools : List Text }"

engineBindingType :: String
engineBindingType =
  "{ engine : Text, adapterId : Text, adapterType : "
    <> engineAdapterTypeUnionType
    <> ", adapterLocator : Text, adapterEntrypoint : Text, setupEntrypoint : Text, projectDirectory : Text, pythonNative : Bool }"

requestFieldType :: String
requestFieldType =
  "{ name : Text, label : Text, fieldType : "
    <> requestFieldTypeUnionType
    <> " }"

modelDescriptorType :: String
modelDescriptorType =
  "{ matrixRowId : Text, modelId : Text, displayName : Text, family : Text, description : Text, artifactType : Text, referenceModel : Text, downloadUrl : Text, selectedEngine : Text, requestShape : List "
    <> requestFieldType
    <> ", runtimeMode : "
    <> runtimeModeUnionType
    <> ", runtimeLane : "
    <> runtimeLaneUnionType
    <> ", requiresGpu : Bool, notes : Text, modelRamFootprintMib : Natural }"
