{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TypeApplications #-}

module Infernix.Substrate.Internal
  ( decodeSubstrateConfigFile,
    decodeCompiledRuntimePlanFile,
    decodeRawRuntimeConfigFile,
    demoConfigGeneratedBanner,
    demoConfigGeneratedBannerLine,
    encodeSubstrateConfig,
    renderSubstrateConfigSchema,
    renderSubstrateConfig,
    resolveRuntimeModeFromSubstrateFile,
  )
where

import Control.Exception (SomeException, displayException, try)
import Data.ByteString.Lazy qualified as Lazy
import Data.Char (isAlphaNum, toLower)
import Data.List (intercalate)
import Data.Maybe (fromMaybe)
import Data.Text (Text)
import Data.Text qualified as Text
import Data.Text.Encoding qualified as TextEncoding
import Data.Text.IO qualified as TextIO
import Dhall qualified
import Dhall.Core qualified as DhallCore
import GHC.Generics (Generic)
import Infernix.DhallSchema.Reflection (renderDecoderExpected)
import Infernix.EngineBindings (canonicalEngineBindingForSelectedEngine)
import Infernix.EngineRouting (requestTopicsForMode, resultTopicForMode)
import Infernix.ExecutionPlan (CompiledRuntimePlan, ConfigErrors, compileRuntimePlan)
import Infernix.ExecutionPlan.Internal (RawRuntimeConfig (..))
import Infernix.Types
import Numeric.Natural (Natural)

demoConfigGeneratedBannerLine :: String
demoConfigGeneratedBannerLine = "{- Auto-generated by infernix substrate materialization -}"

demoConfigGeneratedBanner :: String
demoConfigGeneratedBanner = demoConfigGeneratedBannerLine <> "\n"

encodeSubstrateConfig :: DemoConfig -> Lazy.ByteString
encodeSubstrateConfig demoConfig =
  Lazy.fromStrict
    ( TextEncoding.encodeUtf8
        (Text.pack (demoConfigGeneratedBanner <> renderSubstrateConfig demoConfig))
    )

decodeSubstrateConfigFile :: FilePath -> IO DemoConfig
decodeSubstrateConfigFile filePath = do
  RawRuntimeConfig config <- decodeRawRuntimeConfigFile filePath
  pure config

-- | Decode the generated Dhall into the opaque untrusted input accepted by the
-- execution-plan compiler.  New routing and launch consumers use this boundary
-- and cannot inspect the raw record.
decodeRawRuntimeConfigFile :: FilePath -> IO RawRuntimeConfig
decodeRawRuntimeConfigFile filePath = do
  decodedValue <- try (Dhall.inputFile Dhall.auto filePath :: IO DhallDemoConfig)
  case decodedValue of
    Left err -> do
      -- Phase 8 Sprint 8.9: a payload written by a pre-union generator fails
      -- the schema with a raw structural Dhall type error that says nothing
      -- about what to do. Name the retired shape and the command that replaces
      -- it before falling back to the generic diagnostic.
      legacyShape <- classifyRetiredSubstrateShape filePath
      ioError
        ( userError
            ( "invalid generated substrate Dhall: "
                <> maybe "" (<> "\n") legacyShape
                <> displayException (err :: SomeException)
            )
        )
    Right rawConfig ->
      case demoConfigFromDhall rawConfig of
        Left message -> ioError (userError ("invalid generated substrate Dhall: " <> message))
        Right demoConfig -> pure (RawRuntimeConfig demoConfig)

-- | Phase 8 Sprint 8.9 — recognise the retired flat, text-discriminated
-- execution-plan payloads and name them. Every generated @.dhall@ is produced
-- by this binary and is never version-controlled, so a payload carrying one of
-- these retired shapes is always a stale file left by an older binary, and the
-- fix is always to regenerate it. The check reads the file as text and looks
-- only for retired *field* spellings, so it cannot misfire on a current
-- payload: the union arms carry no @kind@ discriminator and no flat
-- @podLimitMib@ / @inferenceRamBudgetMib@ scalar, the enum fields are matched
-- together with the opening quote a union value never has, and @edgePort@ is no
-- longer emitted at all.
classifyRetiredSubstrateShape :: FilePath -> IO (Maybe String)
classifyRetiredSubstrateShape filePath = do
  contents <- try (TextIO.readFile filePath)
  pure $
    case contents of
      Left (_ :: SomeException) -> Nothing
      Right payload ->
        case [description | (marker, description) <- retiredSubstrateMarkers, marker `Text.isInfixOf` payload] of
          [] -> Nothing
          description : _ ->
            Just
              ( "this file carries the retired "
                  <> description
                  <> ". Every enum-like choice in the generated execution-plan"
                  <> " language is a Dhall union rather than a Text tag, and every"
                  <> " field the binary can derive has left the wire. No `.dhall` is"
                  <> " version-controlled: delete it and re-run `infernix init`"
                  <> " (or `infernix test init` for the harness input) to regenerate"
                  <> " it with the current binary."
              )

retiredSubstrateMarkers :: [(Text, String)]
retiredSubstrateMarkers =
  [ ("inferenceRamBudgetMib", "flat `inferenceRamBudgetMib` scalar budget"),
    ("kind =", "text-discriminated `kind =` inference-memory-budget record"),
    ("podLimitMib", "flat `podLimitMib` inference-memory-budget field"),
    -- Phase 8 Sprint 8.9 retired the remaining text-tagged enums. Match the
    -- retired spellings with their surrounding `field = "` so a current payload
    -- — which now writes `runtimeMode = < … >.LinuxCpu` — cannot match, and so
    -- a stale file reports the migration instead of a bare Dhall type error.
    -- `daemonRole` is listed first among these because it is the one field whose
    -- retired aliases (`frontend`, `cluster`, `host`) a union cannot express at
    -- all, so its stale payloads have no other diagnosis.
    ("daemonRole = \"", "text-tagged `daemonRole` field"),
    ("runtimeMode = \"", "text-tagged `runtimeMode` field"),
    ("runtimeLane = \"", "text-tagged `runtimeLane` field"),
    ("subscription = \"", "text-tagged engine-pool `subscription` field"),
    ("pulsarConnectionMode = \"", "text-tagged `pulsarConnectionMode` field"),
    ("adapterType = \"", "text-tagged engine-binding `adapterType` field"),
    ("fieldType = \"", "text-tagged request-shape `fieldType` field"),
    ("edgePort = ", "generated `edgePort` field, which no consumer ever read"),
    -- Phase 8 Sprint 8.10 deleted every field that was a second copy of a fact
    -- the binary derives. Each one gets its own marker so a stale file names the
    -- field it still carries rather than reporting a bare Dhall type error at
    -- whichever record the decoder happened to reach first. The markers match
    -- the retired spelling together with its `= ` so a field name that merely
    -- appears inside a topic string cannot match.
    ("request_topics = ", "generated `request_topics` field, now derived from the runtime mode"),
    ("result_topic = ", "generated `result_topic` field, now derived from the runtime mode"),
    ("engineDaemons = ", "generated `engineDaemons` list, now derived from the engine members and the pool graph"),
    ("engines = ", "generated `engines` list, now derived from the models' selected engines"),
    -- The top-level `runtimeMode` is still on the wire and renders as
    -- `{ runtimeMode = `, so the retired per-entity copies are matched by their
    -- leading `, ` separator instead.
    (", runtimeMode = ", "per-entity `runtimeMode` field, now derived from the top-level runtime mode"),
    ("runtimeLane = <", "per-model `runtimeLane` field, now derived from the runtime mode and `requiresGpu`"),
    ("location = ", "per-daemon or per-member `location` field, now derived from the role and the runtime mode"),
    ("maxInflightPerMember = ", "per-pool `maxInflightPerMember` knob, which only ever held one supported value"),
    ("resource = <", "substrate-limit `resource` field, now derived from the runtime mode and which half of the budget the limit occupies"),
    ("source = <", "substrate-limit `source` field, now derived alongside its resource"),
    ("headroomMib = ", "host-partition `headroomMib` term, which only ever held the binary's own minimum")
  ]

decodeCompiledRuntimePlanFile :: FilePath -> IO (Either ConfigErrors CompiledRuntimePlan)
decodeCompiledRuntimePlanFile filePath =
  compileRuntimePlan <$> decodeRawRuntimeConfigFile filePath

resolveRuntimeModeFromSubstrateFile :: FilePath -> IO RuntimeMode
resolveRuntimeModeFromSubstrateFile filePath =
  configRuntimeMode <$> decodeSubstrateConfigFile filePath

renderSubstrateConfigSchema :: Either String Text
renderSubstrateConfigSchema =
  renderDecoderExpected (Dhall.auto @DhallDemoConfig)

data DhallDemoConfig = DhallDemoConfig
  { dhallConfigRuntimeMode :: DhallRuntimeMode,
    dhallConfigMapName :: Text,
    dhallGeneratedPath :: Text,
    dhallMountedPath :: Text,
    dhallDemoUi :: Bool,
    dhallDaemonRole :: DhallDaemonRole,
    dhallCoordinator :: DhallDaemonConfig,
    dhallWebapp :: DhallDaemonConfig,
    dhallEnginePools :: [DhallEnginePool],
    dhallEngineMembers :: [DhallEngineMember],
    dhallModelsBucket :: Text,
    dhallModelBootstrapTopic :: Text,
    dhallModels :: [DhallModelDescriptor],
    dhallInferenceMemoryBudget :: DhallInferenceMemoryBudget
  }
  deriving (Generic)

instance Dhall.FromDhall DhallDemoConfig where
  autoWith _ = Dhall.genericAutoWith dhallInterpretOptions

-- | Phase 8 Sprint 8.10: the engine daemons left the wire entirely and the two
-- in-cluster daemons kept only what is theirs to declare. Location and topics
-- are functions of the runtime mode and the pool graph, so they are derived
-- rather than mirrored.
data DhallDaemonConfig = DhallDaemonConfig
  { dhallRole :: DhallDaemonRole,
    dhallMemberId :: Maybe Text,
    dhallPulsarConnectionMode :: DhallPulsarConnectionMode
  }
  deriving (Generic)

instance Dhall.FromDhall DhallDaemonConfig where
  autoWith _ = Dhall.genericAutoWith dhallInterpretOptions

data DhallEnginePool = DhallEnginePool
  { dhallPoolId :: Text,
    dhallPoolModelIds :: [Text],
    dhallPoolMemberIds :: [Text],
    dhallPoolSubscriptionType :: DhallConsumerSubscription
  }
  deriving (Generic)

instance Dhall.FromDhall DhallEnginePool where
  autoWith _ = Dhall.genericAutoWith dhallInterpretOptions

data DhallEngineMember = DhallEngineMember
  { dhallMemberConfigId :: Text,
    dhallMemberPoolIds :: [Text]
  }
  deriving (Generic)

instance Dhall.FromDhall DhallEngineMember where
  autoWith _ = Dhall.genericAutoWith dhallInterpretOptions

data DhallModelDescriptor = DhallModelDescriptor
  { dhallMatrixRowId :: Text,
    dhallModelId :: Text,
    dhallDisplayName :: Text,
    dhallFamily :: Text,
    dhallDescription :: Text,
    dhallArtifactType :: Text,
    dhallReferenceModel :: Text,
    dhallDownloadUrl :: Text,
    dhallSelectedEngine :: Text,
    dhallRequestShape :: [DhallRequestField],
    dhallRequiresGpu :: Bool,
    dhallNotes :: Text,
    dhallModelRamFootprintMib :: Natural
  }
  deriving (Generic)

instance Dhall.FromDhall DhallModelDescriptor where
  autoWith _ = Dhall.genericAutoWith dhallInterpretOptions

-- | The generated execution-plan budget is a proper union. An arm carries only
-- its applicable fields, so the retired text discriminator plus zero-filled
-- fields cannot be represented.
data DhallInferenceMemoryBudget
  = HostEnforced DhallHostMemoryBudget
  | SubstrateEnforced DhallSubstrateMemoryBudget
  | DualEnforced DhallDualMemoryBudget
  deriving (Generic)

instance Dhall.FromDhall DhallInferenceMemoryBudget

-- | Phase 8 Sprint 8.10: the headroom term left the wire. Every partition this
-- binary has ever generated held back exactly 'minHostHeadroomMib', so the field
-- was a second copy of a constant the binary owns.
data DhallHostMemoryBudget = DhallHostMemoryBudget
  { dhallBudgetPhysicalMib :: Natural,
    dhallBudgetVmReserveMib :: Natural
  }
  deriving (Generic)

instance Dhall.FromDhall DhallHostMemoryBudget where
  autoWith _ = Dhall.genericAutoWith dhallInterpretOptions

-- | Phase 8 Sprint 8.10: a substrate limit carries only its quantity. Which
-- physical resource it bounds and which policy set it are decided by the runtime
-- mode and by which half of the budget the limit occupies, so a wire copy could
-- only ever disagree with the derivation.
newtype DhallSubstrateMemoryBudget = DhallSubstrateMemoryBudget
  { dhallBudgetLimitMib :: Natural
  }
  deriving (Generic)

instance Dhall.FromDhall DhallSubstrateMemoryBudget where
  autoWith _ = Dhall.genericAutoWith dhallInterpretOptions

-- | Phase 6 Sprint 6.44 — the @linux-gpu@ arm. It reuses the substrate limit
-- record for both halves, so the two limits are structurally identical and the
-- arm names which is which rather than encoding it in a discriminator field.
data DhallDualMemoryBudget = DhallDualMemoryBudget
  { dhallBudgetPodLimit :: DhallSubstrateMemoryBudget,
    dhallBudgetVramLimit :: DhallSubstrateMemoryBudget
  }
  deriving (Generic)

instance Dhall.FromDhall DhallDualMemoryBudget where
  autoWith _ = Dhall.genericAutoWith dhallInterpretOptions

data DhallRequestField = DhallRequestField
  { dhallName :: Text,
    dhallLabel :: Text,
    dhallFieldType :: DhallRequestFieldType
  }
  deriving (Generic)

instance Dhall.FromDhall DhallRequestField where
  autoWith _ = Dhall.genericAutoWith dhallInterpretOptions

-- | Phase 8 Sprint 8.9 — the generated wire's enum-like choices are Dhall
-- unions, not @Text@ refined after decode.
--
-- Each mirror below carries a type-specific Haskell constructor prefix, because
-- several of them name an alternative the domain type also names and Haskell
-- has one constructor namespace per module. 'dhallEnumInterpretOptions' strips
-- that prefix, so the /wire/ alternative is exactly the suffix. Alternatives are
-- identifier-shaped (@AppleSilicon@, not @apple-silicon@) because a Dhall
-- alternative is a label rather than a string — which is the whole point of
-- retiring the text tags. Refinement is a total case match: an unsupported
-- spelling is now a structural type error at decode rather than a
-- post-decode @parseEnum@ failure.
--
-- One consequence is deliberate and recorded rather than incidental:
-- 'parseDaemonRole' accepts three retired aliases (@frontend@, @cluster@,
-- @host@) that the renderer has never emitted. A union cannot express an alias,
-- so a stale @.dhall@ carrying one is now a decode failure. The retired-shape
-- classifier names it.
dhallEnumInterpretOptions :: Text -> Dhall.InterpretOptions
dhallEnumInterpretOptions constructorPrefix =
  Dhall.defaultInterpretOptions
    { Dhall.constructorModifier =
        \constructorName ->
          fromMaybe constructorName (Text.stripPrefix constructorPrefix constructorName)
    }

-- | The rendered spelling of an enum-only union. Both the value renderer and
-- every record-type annotation that contains the field select from one of these
-- values, so an annotation cannot drift from the value it annotates.
dhallEnumUnionType :: [String] -> String
dhallEnumUnionType alternatives =
  "< " <> intercalate " | " alternatives <> " >"

dhallEnumValue :: String -> String -> String
dhallEnumValue unionType alternative = unionType <> "." <> alternative

data DhallRuntimeMode
  = DhallRuntimeModeAppleSilicon
  | DhallRuntimeModeLinuxCpu
  | DhallRuntimeModeLinuxGpu
  deriving (Generic)

instance Dhall.FromDhall DhallRuntimeMode where
  autoWith _ = Dhall.genericAutoWith (dhallEnumInterpretOptions "DhallRuntimeMode")

runtimeModeFromDhall :: DhallRuntimeMode -> RuntimeMode
runtimeModeFromDhall rawRuntimeMode = case rawRuntimeMode of
  DhallRuntimeModeAppleSilicon -> AppleSilicon
  DhallRuntimeModeLinuxCpu -> LinuxCpu
  DhallRuntimeModeLinuxGpu -> LinuxGpu

runtimeModeAlternative :: RuntimeMode -> String
runtimeModeAlternative runtimeModeValue = case runtimeModeValue of
  AppleSilicon -> "AppleSilicon"
  LinuxCpu -> "LinuxCpu"
  LinuxGpu -> "LinuxGpu"

runtimeModeUnionType :: String
runtimeModeUnionType = dhallEnumUnionType (map runtimeModeAlternative allRuntimeModes)

renderRuntimeMode :: RuntimeMode -> String
renderRuntimeMode = dhallEnumValue runtimeModeUnionType . runtimeModeAlternative

data DhallDaemonRole
  = DhallDaemonRoleCoordinator
  | DhallDaemonRoleEngine
  | DhallDaemonRoleWebapp
  deriving (Generic)

instance Dhall.FromDhall DhallDaemonRole where
  autoWith _ = Dhall.genericAutoWith (dhallEnumInterpretOptions "DhallDaemonRole")

daemonRoleFromDhall :: DhallDaemonRole -> DaemonRole
daemonRoleFromDhall rawRole = case rawRole of
  DhallDaemonRoleCoordinator -> Coordinator
  DhallDaemonRoleEngine -> Engine
  DhallDaemonRoleWebapp -> Webapp

daemonRoleAlternative :: DaemonRole -> String
daemonRoleAlternative role = case role of
  Coordinator -> "Coordinator"
  Engine -> "Engine"
  Webapp -> "Webapp"

daemonRoleUnionType :: String
daemonRoleUnionType =
  dhallEnumUnionType (map daemonRoleAlternative [Coordinator, Engine, Webapp])

renderDaemonRole :: DaemonRole -> String
renderDaemonRole = dhallEnumValue daemonRoleUnionType . daemonRoleAlternative

data DhallConsumerSubscription
  = DhallConsumerSubscriptionShared
  | DhallConsumerSubscriptionExclusive
  | DhallConsumerSubscriptionFailover
  deriving (Generic)

instance Dhall.FromDhall DhallConsumerSubscription where
  autoWith _ =
    Dhall.genericAutoWith (dhallEnumInterpretOptions "DhallConsumerSubscription")

consumerSubscriptionFromDhall :: DhallConsumerSubscription -> ConsumerSubscriptionType
consumerSubscriptionFromDhall rawSubscription = case rawSubscription of
  DhallConsumerSubscriptionShared -> ConsumerShared
  DhallConsumerSubscriptionExclusive -> ConsumerExclusive
  DhallConsumerSubscriptionFailover -> ConsumerFailover

consumerSubscriptionAlternative :: ConsumerSubscriptionType -> String
consumerSubscriptionAlternative subscription = case subscription of
  ConsumerShared -> "Shared"
  ConsumerExclusive -> "Exclusive"
  ConsumerFailover -> "Failover"

consumerSubscriptionUnionType :: String
consumerSubscriptionUnionType =
  dhallEnumUnionType
    (map consumerSubscriptionAlternative [ConsumerShared, ConsumerExclusive, ConsumerFailover])

renderConsumerSubscription :: ConsumerSubscriptionType -> String
renderConsumerSubscription =
  dhallEnumValue consumerSubscriptionUnionType . consumerSubscriptionAlternative

data DhallPulsarConnectionMode
  = DhallPulsarConnectionModeConfiguredTransport
  | DhallPulsarConnectionModePublicationEdgeAutoDiscovery
  deriving (Generic)

instance Dhall.FromDhall DhallPulsarConnectionMode where
  autoWith _ =
    Dhall.genericAutoWith (dhallEnumInterpretOptions "DhallPulsarConnectionMode")

pulsarConnectionModeFromDhall :: DhallPulsarConnectionMode -> PulsarConnectionMode
pulsarConnectionModeFromDhall rawMode = case rawMode of
  DhallPulsarConnectionModeConfiguredTransport -> ConfiguredTransport
  DhallPulsarConnectionModePublicationEdgeAutoDiscovery -> PublicationEdgeAutoDiscovery

pulsarConnectionModeAlternative :: PulsarConnectionMode -> String
pulsarConnectionModeAlternative connectionMode = case connectionMode of
  ConfiguredTransport -> "ConfiguredTransport"
  PublicationEdgeAutoDiscovery -> "PublicationEdgeAutoDiscovery"

pulsarConnectionModeUnionType :: String
pulsarConnectionModeUnionType =
  dhallEnumUnionType
    ( map
        pulsarConnectionModeAlternative
        [ConfiguredTransport, PublicationEdgeAutoDiscovery]
    )

renderPulsarConnectionMode :: PulsarConnectionMode -> String
renderPulsarConnectionMode =
  dhallEnumValue pulsarConnectionModeUnionType . pulsarConnectionModeAlternative

-- | The one mirror that cannot use the generic derivation.
--
-- @genericAutoWith@ dispatches on the datatype's GHC-Generics shape, and a
-- single-constructor type has no @:+:@ at all, so it derives as a /record/ —
-- here the empty record @{}@ — rather than as a one-alternative union. Building
-- the union decoder explicitly keeps the wire shape @< TextField >@, so adding
-- a second request-field type later is a wire addition rather than a wire
-- rewrite. The round-trip through the real decode boundary is what catches this;
-- the annotation and the decoder are otherwise unrelated.
data DhallRequestFieldType
  = DhallRequestFieldTypeTextField

instance Dhall.FromDhall DhallRequestFieldType where
  autoWith _ =
    Dhall.union (DhallRequestFieldTypeTextField <$ Dhall.constructor "TextField" Dhall.unit)

requestFieldTypeFromDhall :: DhallRequestFieldType -> RequestFieldType
requestFieldTypeFromDhall rawFieldType = case rawFieldType of
  DhallRequestFieldTypeTextField -> TextRequestField

requestFieldTypeAlternative :: RequestFieldType -> String
requestFieldTypeAlternative fieldTypeValue = case fieldTypeValue of
  TextRequestField -> "TextField"

requestFieldTypeUnionType :: String
requestFieldTypeUnionType =
  dhallEnumUnionType [requestFieldTypeAlternative TextRequestField]

renderRequestFieldType :: RequestFieldType -> String
renderRequestFieldType =
  dhallEnumValue requestFieldTypeUnionType . requestFieldTypeAlternative

-- | Convert a wire 'Natural' into the platform 'Int' the domain types use.
--
-- Phase 8 Sprint 8.9 moved every generated quantity from Dhall @Integer@ to
-- @Natural@, so a negative quantity is no longer representable in the wire
-- language at all rather than being rejected after decode. What @Natural@ does
-- not bound is the top: fail closed on a value the platform integer cannot hold
-- instead of wrapping it into a small positive one.
naturalToInt :: String -> Natural -> Either String Int
naturalToInt fieldPath value
  | toInteger value > toInteger (maxBound :: Int) =
      Left (fieldPath <> " exceeds the supported integer range: " <> show value)
  | otherwise = Right (fromIntegral value)

dhallInterpretOptions :: Dhall.InterpretOptions
dhallInterpretOptions =
  Dhall.defaultInterpretOptions {Dhall.fieldModifier = dhallFieldName}

dhallFieldName :: Text -> Text
-- Phase 8 Sprint 8.9 removed the @legacyDhall@ prefix branch: the pre-union
-- decoder it served is gone and no field carried that prefix any more, so the
-- branch was dead compatibility residue rather than a supported spelling.
dhallFieldName rawFieldName =
  maybe rawFieldName dhallFieldSuffixName (Text.stripPrefix "dhall" rawFieldName)

dhallFieldSuffixName :: Text -> Text
dhallFieldSuffixName suffix =
  case suffix of
    "ConfigRuntimeMode" -> "runtimeMode"
    "DemoUi" -> "demo_ui"
    "MemberId" -> "memberId"
    "ModelsBucket" -> "models_bucket"
    "ModelBootstrapTopic" -> "model_bootstrap_topic"
    "InferenceMemoryBudget" -> "inferenceMemoryBudget"
    "BudgetPhysicalMib" -> "physicalMib"
    "BudgetVmReserveMib" -> "vmReserveMib"
    "BudgetLimitMib" -> "limitMib"
    "BudgetPodLimit" -> "podLimit"
    "BudgetVramLimit" -> "vramLimit"
    "EnginePools" -> "enginePools"
    "EngineMembers" -> "engineMembers"
    "PoolId" -> "id"
    "PoolModelIds" -> "models"
    "PoolMemberIds" -> "members"
    "PoolSubscriptionType" -> "subscription"
    "MemberConfigId" -> "id"
    "MemberPoolIds" -> "pools"
    other -> lowerInitial other

lowerInitial :: Text -> Text
lowerInitial value =
  case Text.uncons value of
    Nothing -> value
    Just (firstCharacter, rest) -> Text.cons (toLower firstCharacter) rest

-- | Rebuild the domain configuration from the reduced wire.
--
-- Phase 8 Sprint 8.10: every field this reconstructs was previously carried on
-- the wire as a second copy of a fact the binary already derives. Dhall record
-- types are not dependent — a field's type can never mention a sibling's value —
-- so any pair of fields that must agree is a permanent illegal-state generator.
-- Deriving them here is the only shape with no disagreement left to detect,
-- which is why the equality checks that existed to catch such a disagreement are
-- retired with the fields rather than before them.
demoConfigFromDhall :: DhallDemoConfig -> Either String DemoConfig
demoConfigFromDhall rawConfig = do
  let runtimeModeValue = runtimeModeFromDhall (dhallConfigRuntimeMode rawConfig)
      activeDaemonRoleValue = daemonRoleFromDhall (dhallDaemonRole rawConfig)
      derivedRequestTopics = requestTopicsForMode runtimeModeValue
      derivedResultTopic = resultTopicForMode runtimeModeValue
  coordinatorDaemonValue <-
    withDefaultConsumerSubscriptionType runtimeModeValue
      <$> clusterDaemonConfigFromDhall derivedRequestTopics derivedResultTopic (dhallCoordinator rawConfig)
  webappDaemonValue <-
    withDefaultConsumerSubscriptionType runtimeModeValue
      <$> clusterDaemonConfigFromDhall derivedRequestTopics derivedResultTopic (dhallWebapp rawConfig)
  enginePoolValues <- traverse (enginePoolFromDhall runtimeModeValue) (dhallEnginePools rawConfig)
  engineMemberValues <- traverse (engineMemberFromDhall runtimeModeValue) (dhallEngineMembers rawConfig)
  modelValues <- traverse (modelDescriptorFromDhall runtimeModeValue) (dhallModels rawConfig)
  memoryBudgetValue <-
    inferenceMemoryBudgetFromDhall runtimeModeValue (dhallInferenceMemoryBudget rawConfig)
  let engineDaemonValues =
        deriveEngineDaemonConfigs runtimeModeValue enginePoolValues engineMemberValues derivedResultTopic
      engineValues = deriveEngineBindings runtimeModeValue modelValues
  pure
    DemoConfig
      { configRuntimeMode = runtimeModeValue,
        configMapName = dhallConfigMapName rawConfig,
        generatedPath = Text.unpack (dhallGeneratedPath rawConfig),
        mountedPath = Text.unpack (dhallMountedPath rawConfig),
        demoUiEnabled = dhallDemoUi rawConfig,
        activeDaemonRole = activeDaemonRoleValue,
        coordinatorDaemon = coordinatorDaemonValue,
        webappDaemon = webappDaemonValue,
        engineDaemons = engineDaemonValues,
        enginePools = enginePoolValues,
        engineMembers = engineMemberValues,
        requestTopics = derivedRequestTopics,
        resultTopic = derivedResultTopic,
        modelsBucket = dhallModelsBucket rawConfig,
        modelBootstrapTopic = dhallModelBootstrapTopic rawConfig,
        engines = engineValues,
        models = modelValues,
        inferenceMemoryBudget = memoryBudgetValue
      }

-- | The engine bindings a model set implies. A selected engine with no canonical
-- binding produces no entry, so the compiler still reports it as
-- @UnknownSelectedEngine@ against the model that named it — which is the only
-- fact a generated engine list could ever have added.
deriveEngineBindings :: RuntimeMode -> [ModelDescriptor] -> [EngineBinding]
deriveEngineBindings runtimeModeValue modelValues =
  nubOn
    engineBindingName
    [ binding
    | model <- modelValues,
      Just binding <-
        [canonicalEngineBindingForSelectedEngine runtimeModeValue (selectedEngine model)]
    ]

nubOn :: (Eq key) => (value -> key) -> [value] -> [value]
nubOn keyOf = go []
  where
    go _ [] = []
    go seen (value : rest)
      | keyOf value `elem` seen = go seen rest
      | otherwise = value : go (keyOf value : seen) rest

inferenceMemoryBudgetFromDhall ::
  RuntimeMode ->
  DhallInferenceMemoryBudget ->
  Either String InferenceMemoryBudget
inferenceMemoryBudgetFromDhall runtimeModeValue rawBudget =
  case rawBudget of
    HostEnforced hostBudget -> do
      physicalMib <-
        naturalToInt "inferenceMemoryBudget.physicalMib" (dhallBudgetPhysicalMib hostBudget)
      vmReserveMib <-
        naturalToInt "inferenceMemoryBudget.vmReserveMib" (dhallBudgetVmReserveMib hostBudget)
      HostEnforcedBudget <$> mkHostMemoryPartition physicalMib vmReserveMib minHostHeadroomMib
    SubstrateEnforced substrateBudget ->
      SubstrateEnforcedBudget
        <$> podMemoryLimitFromDhall
          "inferenceMemoryBudget"
          PodRam
          (residentLimitSourceForMode runtimeModeValue)
          substrateBudget
    DualEnforced dualBudget ->
      DualEnforcedBudget
        <$> podMemoryLimitFromDhall
          "inferenceMemoryBudget.podLimit"
          PodRam
          (residentLimitSourceForMode runtimeModeValue)
          (dhallBudgetPodLimit dualBudget)
        <*> podMemoryLimitFromDhall
          "inferenceMemoryBudget.vramLimit"
          GpuVram
          LinuxGpuVramBudget
          (dhallBudgetVramLimit dualBudget)

-- | Which policy set a resident-memory limit. Only the cluster engine pod limit
-- has ever named one; the VRAM half names its own source at its own call site.
residentLimitSourceForMode :: RuntimeMode -> PodMemoryLimitSource
residentLimitSourceForMode _ = ClusterEnginePodMemoryLimit

podMemoryLimitFromDhall ::
  String ->
  InferenceMemoryResource ->
  PodMemoryLimitSource ->
  DhallSubstrateMemoryBudget ->
  Either String PodMemoryLimit
podMemoryLimitFromDhall fieldPath resourceValue sourceValue substrateBudget = do
  limitMib <- naturalToInt (fieldPath <> ".limitMib") (dhallBudgetLimitMib substrateBudget)
  -- @Natural@ already excludes a negative limit on the wire; zero is still
  -- representable, so the positivity check stays.
  if limitMib <= 0
    then Left (fieldPath <> ".limitMib must be positive")
    else
      pure
        PodMemoryLimit
          { podMemoryLimitResource = resourceValue,
            podMemoryLimitSource = sourceValue,
            podMemoryLimitMib = limitMib
          }

deriveEngineDaemonConfigs :: RuntimeMode -> [EnginePool] -> [EngineMember] -> Text -> [DaemonConfig]
deriveEngineDaemonConfigs runtimeMode pools members resultTopicValue =
  map engineDaemonConfigForMember members
  where
    engineDaemonConfigForMember member =
      DaemonConfig
        { daemonConfigRole = Engine,
          daemonConfigLocation = engineMemberLocation member,
          daemonConfigMemberId = Just (engineMemberId member),
          daemonConfigRequestTopics = derivedEngineMemberRequestTopics runtimeMode pools member,
          daemonConfigResultTopic = resultTopicValue,
          daemonConfigPulsarConnectionMode =
            if runtimeMode == AppleSilicon
              then PublicationEdgeAutoDiscovery
              else ConfiguredTransport,
          daemonConfigConsumerSubscriptionType = Just ConsumerShared
        }

derivedEngineMemberRequestTopics :: RuntimeMode -> [EnginePool] -> EngineMember -> [Text]
derivedEngineMemberRequestTopics runtimeMode pools member =
  [ derivedEnginePoolTopicForMode runtimeMode (enginePoolId pool) modelIdValue
  | pool <- pools,
    enginePoolId pool `elem` engineMemberPoolIds member,
    engineMemberId member `elem` enginePoolMemberIds pool,
    modelIdValue <- enginePoolModelIds pool
  ]

derivedEnginePoolTopicForMode :: RuntimeMode -> Text -> Text -> Text
derivedEnginePoolTopicForMode runtimeMode poolId modelIdValue =
  "persistent://infernix/demo/inference.batch."
    <> runtimeModeId runtimeMode
    <> ".pool."
    <> topicSegment poolId
    <> ".model."
    <> topicSegment modelIdValue

topicSegment :: Text -> Text
topicSegment =
  Text.map replaceInvalid
  where
    replaceInvalid character
      | isAlphaNum character || character == '-' || character == '_' || character == '.' = character
      | otherwise = '-'

-- | The two in-cluster daemons. Both run in a pod on every supported substrate
-- and both consume the coordinator request topic and publish the shared result
-- topic, so location and topics are derived rather than declared.
clusterDaemonConfigFromDhall ::
  [Text] ->
  Text ->
  DhallDaemonConfig ->
  Either String DaemonConfig
clusterDaemonConfigFromDhall derivedRequestTopics derivedResultTopic rawConfig = do
  let roleValue = daemonRoleFromDhall (dhallRole rawConfig)
      connectionModeValue =
        pulsarConnectionModeFromDhall (dhallPulsarConnectionMode rawConfig)
  pure
    DaemonConfig
      { daemonConfigRole = roleValue,
        daemonConfigLocation = clusterDaemonLocation,
        daemonConfigMemberId = dhallMemberId rawConfig,
        daemonConfigRequestTopics = derivedRequestTopics,
        daemonConfigResultTopic = derivedResultTopic,
        daemonConfigPulsarConnectionMode = connectionModeValue,
        daemonConfigConsumerSubscriptionType = Nothing
      }

enginePoolFromDhall :: RuntimeMode -> DhallEnginePool -> Either String EnginePool
enginePoolFromDhall runtimeModeValue rawPool =
  pure
    EnginePool
      { enginePoolId = dhallPoolId rawPool,
        enginePoolRuntimeMode = runtimeModeValue,
        enginePoolModelIds = dhallPoolModelIds rawPool,
        enginePoolMemberIds = dhallPoolMemberIds rawPool,
        enginePoolSubscriptionType =
          consumerSubscriptionFromDhall (dhallPoolSubscriptionType rawPool),
        enginePoolMaxInflightPerMember = defaultMaxInflightPerMember
      }

engineMemberFromDhall :: RuntimeMode -> DhallEngineMember -> Either String EngineMember
engineMemberFromDhall runtimeModeValue rawMember =
  pure
    EngineMember
      { engineMemberId = dhallMemberConfigId rawMember,
        engineMemberRuntimeMode = runtimeModeValue,
        engineMemberLocation = engineMemberLocationForMode runtimeModeValue,
        engineMemberPoolIds = dhallMemberPoolIds rawMember
      }

withDefaultConsumerSubscriptionType :: RuntimeMode -> DaemonConfig -> DaemonConfig
withDefaultConsumerSubscriptionType runtimeMode daemonConfig =
  daemonConfig
    { daemonConfigConsumerSubscriptionType =
        case daemonConfigConsumerSubscriptionType daemonConfig of
          Just subscriptionType -> Just subscriptionType
          Nothing -> Just (defaultConsumerSubscriptionType runtimeMode daemonConfig)
    }

defaultConsumerSubscriptionType :: RuntimeMode -> DaemonConfig -> ConsumerSubscriptionType
defaultConsumerSubscriptionType runtimeMode daemonConfig
  | runtimeMode == AppleSilicon
      && daemonConfigRole daemonConfig == Engine
      && daemonConfigLocation daemonConfig == "control-plane-host" =
      ConsumerShared
  | otherwise = ConsumerShared

modelDescriptorFromDhall :: RuntimeMode -> DhallModelDescriptor -> Either String ModelDescriptor
modelDescriptorFromDhall runtimeModeValue rawModel = do
  let runtimeLaneValue = runtimeLaneForMode runtimeModeValue (dhallRequiresGpu rawModel)
  requestShapeValue <- traverse requestFieldFromDhall (dhallRequestShape rawModel)
  -- Phase 4 Sprint 4.31: the footprint is required and positive; a model whose
  -- Dhall row carries an absent/zero footprint fails the decode closed.
  footprintMib <-
    naturalToInt
      ("models." <> Text.unpack (dhallModelId rawModel) <> ".modelRamFootprintMib")
      (dhallModelRamFootprintMib rawModel)
  footprintValue <- mkModelMemoryFootprint footprintMib
  pure
    ModelDescriptor
      { matrixRowId = dhallMatrixRowId rawModel,
        modelId = dhallModelId rawModel,
        displayName = dhallDisplayName rawModel,
        family = dhallFamily rawModel,
        description = dhallDescription rawModel,
        artifactType = dhallArtifactType rawModel,
        referenceModel = dhallReferenceModel rawModel,
        downloadUrl = dhallDownloadUrl rawModel,
        selectedEngine = dhallSelectedEngine rawModel,
        requestShape = requestShapeValue,
        runtimeMode = runtimeModeValue,
        runtimeLane = runtimeLaneValue,
        requiresGpu = dhallRequiresGpu rawModel,
        notes = dhallNotes rawModel,
        modelRamFootprint = footprintValue
      }

requestFieldFromDhall :: DhallRequestField -> Either String RequestField
requestFieldFromDhall rawField =
  pure
    RequestField
      { name = dhallName rawField,
        label = dhallLabel rawField,
        fieldType = requestFieldTypeFromDhall (dhallFieldType rawField)
      }

renderSubstrateConfig :: DemoConfig -> String
renderSubstrateConfig demoConfig =
  unlines
    [ "{ runtimeMode = " <> renderRuntimeMode (configRuntimeMode demoConfig),
      ", configMapName = " <> dhallText (configMapName demoConfig),
      ", generatedPath = " <> dhallFilePath (generatedPath demoConfig),
      ", mountedPath = " <> dhallFilePath (mountedPath demoConfig),
      ", demo_ui = " <> dhallBool (demoUiEnabled demoConfig),
      ", daemonRole = " <> renderDaemonRole (activeDaemonRole demoConfig),
      ", coordinator = " <> renderDaemonConfig (coordinatorDaemon demoConfig),
      ", webapp = " <> renderDaemonConfig (webappDaemon demoConfig),
      ", enginePools = " <> dhallList enginePoolType renderEnginePool (enginePools demoConfig),
      ", engineMembers = " <> dhallList engineMemberType renderEngineMember (engineMembers demoConfig),
      ", models_bucket = " <> dhallText (modelsBucket demoConfig),
      ", model_bootstrap_topic = " <> dhallText (modelBootstrapTopic demoConfig),
      ", models = " <> dhallList modelDescriptorType renderModelDescriptor (models demoConfig),
      ", inferenceMemoryBudget = " <> renderInferenceMemoryBudget (inferenceMemoryBudget demoConfig),
      "}"
    ]

-- | The single rendered spelling of the generated budget union. Every renderer
-- arm selects from this one value, so a new arm cannot be added to the Haskell
-- ADT and its decoder while some renderer keeps emitting a stale union type.
inferenceMemoryBudgetUnionType :: String
inferenceMemoryBudgetUnionType =
  "< HostEnforced : { physicalMib : Natural, vmReserveMib : Natural }"
    <> " | SubstrateEnforced : "
    <> substrateMemoryBudgetRecordType
    <> " | DualEnforced : { podLimit : "
    <> substrateMemoryBudgetRecordType
    <> ", vramLimit : "
    <> substrateMemoryBudgetRecordType
    <> " } >"

substrateMemoryBudgetRecordType :: String
substrateMemoryBudgetRecordType = "{ limitMib : Natural }"

renderInferenceMemoryBudget :: InferenceMemoryBudget -> String
renderInferenceMemoryBudget budget =
  case budget of
    HostEnforcedBudget partition ->
      inferenceMemoryBudgetUnionType
        <> ".HostEnforced "
        <> "{ physicalMib = "
        <> dhallNatural (hostPartitionPhysicalMib partition)
        <> ", vmReserveMib = "
        <> dhallNatural (hostPartitionVmReserveMib partition)
        <> " }"
    SubstrateEnforcedBudget podLimit ->
      inferenceMemoryBudgetUnionType
        <> ".SubstrateEnforced "
        <> renderPodMemoryLimit podLimit
    DualEnforcedBudget podLimit vramLimit ->
      inferenceMemoryBudgetUnionType
        <> ".DualEnforced "
        <> "{ podLimit = "
        <> renderPodMemoryLimit podLimit
        <> ", vramLimit = "
        <> renderPodMemoryLimit vramLimit
        <> " }"

renderPodMemoryLimit :: PodMemoryLimit -> String
renderPodMemoryLimit podLimit =
  "{ limitMib = "
    <> dhallNatural (podMemoryLimitMib podLimit)
    <> " }"

renderDaemonConfig :: DaemonConfig -> String
renderDaemonConfig daemonConfig =
  "{ role = "
    <> renderDaemonRole (daemonConfigRole daemonConfig)
    <> ", memberId = "
    <> dhallOptional "Text" dhallText (daemonConfigMemberId daemonConfig)
    <> ", pulsarConnectionMode = "
    <> renderPulsarConnectionMode (daemonConfigPulsarConnectionMode daemonConfig)
    <> " }"

renderEnginePool :: EnginePool -> String
renderEnginePool pool =
  "{ id = "
    <> dhallText (enginePoolId pool)
    <> ", models = "
    <> dhallList "Text" dhallText (enginePoolModelIds pool)
    <> ", members = "
    <> dhallList "Text" dhallText (enginePoolMemberIds pool)
    <> ", subscription = "
    <> renderConsumerSubscription (enginePoolSubscriptionType pool)
    <> " }"

renderEngineMember :: EngineMember -> String
renderEngineMember member =
  "{ id = "
    <> dhallText (engineMemberId member)
    <> ", pools = "
    <> dhallList "Text" dhallText (engineMemberPoolIds member)
    <> " }"

renderModelDescriptor :: ModelDescriptor -> String
renderModelDescriptor model =
  "{ matrixRowId = "
    <> dhallText (matrixRowId model)
    <> ", modelId = "
    <> dhallText (modelId model)
    <> ", displayName = "
    <> dhallText (displayName model)
    <> ", family = "
    <> dhallText (family model)
    <> ", description = "
    <> dhallText (description model)
    <> ", artifactType = "
    <> dhallText (artifactType model)
    <> ", referenceModel = "
    <> dhallText (referenceModel model)
    <> ", downloadUrl = "
    <> dhallText (downloadUrl model)
    <> ", selectedEngine = "
    <> dhallText (selectedEngine model)
    <> ", requestShape = "
    <> dhallList requestFieldType renderRequestField (requestShape model)
    <> ", requiresGpu = "
    <> dhallBool (requiresGpu model)
    <> ", notes = "
    <> dhallText (notes model)
    <> ", modelRamFootprintMib = "
    <> dhallNatural (modelMemoryFootprintMib (modelRamFootprint model))
    <> " }"

renderRequestField :: RequestField -> String
renderRequestField requestField =
  "{ name = "
    <> dhallText (name requestField)
    <> ", label = "
    <> dhallText (label requestField)
    <> ", fieldType = "
    <> renderRequestFieldType (fieldType requestField)
    <> " }"

dhallList :: String -> (a -> String) -> [a] -> String
dhallList itemType renderItem values =
  case values of
    [] -> "([] : List " <> itemType <> ")"
    _ -> "[ " <> intercalate ", " (map renderItem values) <> " ]"

dhallOptional :: String -> (a -> String) -> Maybe a -> String
dhallOptional itemType renderItem value =
  case value of
    Nothing -> "None " <> itemType
    Just item -> "Some " <> renderItem item

dhallBool :: Bool -> String
dhallBool value
  | value = "True"
  | otherwise = "False"

-- | Render a generated quantity as a Dhall @Natural@ literal.
--
-- Every call site renders a value whose non-negativity was already established
-- by a checked constructor or a compiler check: 'mkHostMemoryPartition' rejects
-- a non-positive physical size and negative reserve/headroom,
-- 'mkModelMemoryFootprint' requires a positive footprint, @InvalidPoolMaxInflight@
-- rejects a non-positive inflight bound, and 'podMemoryLimitFromDhall' plus
-- config validation require a positive limit. A negative value would render as
-- an @Integer@ literal and fail the very next decode rather than round-tripping
-- silently.
dhallNatural :: Int -> String
dhallNatural = show

dhallFilePath :: FilePath -> String
dhallFilePath = dhallText . Text.pack

dhallText :: Text -> String
dhallText value =
  Text.unpack ("\"" <> DhallCore.escapeText value <> "\"")

enginePoolType :: String
enginePoolType =
  "{ id : Text, models : List Text, members : List Text, subscription : "
    <> consumerSubscriptionUnionType
    <> " }"

engineMemberType :: String
engineMemberType =
  "{ id : Text, pools : List Text }"

requestFieldType :: String
requestFieldType =
  "{ name : Text, label : Text, fieldType : "
    <> requestFieldTypeUnionType
    <> " }"

modelDescriptorType :: String
modelDescriptorType =
  "{ matrixRowId : Text, modelId : Text, displayName : Text, family : Text, description : Text, artifactType : Text, referenceModel : Text, downloadUrl : Text, selectedEngine : Text, requestShape : List "
    <> requestFieldType
    <> ", requiresGpu : Bool, notes : Text, modelRamFootprintMib : Natural }"
