{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TypeApplications #-}

module Infernix.Substrate.Internal
  ( decodeSubstrateConfigFile,
    decodeCompiledRuntimePlanFile,
    decodeRawRuntimeConfigFile,
    demoConfigGeneratedBanner,
    demoConfigGeneratedBannerLine,
    encodeSubstrateConfig,
    renderSubstrateConfigSchema,
    renderSubstrateConfig,
    resolveRuntimeModeFromSubstrateFile,
  )
where

import Control.Exception (SomeException, displayException, try)
import Data.ByteString.Lazy qualified as Lazy
import Data.Char (toLower)
import Data.List (intercalate)
import Data.Text (Text)
import Data.Text qualified as Text
import Data.Text.Encoding qualified as TextEncoding
import Data.Text.IO qualified as TextIO
import Dhall qualified
import Dhall.Core qualified as DhallCore
import GHC.Generics (Generic)
import Infernix.DhallSchema.Enums (dhallEnumInterpretOptions, dhallEnumUnionType, dhallEnumValue)
import Infernix.DhallSchema.Reflection (renderDecoderExpected)
import Infernix.ExecutionPlan (CompiledRuntimePlan, ConfigErrors, compileRuntimePlan)
import Infernix.ExecutionPlan.Internal (RawRuntimeConfig (..))
import Infernix.Types
import Numeric.Natural (Natural)

demoConfigGeneratedBannerLine :: String
demoConfigGeneratedBannerLine = "{- Auto-generated by infernix substrate materialization -}"

demoConfigGeneratedBanner :: String
demoConfigGeneratedBanner = demoConfigGeneratedBannerLine <> "\n"

encodeSubstrateConfig :: DemoConfig -> Lazy.ByteString
encodeSubstrateConfig demoConfig =
  Lazy.fromStrict
    ( TextEncoding.encodeUtf8
        (Text.pack (demoConfigGeneratedBanner <> renderSubstrateConfig demoConfig))
    )

decodeSubstrateConfigFile :: FilePath -> IO DemoConfig
decodeSubstrateConfigFile filePath = do
  RawRuntimeConfig config <- decodeRawRuntimeConfigFile filePath
  pure config

-- | Decode the generated Dhall into the opaque untrusted input accepted by the
-- execution-plan compiler.  New routing and launch consumers use this boundary
-- and cannot inspect the raw record.
decodeRawRuntimeConfigFile :: FilePath -> IO RawRuntimeConfig
decodeRawRuntimeConfigFile filePath = do
  decodedValue <- try (Dhall.inputFile Dhall.auto filePath :: IO DhallDemoConfig)
  case decodedValue of
    Left err -> do
      -- Phase 8 Sprint 8.9: a payload written by a pre-union generator fails
      -- the schema with a raw structural Dhall type error that says nothing
      -- about what to do. Name the retired shape and the command that replaces
      -- it before falling back to the generic diagnostic.
      legacyShape <- classifyRetiredSubstrateShape filePath
      ioError
        ( userError
            ( "invalid generated substrate Dhall: "
                <> maybe "" (<> "\n") legacyShape
                <> displayException (err :: SomeException)
            )
        )
    Right rawConfig ->
      case demoConfigFromDhall rawConfig of
        Left message -> ioError (userError ("invalid generated substrate Dhall: " <> message))
        Right demoConfig -> pure (RawRuntimeConfig demoConfig)

-- | Phase 8 Sprint 8.9 — recognise the retired flat, text-discriminated
-- execution-plan payloads and name them. Every generated @.dhall@ is produced
-- by this binary and is never version-controlled, so a payload carrying one of
-- these retired shapes is always a stale file left by an older binary, and the
-- fix is always to regenerate it. The check reads the file as text and looks
-- only for retired *field* spellings, so it cannot misfire on a current
-- payload: the union arms carry no @kind@ discriminator and no flat
-- @podLimitMib@ / @inferenceRamBudgetMib@ scalar, the enum fields are matched
-- together with the opening quote a union value never has, and @edgePort@ is no
-- longer emitted at all.
classifyRetiredSubstrateShape :: FilePath -> IO (Maybe String)
classifyRetiredSubstrateShape filePath = do
  contents <- try (TextIO.readFile filePath)
  pure $
    case contents of
      Left (_ :: SomeException) -> Nothing
      Right payload ->
        case [description | (marker, description) <- retiredSubstrateMarkers, marker `Text.isInfixOf` payload] of
          [] -> Nothing
          description : _ ->
            Just
              ( "this file carries the retired "
                  <> description
                  <> ". Every enum-like choice in the generated execution-plan"
                  <> " language is a Dhall union rather than a Text tag, and every"
                  <> " field the binary can derive has left the wire. No `.dhall` is"
                  <> " version-controlled: delete it and re-run `infernix init`"
                  <> " (or `infernix test init` for the harness input) to regenerate"
                  <> " it with the current binary."
              )

retiredSubstrateMarkers :: [(Text, String)]
retiredSubstrateMarkers =
  [ ("inferenceRamBudgetMib", "flat `inferenceRamBudgetMib` scalar budget"),
    ("kind =", "text-discriminated `kind =` inference-memory-budget record"),
    ("podLimitMib", "flat `podLimitMib` inference-memory-budget field"),
    -- Phase 8 Sprint 8.9 retired the remaining text-tagged enums. Match the
    -- retired spellings with their surrounding `field = "` so a current payload
    -- — which now writes `runtimeMode = < … >.LinuxCpu` — cannot match, and so
    -- a stale file reports the migration instead of a bare Dhall type error.
    -- `daemonRole` is listed first among these because it is the one field whose
    -- retired aliases (`frontend`, `cluster`, `host`) a union cannot express at
    -- all, so its stale payloads have no other diagnosis.
    ("daemonRole = \"", "text-tagged `daemonRole` field"),
    ("runtimeMode = \"", "text-tagged `runtimeMode` field"),
    ("runtimeLane = \"", "text-tagged `runtimeLane` field"),
    ("subscription = \"", "text-tagged engine-pool `subscription` field"),
    ("pulsarConnectionMode = \"", "text-tagged `pulsarConnectionMode` field"),
    ("adapterType = \"", "text-tagged engine-binding `adapterType` field"),
    ("fieldType = \"", "text-tagged request-shape `fieldType` field"),
    ("edgePort = ", "generated `edgePort` field, which no consumer ever read"),
    -- Phase 8 Sprint 8.10 deleted every field that was a second copy of a fact
    -- the binary derives. Each one gets its own marker so a stale file names the
    -- field it still carries rather than reporting a bare Dhall type error at
    -- whichever record the decoder happened to reach first. The markers match
    -- the retired spelling together with its `= ` so a field name that merely
    -- appears inside a topic string cannot match.
    ("request_topics = ", "generated `request_topics` field, now derived from the runtime mode"),
    ("result_topic = ", "generated `result_topic` field, now derived from the runtime mode"),
    ("engineDaemons = ", "generated `engineDaemons` list, now derived from the engine members and the pool graph"),
    ("engines = ", "generated `engines` list, now derived from the models' selected engines"),
    -- The top-level `runtimeMode` is still on the wire and renders as
    -- `{ runtimeMode = `, so the retired per-entity copies are matched by their
    -- leading `, ` separator instead.
    (", runtimeMode = ", "per-entity `runtimeMode` field, now derived from the top-level runtime mode"),
    ("runtimeLane = <", "per-model `runtimeLane` field, now derived from the runtime mode and `requiresGpu`"),
    ("location = ", "per-daemon or per-member `location` field, now derived from the role and the runtime mode"),
    ("maxInflightPerMember = ", "per-pool `maxInflightPerMember` knob, which only ever held one supported value"),
    ("resource = <", "substrate-limit `resource` field, now derived from the runtime mode and which half of the budget the limit occupies"),
    ("source = <", "substrate-limit `source` field, now derived alongside its resource"),
    ("headroomMib = ", "host-partition `headroomMib` term, which only ever held the binary's own minimum"),
    -- Phase 8 Sprint 8.11 split the wire into a system contract and a machine
    -- contract. The role moved to the machine contract, the two in-cluster
    -- daemon records became fully derivable, and the model catalog moved inside
    -- the pool that owns it, taking the member list with it.
    ("daemonRole = <", "generated `daemonRole` field, which now lives in the machine contract's `machine` block"),
    ("coordinator = ", "generated `coordinator` record, now derived from the runtime mode"),
    ("webapp = ", "generated `webapp` record, now derived from the runtime mode"),
    ("engineMembers = ", "generated `engineMembers` list, now inverted out of the pool graph"),
    -- Phase 4 Sprint 4.38 replaced the per-model `requiresGpu : Bool` plus
    -- `modelRamFootprintMib : Natural` pair with one closed requirement union.
    -- Both markers carry their `= ` so a field name appearing inside a note or
    -- a URL cannot match, and neither spelling occurs in a current payload:
    -- device usage is now the requirement's own arm.
    ("requiresGpu = ", "per-model `requiresGpu` field, now derived from the requirement's own arm"),
    ("modelRamFootprintMib = ", "per-model `modelRamFootprintMib` field, replaced by the derived requirement and the declared execution shape"),
    -- Phase 4 Sprint 4.39 took the requirement's quantities off the wire too:
    -- they are derived from the artifact's own bytes on the machine that will
    -- execute, and what remains declared is the shape they are evaluated
    -- against.
    ("requirement = <", "per-model `requirement` union, whose quantities are now derived from the model's own artifact")
  ]

-- The retired top-level `models` list has no marker of its own on purpose: a
-- pool now renders its own `models = [ { matrixRowId …` list, so every text a
-- top-level list could be recognised by is text a current payload also
-- contains. A marker that matches a valid payload is worse than no marker,
-- because it would report a migration for a file that needs none. The retired
-- shape still fails the decode; it just fails with the structural diagnostic.

decodeCompiledRuntimePlanFile :: FilePath -> IO (Either ConfigErrors CompiledRuntimePlan)
decodeCompiledRuntimePlanFile filePath =
  compileRuntimePlan <$> decodeRawRuntimeConfigFile filePath

resolveRuntimeModeFromSubstrateFile :: FilePath -> IO RuntimeMode
resolveRuntimeModeFromSubstrateFile filePath =
  configRuntimeMode <$> decodeSubstrateConfigFile filePath

renderSubstrateConfigSchema :: Either String Text
renderSubstrateConfigSchema =
  renderDecoderExpected (Dhall.auto @DhallDemoConfig)

-- | Phase 8 Sprint 8.11 — the system contract: what the platform runs, held
-- identically by every machine.
--
-- Three families of field left the wire with this sprint, each because it was a
-- second copy of something another part of the pair already decides:
--
-- * @daemonRole@ moved to the machine contract, where a box's default role
--   belongs. The @--role@ flag still selects a role per process for the split
--   Deployments.
-- * @coordinator@ and @webapp@ were fully derivable from the runtime mode —
--   both run in a cluster pod, both use the configured transport, and neither
--   ever carried a member id.
-- * the top-level @models@ list and the @engineMembers@ list are gone. A pool
--   now carries its own model descriptors, so a pool naming a model the catalog
--   does not define is unrepresentable rather than rejected; and members are
--   inverted out of the pool graph, so the bidirectional pool\/member link can
--   no longer disagree with itself.
data DhallDemoConfig = DhallDemoConfig
  { dhallConfigRuntimeMode :: DhallRuntimeMode,
    dhallConfigMapName :: Text,
    dhallGeneratedPath :: Text,
    dhallMountedPath :: Text,
    dhallDemoUi :: Bool,
    dhallEnginePools :: [DhallEnginePool],
    dhallModelsBucket :: Text,
    dhallModelBootstrapTopic :: Text,
    dhallInferenceMemoryBudget :: DhallInferenceMemoryBudget
  }
  deriving (Generic)

instance Dhall.FromDhall DhallDemoConfig where
  autoWith _ = Dhall.genericAutoWith dhallInterpretOptions

-- | A pool and the models it serves. Phase 8 Sprint 8.11 moved the model
-- descriptors inside their pool: model ownership is now the structure of the
-- wire rather than a cross-reference between two lists that a generator could
-- get wrong.
data DhallEnginePool = DhallEnginePool
  { dhallPoolId :: Text,
    dhallPoolMemberIds :: [Text],
    dhallPoolSubscriptionType :: DhallConsumerSubscription,
    dhallPoolModels :: [DhallModelDescriptor]
  }
  deriving (Generic)

instance Dhall.FromDhall DhallEnginePool where
  autoWith _ = Dhall.genericAutoWith dhallInterpretOptions

data DhallModelDescriptor = DhallModelDescriptor
  { dhallMatrixRowId :: Text,
    dhallModelId :: Text,
    dhallDisplayName :: Text,
    dhallFamily :: Text,
    dhallDescription :: Text,
    dhallArtifactType :: Text,
    dhallReferenceModel :: Text,
    dhallDownloadUrl :: Text,
    dhallSelectedEngine :: Text,
    dhallRequestShape :: [DhallRequestField],
    dhallNotes :: Text,
    -- | Phase 4 Sprint 4.39: the execution shape the cache term is evaluated
    -- against, and the declared geometry it is evaluated from. Sprint 4.38 put a
    -- closed requirement here in place of the retired @requiresGpu : Bool@ plus
    -- @modelRamFootprintMib : Natural@ pair; this sprint took the quantities off
    -- the wire entirely, because they are derived from the artifact's own bytes
    -- on the machine that will execute. Where the weights live is what remains
    -- declared, and it is what decides which resource the model-size term is
    -- charged to.
    dhallExecutionShape :: DhallModelExecutionShape,
    dhallGeometry :: Maybe DhallModelGeometry
  }
  deriving (Generic)

instance Dhall.FromDhall DhallModelDescriptor where
  autoWith _ = Dhall.genericAutoWith dhallInterpretOptions

data DhallModelExecutionShape = DhallModelExecutionShape
  { dhallShapeContextLength :: Natural,
    dhallShapeBatchSize :: Natural,
    dhallShapeGenerationBound :: Natural,
    dhallShapeCacheElementWidth :: Natural,
    dhallShapeLoadStrategy :: DhallModelLoadStrategy
  }
  deriving (Generic)

instance Dhall.FromDhall DhallModelExecutionShape where
  autoWith _ = Dhall.genericAutoWith dhallInterpretOptions

data DhallModelLoadStrategy
  = DhallModelLoadStrategyLoadResidentHost
  | DhallModelLoadStrategyStreamWeightsToDevice
  deriving (Generic)

instance Dhall.FromDhall DhallModelLoadStrategy where
  autoWith _ =
    Dhall.genericAutoWith (dhallEnumInterpretOptions "DhallModelLoadStrategy")

data DhallModelGeometry = DhallModelGeometry
  { dhallGeometryLayers :: Natural,
    dhallGeometryKeyValueHeads :: Natural,
    dhallGeometryHeadWidth :: Natural,
    dhallGeometryHiddenWidth :: Natural
  }
  deriving (Generic)

instance Dhall.FromDhall DhallModelGeometry where
  autoWith _ = Dhall.genericAutoWith dhallInterpretOptions

-- | The generated execution-plan budget is a proper union. An arm carries only
-- its applicable fields, so the retired text discriminator plus zero-filled
-- fields cannot be represented.
data DhallInferenceMemoryBudget
  = HostEnforced DhallHostMemoryBudget
  | SubstrateEnforced DhallSubstrateMemoryBudget
  | DualEnforced DhallDualMemoryBudget
  deriving (Generic)

instance Dhall.FromDhall DhallInferenceMemoryBudget

-- | Phase 8 Sprint 8.10: the headroom term left the wire. The binary derives it
-- from the checked claimable pool, so a wire field would be a second authored
-- copy of policy the partition owns.
data DhallHostMemoryBudget = DhallHostMemoryBudget
  { dhallBudgetPhysicalMib :: Natural,
    dhallBudgetVmReserveMib :: Natural
  }
  deriving (Generic)

instance Dhall.FromDhall DhallHostMemoryBudget where
  autoWith _ = Dhall.genericAutoWith dhallInterpretOptions

-- | Phase 8 Sprint 8.10: a substrate limit carries only its quantity. Which
-- physical resource it bounds and which policy set it are decided by the runtime
-- mode and by which half of the budget the limit occupies, so a wire copy could
-- only ever disagree with the derivation.
newtype DhallSubstrateMemoryBudget = DhallSubstrateMemoryBudget
  { dhallBudgetLimitMib :: Natural
  }
  deriving (Generic)

instance Dhall.FromDhall DhallSubstrateMemoryBudget where
  autoWith _ = Dhall.genericAutoWith dhallInterpretOptions

-- | Phase 6 Sprint 6.44 — the @linux-gpu@ arm. It reuses the substrate limit
-- record for both halves, so the two limits are structurally identical and the
-- arm names which is which rather than encoding it in a discriminator field.
data DhallDualMemoryBudget = DhallDualMemoryBudget
  { dhallBudgetPodLimit :: DhallSubstrateMemoryBudget,
    dhallBudgetVramLimit :: DhallSubstrateMemoryBudget
  }
  deriving (Generic)

instance Dhall.FromDhall DhallDualMemoryBudget where
  autoWith _ = Dhall.genericAutoWith dhallInterpretOptions

data DhallRequestField = DhallRequestField
  { dhallName :: Text,
    dhallLabel :: Text,
    dhallFieldType :: DhallRequestFieldType
  }
  deriving (Generic)

instance Dhall.FromDhall DhallRequestField where
  autoWith _ = Dhall.genericAutoWith dhallInterpretOptions

data DhallRuntimeMode
  = DhallRuntimeModeAppleSilicon
  | DhallRuntimeModeLinuxCpu
  | DhallRuntimeModeLinuxGpu
  deriving (Generic)

instance Dhall.FromDhall DhallRuntimeMode where
  autoWith _ = Dhall.genericAutoWith (dhallEnumInterpretOptions "DhallRuntimeMode")

runtimeModeFromDhall :: DhallRuntimeMode -> RuntimeMode
runtimeModeFromDhall rawRuntimeMode = case rawRuntimeMode of
  DhallRuntimeModeAppleSilicon -> AppleSilicon
  DhallRuntimeModeLinuxCpu -> LinuxCpu
  DhallRuntimeModeLinuxGpu -> LinuxGpu

runtimeModeAlternative :: RuntimeMode -> String
runtimeModeAlternative runtimeModeValue = case runtimeModeValue of
  AppleSilicon -> "AppleSilicon"
  LinuxCpu -> "LinuxCpu"
  LinuxGpu -> "LinuxGpu"

runtimeModeUnionType :: String
runtimeModeUnionType = dhallEnumUnionType (map runtimeModeAlternative allRuntimeModes)

renderRuntimeMode :: RuntimeMode -> String
renderRuntimeMode = dhallEnumValue runtimeModeUnionType . runtimeModeAlternative

data DhallConsumerSubscription
  = DhallConsumerSubscriptionShared
  | DhallConsumerSubscriptionExclusive
  | DhallConsumerSubscriptionFailover
  deriving (Generic)

instance Dhall.FromDhall DhallConsumerSubscription where
  autoWith _ =
    Dhall.genericAutoWith (dhallEnumInterpretOptions "DhallConsumerSubscription")

consumerSubscriptionFromDhall :: DhallConsumerSubscription -> ConsumerSubscriptionType
consumerSubscriptionFromDhall rawSubscription = case rawSubscription of
  DhallConsumerSubscriptionShared -> ConsumerShared
  DhallConsumerSubscriptionExclusive -> ConsumerExclusive
  DhallConsumerSubscriptionFailover -> ConsumerFailover

consumerSubscriptionAlternative :: ConsumerSubscriptionType -> String
consumerSubscriptionAlternative subscription = case subscription of
  ConsumerShared -> "Shared"
  ConsumerExclusive -> "Exclusive"
  ConsumerFailover -> "Failover"

consumerSubscriptionUnionType :: String
consumerSubscriptionUnionType =
  dhallEnumUnionType
    (map consumerSubscriptionAlternative [ConsumerShared, ConsumerExclusive, ConsumerFailover])

renderConsumerSubscription :: ConsumerSubscriptionType -> String
renderConsumerSubscription =
  dhallEnumValue consumerSubscriptionUnionType . consumerSubscriptionAlternative

-- | The one mirror that cannot use the generic derivation.
--
-- @genericAutoWith@ dispatches on the datatype's GHC-Generics shape, and a
-- single-constructor type has no @:+:@ at all, so it derives as a /record/ —
-- here the empty record @{}@ — rather than as a one-alternative union. Building
-- the union decoder explicitly keeps the wire shape @< TextField >@, so adding
-- a second request-field type later is a wire addition rather than a wire
-- rewrite. The round-trip through the real decode boundary is what catches this;
-- the annotation and the decoder are otherwise unrelated.
data DhallRequestFieldType
  = DhallRequestFieldTypeTextField

instance Dhall.FromDhall DhallRequestFieldType where
  autoWith _ =
    Dhall.union (DhallRequestFieldTypeTextField <$ Dhall.constructor "TextField" Dhall.unit)

requestFieldTypeFromDhall :: DhallRequestFieldType -> RequestFieldType
requestFieldTypeFromDhall rawFieldType = case rawFieldType of
  DhallRequestFieldTypeTextField -> TextRequestField

requestFieldTypeAlternative :: RequestFieldType -> String
requestFieldTypeAlternative fieldTypeValue = case fieldTypeValue of
  TextRequestField -> "TextField"

requestFieldTypeUnionType :: String
requestFieldTypeUnionType =
  dhallEnumUnionType [requestFieldTypeAlternative TextRequestField]

renderRequestFieldType :: RequestFieldType -> String
renderRequestFieldType =
  dhallEnumValue requestFieldTypeUnionType . requestFieldTypeAlternative

-- | Convert a wire 'Natural' into the platform 'Int' the domain types use.
--
-- Phase 8 Sprint 8.9 moved every generated quantity from Dhall @Integer@ to
-- @Natural@, so a negative quantity is no longer representable in the wire
-- language at all rather than being rejected after decode. What @Natural@ does
-- not bound is the top: fail closed on a value the platform integer cannot hold
-- instead of wrapping it into a small positive one.
naturalToInt :: String -> Natural -> Either String Int
naturalToInt fieldPath value
  | toInteger value > toInteger (maxBound :: Int) =
      Left (fieldPath <> " exceeds the supported integer range: " <> show value)
  | otherwise = Right (fromIntegral value)

dhallInterpretOptions :: Dhall.InterpretOptions
dhallInterpretOptions =
  Dhall.defaultInterpretOptions {Dhall.fieldModifier = dhallFieldName}

dhallFieldName :: Text -> Text
-- Phase 8 Sprint 8.9 removed the @legacyDhall@ prefix branch: the pre-union
-- decoder it served is gone and no field carried that prefix any more, so the
-- branch was dead compatibility residue rather than a supported spelling.
dhallFieldName rawFieldName =
  maybe rawFieldName dhallFieldSuffixName (Text.stripPrefix "dhall" rawFieldName)

dhallFieldSuffixName :: Text -> Text
dhallFieldSuffixName suffix =
  case suffix of
    "ConfigRuntimeMode" -> "runtimeMode"
    "DemoUi" -> "demo_ui"
    "ModelsBucket" -> "models_bucket"
    "ModelBootstrapTopic" -> "model_bootstrap_topic"
    "InferenceMemoryBudget" -> "inferenceMemoryBudget"
    "BudgetPhysicalMib" -> "physicalMib"
    "BudgetVmReserveMib" -> "vmReserveMib"
    "BudgetLimitMib" -> "limitMib"
    "BudgetPodLimit" -> "podLimit"
    "BudgetVramLimit" -> "vramLimit"
    "ExecutionShape" -> "executionShape"
    "ShapeContextLength" -> "contextLength"
    "ShapeBatchSize" -> "batchSize"
    "ShapeGenerationBound" -> "generationBound"
    "ShapeCacheElementWidth" -> "cacheElementWidth"
    "ShapeLoadStrategy" -> "loadStrategy"
    "GeometryLayers" -> "layers"
    "GeometryKeyValueHeads" -> "keyValueHeads"
    "GeometryHeadWidth" -> "headWidth"
    "GeometryHiddenWidth" -> "hiddenWidth"
    "EnginePools" -> "enginePools"
    "PoolId" -> "id"
    "PoolMemberIds" -> "members"
    "PoolSubscriptionType" -> "subscription"
    "PoolModels" -> "models"
    other -> lowerInitial other

lowerInitial :: Text -> Text
lowerInitial value =
  case Text.uncons value of
    Nothing -> value
    Just (firstCharacter, rest) -> Text.cons (toLower firstCharacter) rest

-- | Rebuild the domain configuration from the reduced wire.
--
-- Phase 8 Sprint 8.10: every field this reconstructs was previously carried on
-- the wire as a second copy of a fact the binary already derives. Dhall record
-- types are not dependent — a field's type can never mention a sibling's value —
-- so any pair of fields that must agree is a permanent illegal-state generator.
-- Deriving them here is the only shape with no disagreement left to detect,
-- which is why the equality checks that existed to catch such a disagreement are
-- retired with the fields rather than before them.
demoConfigFromDhall :: DhallDemoConfig -> Either String DemoConfig
demoConfigFromDhall rawConfig = do
  let runtimeModeValue = runtimeModeFromDhall (dhallConfigRuntimeMode rawConfig)
  decodedPools <- traverse (enginePoolFromDhall runtimeModeValue) (dhallEnginePools rawConfig)
  memoryBudgetValue <-
    inferenceMemoryBudgetFromDhall runtimeModeValue (dhallInferenceMemoryBudget rawConfig)
  pure
    DemoConfig
      { configRuntimeMode = runtimeModeValue,
        configMapName = dhallConfigMapName rawConfig,
        generatedPath = Text.unpack (dhallGeneratedPath rawConfig),
        mountedPath = Text.unpack (dhallMountedPath rawConfig),
        demoUiEnabled = dhallDemoUi rawConfig,
        configPoolCatalogs =
          [ PoolCatalog
              { poolCatalogId = enginePoolId pool,
                poolCatalogMemberIds = enginePoolMemberIds pool,
                poolCatalogSubscriptionType = enginePoolSubscriptionType pool,
                poolCatalogModels = poolModels
              }
          | (pool, poolModels) <- decodedPools
          ],
        modelsBucket = dhallModelsBucket rawConfig,
        modelBootstrapTopic = dhallModelBootstrapTopic rawConfig,
        inferenceMemoryBudget = memoryBudgetValue
      }

inferenceMemoryBudgetFromDhall ::
  RuntimeMode ->
  DhallInferenceMemoryBudget ->
  Either String InferenceMemoryBudget
inferenceMemoryBudgetFromDhall runtimeModeValue rawBudget =
  case rawBudget of
    HostEnforced hostBudget -> do
      physicalMib <-
        naturalToInt "inferenceMemoryBudget.physicalMib" (dhallBudgetPhysicalMib hostBudget)
      vmReserveMib <-
        naturalToInt "inferenceMemoryBudget.vmReserveMib" (dhallBudgetVmReserveMib hostBudget)
      HostEnforcedBudget <$> mkHostMemoryPartition physicalMib vmReserveMib
    SubstrateEnforced substrateBudget ->
      SubstrateEnforcedBudget
        <$> podMemoryLimitFromDhall
          "inferenceMemoryBudget"
          PodRam
          (residentLimitSourceForMode runtimeModeValue)
          substrateBudget
    DualEnforced dualBudget ->
      DualEnforcedBudget
        <$> podMemoryLimitFromDhall
          "inferenceMemoryBudget.podLimit"
          PodRam
          (residentLimitSourceForMode runtimeModeValue)
          (dhallBudgetPodLimit dualBudget)
        <*> podMemoryLimitFromDhall
          "inferenceMemoryBudget.vramLimit"
          NvidiaVram
          LinuxGpuVramBudget
          (dhallBudgetVramLimit dualBudget)

-- | Which policy set a resident-memory limit. Only the cluster engine pod limit
-- has ever named one; the VRAM half names its own source at its own call site.
residentLimitSourceForMode :: RuntimeMode -> PodMemoryLimitSource
residentLimitSourceForMode _ = ClusterEnginePodMemoryLimit

podMemoryLimitFromDhall ::
  String ->
  Resource ->
  PodMemoryLimitSource ->
  DhallSubstrateMemoryBudget ->
  Either String PodMemoryLimit
podMemoryLimitFromDhall fieldPath limitResource sourceValue substrateBudget = do
  limitMib <- naturalToInt (fieldPath <> ".limitMib") (dhallBudgetLimitMib substrateBudget)
  -- @Natural@ already excludes a negative limit on the wire; zero is still
  -- representable, so the positivity check stays.
  if limitMib <= 0
    then Left (fieldPath <> ".limitMib must be positive")
    else
      pure
        PodMemoryLimit
          { podMemoryLimitResource = limitResource,
            podMemoryLimitSource = sourceValue,
            podMemoryLimitMib = limitMib
          }

enginePoolFromDhall :: RuntimeMode -> DhallEnginePool -> Either String (EnginePool, [ModelDescriptor])
enginePoolFromDhall runtimeModeValue rawPool = do
  poolModels <- traverse (modelDescriptorFromDhall runtimeModeValue) (dhallPoolModels rawPool)
  pure
    ( EnginePool
        { enginePoolId = dhallPoolId rawPool,
          enginePoolRuntimeMode = runtimeModeValue,
          enginePoolModelIds = map modelId poolModels,
          enginePoolMemberIds = dhallPoolMemberIds rawPool,
          enginePoolSubscriptionType =
            consumerSubscriptionFromDhall (dhallPoolSubscriptionType rawPool),
          enginePoolMaxInflightPerMember = defaultMaxInflightPerMember
        },
      poolModels
    )

modelDescriptorFromDhall :: RuntimeMode -> DhallModelDescriptor -> Either String ModelDescriptor
modelDescriptorFromDhall runtimeModeValue rawModel = do
  requestShapeValue <- traverse requestFieldFromDhall (dhallRequestShape rawModel)
  -- Phase 4 Sprint 4.39: the shape's quantities are required and positive, and
  -- the load strategy is what decides whether the model uses the device at all.
  shapeValue <- modelExecutionShapeFromDhall (dhallModelId rawModel) (dhallExecutionShape rawModel)
  geometryValue <-
    traverse (modelGeometryFromDhall (dhallModelId rawModel)) (dhallGeometry rawModel)
  let runtimeLaneValue =
        runtimeLaneForMode
          runtimeModeValue
          (executionLoadStrategy shapeValue == StreamWeightsToDevice)
  pure
    ModelDescriptor
      { matrixRowId = dhallMatrixRowId rawModel,
        modelId = dhallModelId rawModel,
        displayName = dhallDisplayName rawModel,
        family = dhallFamily rawModel,
        description = dhallDescription rawModel,
        artifactType = dhallArtifactType rawModel,
        referenceModel = dhallReferenceModel rawModel,
        downloadUrl = dhallDownloadUrl rawModel,
        selectedEngine = dhallSelectedEngine rawModel,
        requestShape = requestShapeValue,
        runtimeMode = runtimeModeValue,
        runtimeLane = runtimeLaneValue,
        notes = dhallNotes rawModel,
        modelExecutionShape = shapeValue,
        modelGeometry = geometryValue
      }

modelExecutionShapeFromDhall ::
  Text ->
  DhallModelExecutionShape ->
  Either String ModelExecutionShape
modelExecutionShapeFromDhall modelIdValue rawShape = do
  contextLength <- shapeNatural "contextLength" (dhallShapeContextLength rawShape)
  batchSize <- shapeNatural "batchSize" (dhallShapeBatchSize rawShape)
  generationBound <- shapeNatural "generationBound" (dhallShapeGenerationBound rawShape)
  cacheElementWidth <- shapeNatural "cacheElementWidth" (dhallShapeCacheElementWidth rawShape)
  pure
    ModelExecutionShape
      { executionContextLength = contextLength,
        executionBatchSize = batchSize,
        executionGenerationBound = generationBound,
        executionCacheElementWidth = cacheElementWidth,
        executionLoadStrategy = loadStrategyFromDhall (dhallShapeLoadStrategy rawShape)
      }
  where
    shapeNatural fieldName =
      naturalToInt
        ("models." <> Text.unpack modelIdValue <> ".executionShape." <> fieldName)

loadStrategyFromDhall :: DhallModelLoadStrategy -> ModelLoadStrategy
loadStrategyFromDhall rawStrategy =
  case rawStrategy of
    DhallModelLoadStrategyLoadResidentHost -> LoadResidentHost
    DhallModelLoadStrategyStreamWeightsToDevice -> StreamWeightsToDevice

modelGeometryFromDhall :: Text -> DhallModelGeometry -> Either String ModelGeometry
modelGeometryFromDhall modelIdValue rawGeometry = do
  layers <- geometryNatural "layers" (dhallGeometryLayers rawGeometry)
  keyValueHeads <- geometryNatural "keyValueHeads" (dhallGeometryKeyValueHeads rawGeometry)
  headWidth <- geometryNatural "headWidth" (dhallGeometryHeadWidth rawGeometry)
  hiddenWidth <- geometryNatural "hiddenWidth" (dhallGeometryHiddenWidth rawGeometry)
  pure
    ModelGeometry
      { geometryLayers = layers,
        geometryKeyValueHeads = keyValueHeads,
        geometryHeadWidth = headWidth,
        geometryHiddenWidth = hiddenWidth
      }
  where
    geometryNatural fieldName =
      naturalToInt
        ("models." <> Text.unpack modelIdValue <> ".geometry." <> fieldName)

requestFieldFromDhall :: DhallRequestField -> Either String RequestField
requestFieldFromDhall rawField =
  pure
    RequestField
      { name = dhallName rawField,
        label = dhallLabel rawField,
        fieldType = requestFieldTypeFromDhall (dhallFieldType rawField)
      }

renderSubstrateConfig :: DemoConfig -> String
renderSubstrateConfig demoConfig =
  unlines
    [ "{ runtimeMode = " <> renderRuntimeMode (configRuntimeMode demoConfig),
      ", configMapName = " <> dhallText (configMapName demoConfig),
      ", generatedPath = " <> dhallFilePath (generatedPath demoConfig),
      ", mountedPath = " <> dhallFilePath (mountedPath demoConfig),
      ", demo_ui = " <> dhallBool (demoUiEnabled demoConfig),
      ", enginePools = "
        <> dhallList enginePoolType renderPoolCatalog (configPoolCatalogs demoConfig),
      ", models_bucket = " <> dhallText (modelsBucket demoConfig),
      ", model_bootstrap_topic = " <> dhallText (modelBootstrapTopic demoConfig),
      ", inferenceMemoryBudget = " <> renderInferenceMemoryBudget (inferenceMemoryBudget demoConfig),
      "}"
    ]

-- | The single rendered spelling of the generated budget union. Every renderer
-- arm selects from this one value, so a new arm cannot be added to the Haskell
-- ADT and its decoder while some renderer keeps emitting a stale union type.
inferenceMemoryBudgetUnionType :: String
inferenceMemoryBudgetUnionType =
  "< HostEnforced : { physicalMib : Natural, vmReserveMib : Natural }"
    <> " | SubstrateEnforced : "
    <> substrateMemoryBudgetRecordType
    <> " | DualEnforced : { podLimit : "
    <> substrateMemoryBudgetRecordType
    <> ", vramLimit : "
    <> substrateMemoryBudgetRecordType
    <> " } >"

substrateMemoryBudgetRecordType :: String
substrateMemoryBudgetRecordType = "{ limitMib : Natural }"

renderInferenceMemoryBudget :: InferenceMemoryBudget -> String
renderInferenceMemoryBudget budget =
  case budget of
    HostEnforcedBudget partition ->
      inferenceMemoryBudgetUnionType
        <> ".HostEnforced "
        <> "{ physicalMib = "
        <> dhallNatural (hostPartitionPhysicalMib partition)
        <> ", vmReserveMib = "
        <> dhallNatural (hostPartitionVmReserveMib partition)
        <> " }"
    SubstrateEnforcedBudget podLimit ->
      inferenceMemoryBudgetUnionType
        <> ".SubstrateEnforced "
        <> renderPodMemoryLimit podLimit
    DualEnforcedBudget podLimit vramLimit ->
      inferenceMemoryBudgetUnionType
        <> ".DualEnforced "
        <> "{ podLimit = "
        <> renderPodMemoryLimit podLimit
        <> ", vramLimit = "
        <> renderPodMemoryLimit vramLimit
        <> " }"

renderPodMemoryLimit :: PodMemoryLimit -> String
renderPodMemoryLimit podLimit =
  "{ limitMib = "
    <> dhallNatural (podMemoryLimitMib podLimit)
    <> " }"

-- | Render one pool directly from the facts retained from its wire record.
-- Model ids are never stored beside the descriptors: the executable
-- 'EnginePool' projection derives them after decode.
renderPoolCatalog :: PoolCatalog -> String
renderPoolCatalog poolCatalog =
  "{ id = "
    <> dhallText (poolCatalogId poolCatalog)
    <> ", members = "
    <> dhallList "Text" dhallText (poolCatalogMemberIds poolCatalog)
    <> ", subscription = "
    <> renderConsumerSubscription (poolCatalogSubscriptionType poolCatalog)
    <> ", models = "
    <> dhallList modelDescriptorType renderModelDescriptor (poolCatalogModels poolCatalog)
    <> " }"

renderModelDescriptor :: ModelDescriptor -> String
renderModelDescriptor model =
  "{ matrixRowId = "
    <> dhallText (matrixRowId model)
    <> ", modelId = "
    <> dhallText (modelId model)
    <> ", displayName = "
    <> dhallText (displayName model)
    <> ", family = "
    <> dhallText (family model)
    <> ", description = "
    <> dhallText (description model)
    <> ", artifactType = "
    <> dhallText (artifactType model)
    <> ", referenceModel = "
    <> dhallText (referenceModel model)
    <> ", downloadUrl = "
    <> dhallText (downloadUrl model)
    <> ", selectedEngine = "
    <> dhallText (selectedEngine model)
    <> ", requestShape = "
    <> dhallList requestFieldType renderRequestField (requestShape model)
    <> ", notes = "
    <> dhallText (notes model)
    <> ", executionShape = "
    <> renderModelExecutionShape (modelExecutionShape model)
    <> ", geometry = "
    <> renderModelGeometry (modelGeometry model)
    <> " }"

-- | The single rendered spelling of the generated load-strategy union, so a new
-- arm cannot be added to the Haskell ADT and its decoder while some renderer
-- keeps emitting a stale union type.
modelLoadStrategyUnionType :: String
modelLoadStrategyUnionType =
  dhallEnumUnionType ["LoadResidentHost", "StreamWeightsToDevice"]

renderModelLoadStrategy :: ModelLoadStrategy -> String
renderModelLoadStrategy strategy =
  dhallEnumValue modelLoadStrategyUnionType (loadStrategyAlternative strategy)

loadStrategyAlternative :: ModelLoadStrategy -> String
loadStrategyAlternative strategy =
  case strategy of
    LoadResidentHost -> "LoadResidentHost"
    StreamWeightsToDevice -> "StreamWeightsToDevice"

renderModelExecutionShape :: ModelExecutionShape -> String
renderModelExecutionShape shape =
  "{ contextLength = "
    <> dhallNatural (executionContextLength shape)
    <> ", batchSize = "
    <> dhallNatural (executionBatchSize shape)
    <> ", generationBound = "
    <> dhallNatural (executionGenerationBound shape)
    <> ", cacheElementWidth = "
    <> dhallNatural (executionCacheElementWidth shape)
    <> ", loadStrategy = "
    <> renderModelLoadStrategy (executionLoadStrategy shape)
    <> " }"

renderModelGeometry :: Maybe ModelGeometry -> String
renderModelGeometry maybeGeometry =
  case maybeGeometry of
    Nothing -> "None " <> modelGeometryRecordType
    Just geometry ->
      "Some { layers = "
        <> dhallNatural (geometryLayers geometry)
        <> ", keyValueHeads = "
        <> dhallNatural (geometryKeyValueHeads geometry)
        <> ", headWidth = "
        <> dhallNatural (geometryHeadWidth geometry)
        <> ", hiddenWidth = "
        <> dhallNatural (geometryHiddenWidth geometry)
        <> " }"

renderRequestField :: RequestField -> String
renderRequestField requestField =
  "{ name = "
    <> dhallText (name requestField)
    <> ", label = "
    <> dhallText (label requestField)
    <> ", fieldType = "
    <> renderRequestFieldType (fieldType requestField)
    <> " }"

dhallList :: String -> (a -> String) -> [a] -> String
dhallList itemType renderItem values =
  case values of
    [] -> "([] : List " <> itemType <> ")"
    _ -> "[ " <> intercalate ", " (map renderItem values) <> " ]"

dhallBool :: Bool -> String
dhallBool value
  | value = "True"
  | otherwise = "False"

-- | Render a generated quantity as a Dhall @Natural@ literal.
--
-- Every call site renders a value whose non-negativity was already established
-- by a checked constructor or a compiler check: 'mkHostMemoryPartition' rejects
-- a non-positive physical size, a negative reserve, or a pool too small for its
-- derived co-tenant headroom,
-- 'mkModelMemoryFootprint' requires a positive footprint, @InvalidPoolMaxInflight@
-- rejects a non-positive inflight bound, and 'podMemoryLimitFromDhall' plus
-- config validation require a positive limit. A negative value would render as
-- an @Integer@ literal and fail the very next decode rather than round-tripping
-- silently.
dhallNatural :: Int -> String
dhallNatural = show

dhallFilePath :: FilePath -> String
dhallFilePath = dhallText . Text.pack

dhallText :: Text -> String
dhallText value =
  Text.unpack ("\"" <> DhallCore.escapeText value <> "\"")

enginePoolType :: String
enginePoolType =
  "{ id : Text, members : List Text, subscription : "
    <> consumerSubscriptionUnionType
    <> ", models : List "
    <> modelDescriptorType
    <> " }"

requestFieldType :: String
requestFieldType =
  "{ name : Text, label : Text, fieldType : "
    <> requestFieldTypeUnionType
    <> " }"

modelDescriptorType :: String
modelDescriptorType =
  "{ matrixRowId : Text, modelId : Text, displayName : Text, family : Text, description : Text, artifactType : Text, referenceModel : Text, downloadUrl : Text, selectedEngine : Text, requestShape : List "
    <> requestFieldType
    <> ", notes : Text, executionShape : "
    <> modelExecutionShapeRecordType
    <> ", geometry : Optional "
    <> modelGeometryRecordType
    <> " }"

modelExecutionShapeRecordType :: String
modelExecutionShapeRecordType =
  "{ contextLength : Natural, batchSize : Natural, generationBound : Natural, cacheElementWidth : Natural, loadStrategy : "
    <> modelLoadStrategyUnionType
    <> " }"

modelGeometryRecordType :: String
modelGeometryRecordType =
  "{ layers : Natural, keyValueHeads : Natural, headWidth : Natural, hiddenWidth : Natural }"
