kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: infernix-linux-cuda
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia]
      privileged_without_host_devices = false
      runtime_type = "io.containerd.runc.v2"
    [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia.options]
      BinaryName = "/usr/bin/nvidia-container-runtime"
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30090
        hostPort: 9090
        protocol: TCP
      - containerPort: 30002
        hostPort: 30002
        protocol: TCP
      - containerPort: 30011
        hostPort: 30011
        protocol: TCP
      - containerPort: 30080
        hostPort: 30080
        protocol: TCP
      - containerPort: 30650
        hostPort: 30650
        protocol: TCP
    extraMounts:
      - hostPath: ./.build/kind/registry
        containerPath: /etc/containerd/certs.d
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "infernix.runtime/mode=linux-cuda"
  - role: worker
    extraMounts:
      - hostPath: ./.build/kind/registry
        containerPath: /etc/containerd/certs.d
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "infernix.runtime/mode=linux-cuda,infernix.runtime/gpu=true"
