from __future__ import annotations

import argparse
import ast
import contextlib
import hashlib
import importlib
import importlib.util
import io
import json
import os
import subprocess
import sys
import tempfile
import traceback
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path
from typing import Any, cast


def _repo_root() -> Path:
    # Phase 5 Sprint 5.9 follow-on (May 26, 2026): the supported repo
    # root is the parent of the python project that contains this
    # adapters module. The previous INFERNIX_REPO_ROOT env override
    # was redundant — the canonical Poetry invocation always runs from
    # `<repoRoot>/python` and `__file__`-anchored resolution gives the
    # same path. Retiring the env read closes the configuration-doctrine
    # rule that adapters may not read process environments for config.
    return Path(__file__).resolve().parents[2]


generated_proto_root = _repo_root() / "tools" / "generated_proto"
if str(generated_proto_root) not in sys.path:
    sys.path.insert(0, str(generated_proto_root))

try:
    inference_pb2: Any = importlib.import_module("infernix.runtime.inference_pb2")
except ModuleNotFoundError:  # pragma: no cover - exercised before proto generation
    inference_pb2 = None

__all__ = [
    "AdapterContext",
    "ArtifactResult",
    "DEMO_OBJECTS_BUCKET",
    "download_demo_object",
    "inference_pb2",
    "materialize_temp_input",
    "normalized_input_text",
    "run_artifact_adapter",
    "run_model_bootstrap_from_argv",
    "run_check_code",
    "run_context_adapter",
    "run_setup_bootstrap",
    "run_setup_from_argv",
    "short_digest",
]

# Phase 4 Sprint 4.15: the always-on MinIO bucket the artifact families
# (source separation, audio-to-MIDI, music transcription, image, video,
# audio generation, OMR) write their generated bytes to. The retired
# infernix-runtime / infernix-results buckets are never used.
DEMO_OBJECTS_BUCKET = "infernix-demo-objects"


def run_model_bootstrap_from_argv() -> int:
    from adapters.model_bootstrap import run_model_bootstrap_from_argv as run

    return run()


def run_setup_from_argv(adapter_id: str) -> int:
    """Phase 5 Sprint 5.9 follow-on (May 26, 2026): the supported
    setup entrypoint reads ``--install-root <path>`` from argv instead
    of consuming ``INFERNIX_ENGINE_INSTALL_ROOT`` from the
    environment. The Haskell daemon's ``runSetupInvocation`` passes
    the path as a typed CLI argument. When invoked without
    ``--install-root`` (legacy code path), the helper falls through
    to the repo-local default behind ``run_setup_bootstrap`` for direct
    developer calls that are outside the supported Haskell invocation.
    """
    parser = argparse.ArgumentParser(
        prog=f"setup-{adapter_id}",
        description=(
            f"Run the {adapter_id} adapter's setup bootstrap. The supported "
            "invocation passes --install-root explicitly; direct developer "
            "calls fall back to the repo-local adapter install root."
        ),
    )
    parser.add_argument(
        "--install-root",
        required=False,
        default=None,
        help="Absolute path to the engine install root for this adapter.",
    )
    args = parser.parse_args()
    install_root = Path(args.install_root) if args.install_root else None
    return run_setup_bootstrap(adapter_id, install_root=install_root)


@dataclass(frozen=True)
class AdapterContext:
    adapter_id: str
    runtime_mode: str
    model_id: str
    display_name: str
    family: str
    selected_engine: str
    artifact_type: str
    runtime_lane: str
    input_text: str
    # Phase 4 Sprint 4.15: object reference for the non-text input families
    # (audio/image/score). Empty string for the text families.
    input_object_ref: str
    # Phase 7 Sprint 7.28: Haskell-derived object-key prefix for generated
    # artifact uploads, e.g. users/<sub>/contexts/<ctx>/generated/.
    generated_output_object_prefix: str
    bootstrap_ready: bool
    bootstrap_manifest_path: str


def _decode_request() -> inference_pb2.WorkerRequest:
    _require_inference_pb2()
    request = inference_pb2.WorkerRequest()
    request.ParseFromString(sys.stdin.buffer.read())
    return request


_PROTOBUF_STDOUT_FD: int | None = None
_ADAPTER_LOG_PATH: Path | None = None


def _isolate_protobuf_stdout() -> None:
    """Reserve the adapter's stdout for the protobuf ``WorkerResponse`` alone.

    The Haskell worker streams the request to the adapter's stdin and reads the
    serialized ``WorkerResponse`` back from its stdout, so any other bytes on
    file descriptor 1 corrupt the protobuf frame (it surfaces in the worker as
    ``Unknown wire type``). Inference backends such as vLLM log copiously to
    stdout while constructing the engine, which lands ahead of the protobuf and
    breaks the decode. Duplicate the real stdout to a private fd that
    ``_write_response`` targets, then point fd 1 at an adapter-owned temporary
    file so every other stdout write — Python or native C/CUDA — stays away from
    the frame.

    Both fd 1 and fd 2 are pointed at the temporary file: the worker captures the
    adapter's stdout AND stderr on pipes it does not drain until the response
    arrives, and vLLM logs copiously to both while constructing the engine, so
    leaving either fd on its pipe lets the buffer fill and deadlocks the engine
    on ``write`` mid-construction (observed as fd 2 / stderr blocking on
    ``anon_pipe_write``). The serialized response — including any adapter error,
    which is caught and returned as a ``WorkerResponse`` rather than printed —
    travels on the saved real-stdout fd. Failed responses include a bounded tail
    of the backend log so engine-core errors keep their root cause without
    risking pipe deadlocks. Configuration doctrine forbids env toggles (e.g.
    ``VLLM_LOGGING_LEVEL``), so this is enforced structurally at the fd boundary.
    """
    global _ADAPTER_LOG_PATH, _PROTOBUF_STDOUT_FD
    if _PROTOBUF_STDOUT_FD is not None:
        return
    sys.stdout.flush()
    sys.stderr.flush()
    _PROTOBUF_STDOUT_FD = os.dup(1)
    log_fd, log_path = tempfile.mkstemp(prefix="infernix-adapter-", suffix=".log")
    _ADAPTER_LOG_PATH = Path(log_path)
    os.dup2(log_fd, 1)
    os.dup2(log_fd, 2)
    os.close(log_fd)


def _write_response(response: inference_pb2.WorkerResponse) -> None:
    payload = response.SerializeToString()
    if _PROTOBUF_STDOUT_FD is not None:
        os.write(_PROTOBUF_STDOUT_FD, payload)
        return
    sys.stdout.buffer.write(payload)
    sys.stdout.buffer.flush()


def _adapter_backend_log_tail(max_bytes: int = 12000) -> str:
    if _ADAPTER_LOG_PATH is None:
        return ""
    try:
        with _ADAPTER_LOG_PATH.open("rb") as handle:
            handle.seek(0, os.SEEK_END)
            size = handle.tell()
            handle.seek(max(0, size - max_bytes), os.SEEK_SET)
            payload = handle.read()
    except OSError:
        return ""
    text = payload.decode("utf-8", errors="replace").strip()
    if not text:
        return ""
    if size > max_bytes:
        return "[backend log truncated]\n" + text
    return text


def _adapter_error_message(exc: Exception) -> str:
    message_parts = [
        f"{type(exc).__name__}: {exc}",
        "Python traceback:",
        "".join(traceback.format_exception(type(exc), exc, exc.__traceback__)).strip(),
    ]
    backend_tail = _adapter_backend_log_tail()
    if backend_tail:
        message_parts.extend(["Backend log tail:", backend_tail])
    return "\n".join(part for part in message_parts if part)


def _cleanup_adapter_log() -> None:
    global _ADAPTER_LOG_PATH
    if _ADAPTER_LOG_PATH is None:
        return
    try:
        _ADAPTER_LOG_PATH.unlink(missing_ok=True)
    except OSError:
        pass
    _ADAPTER_LOG_PATH = None


def _adapter_error_code(exc: Exception) -> str:
    from adapters import model_cache

    if isinstance(exc, model_cache.ModelCacheNotPopulated):
        return "model_cache_not_populated"
    return "adapter_failed"


def normalized_input_text(value: str) -> str:
    return " ".join(value.split())


def run_context_adapter(transform: Callable[[AdapterContext], str]) -> int:
    request = _decode_request()
    _isolate_protobuf_stdout()
    try:
        _configure_model_cache_from_request(request)
        output_text = transform(load_adapter_context(request))
    except Exception as exc:  # pragma: no cover - surfaced through worker tests
        error_response = inference_pb2.WorkerResponse(
            error_code=_adapter_error_code(exc),
            error_message=_adapter_error_message(exc),
        )
        _write_response(error_response)
        _cleanup_adapter_log()
        return 0
    response = inference_pb2.WorkerResponse(output_text=output_text)
    _write_response(response)
    _cleanup_adapter_log()
    return 0


@dataclass(frozen=True)
class ArtifactResult:
    """Phase 4 Sprint 4.15 — a generated binary artifact from an artifact
    family adapter. ``data`` is uploaded to the ``infernix-demo-objects``
    MinIO bucket and the resulting object reference (``bucket/key``) is
    returned to the Haskell worker in ``WorkerResponse.object_ref``."""

    data: bytes
    content_type: str
    suffix: str


def run_artifact_adapter(transform: Callable[[AdapterContext], ArtifactResult]) -> int:
    """Phase 4 Sprint 4.15 — the artifact-family seam.

    Shares the protobuf-over-stdio boundary with ``run_context_adapter``
    but uploads the generated bytes to ``infernix-demo-objects`` and
    returns the object reference in ``WorkerResponse.object_ref`` instead
    of inline ``output_text``. Used by the source-separation,
    audio-to-MIDI, music-transcription, image, video, audio-generation,
    and OMR families; the text families keep using ``run_context_adapter``.
    """
    request = _decode_request()
    _isolate_protobuf_stdout()
    try:
        _configure_model_cache_from_request(request)
        context = load_adapter_context(request)
        artifact = transform(context)
        if not artifact.data:
            raise RuntimeError(
                "artifact adapter returned empty bytes; refusing to publish a "
                "non-real (empty) inference artifact"
            )
        object_ref = _upload_demo_object(context, artifact)
    except Exception as exc:  # pragma: no cover - surfaced through worker tests
        error_response = inference_pb2.WorkerResponse(
            error_code=_adapter_error_code(exc),
            error_message=_adapter_error_message(exc),
        )
        _write_response(error_response)
        _cleanup_adapter_log()
        return 0
    response = inference_pb2.WorkerResponse(object_ref=object_ref)
    _write_response(response)
    _cleanup_adapter_log()
    return 0


def materialize_temp_input(data: bytes, suffix: str) -> str:
    # Phase 4 Sprint 4.15: several artifact engines (basic-pitch, MT3,
    # Omnizart) take an input file path rather than bytes. Stage the
    # downloaded input under a temp file and return its path.
    import tempfile

    with tempfile.NamedTemporaryFile(suffix=suffix, delete=False) as handle:
        handle.write(data)
        return handle.name


def download_demo_object(object_ref: str) -> bytes:
    # Phase 4 Sprint 4.15: fetch a non-text input (audio/image/score) the
    # input families consume, from its infernix-demo-objects object
    # reference. boto3 is lazy-imported to keep the quality gate
    # machine-independent.
    from adapters import model_cache

    config = model_cache.configured()
    try:
        import boto3
        from botocore.client import Config
    except ImportError as exc:  # pragma: no cover - exercised on cohort hardware
        raise RuntimeError(
            "boto3 is unavailable in this engine venv; cannot download the "
            f"input object {object_ref!r}. Run `poetry install` to reconcile "
            "the supported adapter dependencies."
        ) from exc
    bucket, _, key = object_ref.partition("/")
    client = boto3.client(
        "s3",
        endpoint_url=config.minio_endpoint,
        aws_access_key_id=config.minio_access_key,
        aws_secret_access_key=config.minio_secret_key,
        region_name=config.minio_region,
        config=Config(signature_version="s3v4"),
    )
    response = client.get_object(Bucket=bucket, Key=key)
    payload: bytes = response["Body"].read()
    return payload


def _upload_demo_object(context: AdapterContext, artifact: ArtifactResult) -> str:
    # Phase 4 Sprint 4.15: upload the generated artifact to
    # infernix-demo-objects, reusing the engine daemon's MinIO wiring.
    # boto3 is lazy-imported so `poetry run check-code` stays
    # machine-independent (see documents/development/python_policy.md
    # "Machine-Independent Gate Invariant").
    from adapters import model_cache

    config = model_cache.configured()
    try:
        import boto3
        from botocore.client import Config
    except ImportError as exc:  # pragma: no cover - exercised on cohort hardware
        raise RuntimeError(
            "boto3 is unavailable in this engine venv; cannot upload the "
            f"{context.family} artifact to {DEMO_OBJECTS_BUCKET}. Run "
            "`poetry install` to reconcile the supported adapter dependencies."
        ) from exc
    output_prefix = _validated_generated_output_prefix(context)
    object_key = (
        f"{output_prefix}{_safe_object_key_segment(context.family)}-"
        f"{_safe_object_key_segment(context.model_id)}-"
        f"sha256-{hashlib.sha256(artifact.data).hexdigest()}{_safe_artifact_suffix(artifact.suffix)}"
    )
    artifact_bucket = config.demo_artifacts_bucket or DEMO_OBJECTS_BUCKET
    client = boto3.client(
        "s3",
        endpoint_url=config.minio_endpoint,
        aws_access_key_id=config.minio_access_key,
        aws_secret_access_key=config.minio_secret_key,
        region_name=config.minio_region,
        config=Config(signature_version="s3v4"),
    )
    client.put_object(
        Bucket=artifact_bucket,
        Key=object_key,
        Body=artifact.data,
        ContentType=artifact.content_type,
    )
    return f"{artifact_bucket}/{object_key}"


def _validated_generated_output_prefix(context: AdapterContext) -> str:
    prefix = context.generated_output_object_prefix
    if not prefix:
        raise RuntimeError(
            "artifact adapter request is missing generated_output_object_prefix; "
            "refusing to invent a generated object key"
        )
    if (
        not prefix.startswith("users/")
        or "/contexts/" not in prefix
        or not prefix.endswith("/generated/")
        or ".." in prefix
        or "//" in prefix
    ):
        raise RuntimeError(
            f"invalid generated_output_object_prefix {prefix!r}; expected "
            "users/<sub>/contexts/<ctx>/generated/"
        )
    return prefix


def _safe_object_key_segment(value: str) -> str:
    safe = "".join(
        character if character.isalnum() or character in "._-" else "-"
        for character in value
    ).strip("-")
    return safe or "artifact"


def _safe_artifact_suffix(value: str) -> str:
    suffix = value if value.startswith(".") else f".{value}"
    safe = "".join(
        character if character.isalnum() or character in "._-" else "-"
        for character in suffix
    )
    return safe if safe.startswith(".") and len(safe) > 1 else ".bin"


def _configure_model_cache_from_request(request: inference_pb2.WorkerRequest) -> None:
    # Phase 4 real-engine follow-on: the private Haskell->adapter protobuf
    # request carries cluster-decoded cache + MinIO wiring, replacing the
    # doc-promised but previously missing call to adapters.model_cache.configure().
    from adapters import model_cache

    if not _worker_request_has_model_cache_config(request):
        return

    defaults = model_cache.ModelCacheConfig()
    model_cache.configure(
        model_cache.ModelCacheConfig(
            cache_root=(
                Path(cast(str, request.model_cache_root))
                if cast(str, request.model_cache_root)
                else defaults.cache_root
            ),
            quota_bytes=(
                int(cast(int, request.model_cache_quota_bytes))
                if cast(int, request.model_cache_quota_bytes)
                else defaults.quota_bytes
            ),
            models_bucket=cast(str, request.minio_models_bucket)
            or defaults.models_bucket,
            demo_artifacts_bucket=cast(str, request.minio_demo_artifacts_bucket)
            or defaults.demo_artifacts_bucket,
            minio_endpoint=cast(str, request.minio_endpoint),
            minio_access_key=cast(str, request.minio_access_key),
            minio_secret_key=cast(str, request.minio_secret_key),
            minio_region=cast(str, request.minio_region) or defaults.minio_region,
        )
    )


def _worker_request_has_model_cache_config(
    request: inference_pb2.WorkerRequest,
) -> bool:
    return any(
        [
            bool(cast(str, request.model_cache_root)),
            bool(cast(int, request.model_cache_quota_bytes)),
            bool(cast(str, request.minio_endpoint)),
            bool(cast(str, request.minio_models_bucket)),
            bool(cast(str, request.minio_demo_artifacts_bucket)),
            bool(cast(str, request.minio_region)),
            bool(cast(str, request.minio_access_key)),
            bool(cast(str, request.minio_secret_key)),
        ]
    )


def run_setup_bootstrap(adapter_id: str, install_root: Path | None = None) -> int:
    # Phase 5 Sprint 5.9 follow-on (May 26, 2026): `install_root` is
    # passed explicitly by the setup entrypoint's argparse layer
    # (`--install-root <path>`). Direct developer calls that omit it
    # fall back to the repo-local default in `_engine_install_root`.
    # The bootstrap manifest no longer carries a `runtimeMode` field
    # discovered from process environment. The supported per-substrate
    # adapter dispatch happens upstream of this setup helper (the
    # Haskell daemon decodes the active substrate from the staged
    # `infernix-substrate.dhall` before selecting which adapters to
    # bootstrap), so this manifest records only the versioned adapter
    # identity. Identical setup operations must publish identical evidence.
    resolved_install_root = (
        install_root if install_root is not None else _engine_install_root(adapter_id)
    )
    resolved_install_root.mkdir(parents=True, exist_ok=True)
    install_root = resolved_install_root
    bootstrap_manifest = {
        "adapterId": adapter_id,
        "schemaVersion": 1,
    }
    bootstrap_path = install_root / "bootstrap.json"
    staging_path = install_root / ".bootstrap.json.tmp"
    payload = json.dumps(bootstrap_manifest, indent=2, sort_keys=True) + "\n"
    staging_flags = (
        os.O_WRONLY
        | os.O_CREAT
        | os.O_TRUNC
        | getattr(os, "O_CLOEXEC", 0)
        | getattr(os, "O_NOFOLLOW", 0)
    )
    staging_fd = os.open(staging_path, staging_flags, 0o600)
    with os.fdopen(staging_fd, "w", encoding="utf-8", newline="\n") as staging:
        staging.write(payload)
        staging.flush()
        os.fsync(staging.fileno())
    os.replace(staging_path, bootstrap_path)
    directory_fd = os.open(
        install_root,
        os.O_RDONLY | getattr(os, "O_DIRECTORY", 0) | getattr(os, "O_CLOEXEC", 0),
    )
    try:
        os.fsync(directory_fd)
    finally:
        os.close(directory_fd)
    print(f"setup ready: {adapter_id}")
    return 0


_REALNESS_ADAPTER_GLOB = "*_python.py"
_FORBIDDEN_HELPER_FRAGMENTS = (
    "validation",
    "smoke",
    "fallback",
    "placeholder",
    "stub",
)


def _run_realness_ast_check(adapters_dir: Path) -> None:
    """Realness-by-construction static guard (reopened Phase 6).

    Rejects the fabrication patterns that would let a per-family adapter
    return a non-real result: a ``return`` inside an ``except`` (masking a
    failure as a fabricated success), a fabrication-named helper definition,
    or artifact bytes built from a literal ``bytes([...])`` or a decoded
    constant. Scoped to the ``*_python.py`` transform modules; the ``common``
    harness legitimately returns an error response from ``except``.
    """
    violations: list[str] = []
    for path in sorted(adapters_dir.glob(_REALNESS_ADAPTER_GLOB)):
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        for node in ast.walk(tree):
            if isinstance(node, ast.ExceptHandler):
                for inner in ast.walk(node):
                    if isinstance(inner, ast.Return) and inner.value is not None:
                        violations.append(
                            f"{path.name}:{inner.lineno}: return inside except "
                            "masks a failure; re-raise so the worker reports "
                            "status=failed"
                        )
            if isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef):
                lowered = node.name.lower()
                if any(fragment in lowered for fragment in _FORBIDDEN_HELPER_FRAGMENTS):
                    violations.append(
                        f"{path.name}:{node.lineno}: helper '{node.name}' names "
                        "a fabrication path; adapters return only real output"
                    )
            if isinstance(node, ast.Call):
                name: str | None = None
                if isinstance(node.func, ast.Name):
                    name = node.func.id
                elif isinstance(node.func, ast.Attribute):
                    name = node.func.attr
                if name == "bytes" and node.args and isinstance(node.args[0], ast.List):
                    violations.append(
                        f"{path.name}:{node.lineno}: bytes([...]) literal "
                        "fabricates artifact bytes"
                    )
                if (
                    name in {"b64decode", "b64encode"}
                    and node.args
                    and isinstance(node.args[0], ast.Constant)
                ):
                    violations.append(
                        f"{path.name}:{node.lineno}: decoding a literal constant "
                        "fabricates artifact bytes"
                    )
    if violations:
        raise RuntimeError("realness check failed:\n" + "\n".join(violations))


def _run_native_runner_realness_check(runners_dir: Path) -> None:
    """Realness guard for the native-runner CLIs (``python/native-runners``).

    The name/except heuristics used for the per-family ``*_python.py`` transform
    modules do not transfer here: a native runner is a CLI with a legitimate
    ``smoke`` subcommand and fail-closed error-code ``return`` statements inside
    ``except`` handlers. This applies only the module-agnostic fabrication
    signals — artifact bytes built from a ``bytes([...])`` literal or a decoded
    constant — so a hardcoded-artifact regression in the runner is still caught.
    """
    violations: list[str] = []
    for path in sorted(runners_dir.glob("*.py")):
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        for node in ast.walk(tree):
            if isinstance(node, ast.Call):
                name: str | None = None
                if isinstance(node.func, ast.Name):
                    name = node.func.id
                elif isinstance(node.func, ast.Attribute):
                    name = node.func.attr
                if name == "bytes" and node.args and isinstance(node.args[0], ast.List):
                    violations.append(
                        f"{path.name}:{node.lineno}: bytes([...]) literal "
                        "fabricates artifact bytes"
                    )
                if (
                    name in {"b64decode", "b64encode"}
                    and node.args
                    and isinstance(node.args[0], ast.Constant)
                ):
                    violations.append(
                        f"{path.name}:{node.lineno}: decoding a literal constant "
                        "fabricates artifact bytes"
                    )
    if violations:
        raise RuntimeError(
            "native-runner realness check failed:\n" + "\n".join(violations)
        )


def _load_native_runner_for_contract_check(runner_path: Path) -> Any:
    module_name = "_infernix_check_apple_native_runner"
    spec = importlib.util.spec_from_file_location(module_name, runner_path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load native runner contract from {runner_path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = module
    try:
        spec.loader.exec_module(module)
    except BaseException:
        sys.modules.pop(module_name, None)
        raise
    return module


def _apple_native_runner_ownership_violations(
    source_name: str, runner_source: str
) -> list[str]:
    runner_tree = ast.parse(runner_source, filename=source_name)
    forbidden_modules = {
        "_posixsubprocess",
        "asyncio",
        "ctypes",
        "multiprocessing",
        "os",
        "posix",
        "pty",
        "subprocess",
    }
    forbidden_calls = {
        "Popen",
        "exec",
        "fork",
        "popen",
        "posix_spawn",
        "posix_spawnp",
        "spawn",
        "system",
        "wait",
        "wait3",
        "wait4",
        "waitid",
        "waitpid",
    }
    forbidden_builtin_loaders = {"__import__", "compile", "eval", "exec"}
    violations: list[str] = []
    for node in ast.walk(runner_tree):
        if isinstance(node, ast.Import):
            for imported in node.names:
                if imported.name.split(".", 1)[0] in forbidden_modules:
                    violations.append(
                        f"{source_name}:{node.lineno}: forbidden process module "
                        f"{imported.name}"
                    )
        elif isinstance(node, ast.ImportFrom):
            imported_module = (node.module or "").split(".", 1)[0]
            if imported_module in forbidden_modules:
                violations.append(
                    f"{source_name}:{node.lineno}: forbidden process module "
                    f"{node.module}"
                )
        elif isinstance(node, ast.Call):
            call_name: str | None = None
            if isinstance(node.func, ast.Name):
                call_name = node.func.id
                if call_name in forbidden_builtin_loaders:
                    violations.append(
                        f"{source_name}:{node.lineno}: forbidden dynamic code loader "
                        f"{call_name}"
                    )
            elif isinstance(node.func, ast.Attribute):
                call_name = node.func.attr
                if call_name == "import_module":
                    violations.append(
                        f"{source_name}:{node.lineno}: forbidden dynamic module loader "
                        "import_module"
                    )
            if call_name is not None and (
                call_name in forbidden_calls
                or call_name.startswith("exec")
                or call_name.startswith("spawn")
                or call_name.startswith("wait")
            ):
                violations.append(
                    f"{source_name}:{node.lineno}: forbidden child-process "
                    f"operation {call_name}"
                )
            if any(keyword.arg == "shell" for keyword in node.keywords):
                violations.append(
                    f"{source_name}:{node.lineno}: forbidden shell invocation"
                )
    if "_run_subprocess" in runner_source:
        violations.append(
            f"{source_name}: forbidden subprocess helper remains in source"
        )
    if "parse_known_args" in runner_source:
        violations.append(f"{source_name}: runner accepts unknown command operands")
    return violations


def _run_apple_native_runner_contract_check(runner_path: Path) -> None:
    """Prove that the Python runner cannot create or own child processes."""
    runner_source = runner_path.read_text(encoding="utf-8")
    violations = _apple_native_runner_ownership_violations(
        runner_path.name, runner_source
    )
    if violations:
        raise RuntimeError(
            "apple native runner ownership check failed:\n" + "\n".join(violations)
        )

    rejected_sources = {
        "builtin-import.py": "__import__('subprocess')\n",
        "builtin-eval.py": "eval('1 + 1')\n",
        "builtin-exec.py": "exec('value = 1')\n",
        "builtin-compile.py": "compile('value = 1', '<contract>', 'exec')\n",
        "import-module.py": (
            "import importlib\n"
            "process_module = importlib.import_module('subprocess')\n"
        ),
    }
    for source_name, rejected_source in rejected_sources.items():
        if not _apple_native_runner_ownership_violations(source_name, rejected_source):
            raise RuntimeError(
                "apple native runner ownership check failed: dynamic loader "
                f"fixture {source_name} was accepted"
            )
    if _apple_native_runner_ownership_violations(
        "mlx-eval.py",
        "import mlx.core as mx\nobserved = mx.eval(value)\n",
    ):
        raise RuntimeError(
            "apple native runner ownership check failed: mx.eval was mistaken "
            "for built-in eval"
        )

    runner = _load_native_runner_for_contract_check(runner_path)
    original_argv = sys.argv
    try:
        sys.argv = [
            str(runner_path),
            "--adapter-id",
            "onnx-runtime-native",
            "--engine-name",
            "contract-engine",
            "--expected-python-prefix",
            str(Path(sys.prefix)),
            "--smoke",
        ]
        smoke_args = runner._parse_args()
        if not smoke_args.smoke_only:
            raise RuntimeError(
                "apple native runner contract check: exact --smoke was not accepted"
            )
        sys.argv = [
            str(runner_path),
            "--adapter-id",
            "onnx-runtime-native",
            "--engine-name",
            "contract-engine",
            "--expected-python-prefix",
            str(Path(sys.prefix)),
            "--help",
        ]
        with contextlib.redirect_stderr(io.StringIO()):
            try:
                runner._parse_args()
            except SystemExit as exc:
                if exc.code == 0:
                    raise RuntimeError(
                        "apple native runner contract check: --help exited successfully"
                    ) from exc
            else:
                raise RuntimeError(
                    "apple native runner contract check: --help became smoke authority"
                )
    finally:
        sys.argv = original_argv

    with tempfile.TemporaryDirectory(
        prefix="infernix-native-runner-contract-"
    ) as temporary_root:
        root = Path(temporary_root)
        for adapter_id in ("llama-cpp-cli", "whisper-cpp-cli", "jvm-native"):
            args = runner.RunnerArgs(
                adapter_id=adapter_id,
                engine_name="contract-engine",
                model_id="contract-model",
                selected_engine="contract-engine",
                family="contract-family",
                install_root=root / "candidate",
                input_text="",
                input_object_ref="",
                input_file="",
                model_cache_root=None,
                output_dir=None,
                expected_python_prefix=Path(sys.prefix),
                smoke_only=False,
            )
            for operation_name, operation in (
                ("smoke", runner._run_smoke),
                ("inference", runner._run_inference),
            ):
                try:
                    operation(args)
                except runner.RunnerFailure as exc:
                    if (
                        exc.exit_code != 70
                        or "Haskell direct-target supervision" not in str(exc)
                    ):
                        raise RuntimeError(
                            "apple native runner ownership check failed: "
                            f"{adapter_id} {operation_name} produced exit="
                            f"{exc.exit_code} message={exc}"
                        ) from exc
                else:
                    raise RuntimeError(
                        "apple native runner ownership check failed: "
                        f"{adapter_id} {operation_name} did not reject Python "
                        "process ownership"
                    )

        output_root = root / "output"
        output_root.mkdir()
        regular_output = output_root / "artifact.bin"
        regular_output.write_bytes(b"contract-output")
        accepted_output = runner._require_nonempty_output(
            output_root, regular_output, "contract"
        )
        if accepted_output != regular_output.resolve():
            raise RuntimeError(
                "apple native runner output check changed the accepted exact path"
            )
        empty_output = output_root / "empty.bin"
        empty_output.touch()
        external_output = root / "external.bin"
        external_output.write_bytes(b"external")
        linked_output = output_root / "linked.bin"
        linked_output.symlink_to(external_output)
        for label, rejected_output in (
            ("empty", empty_output),
            ("external", external_output),
            ("symlink", linked_output),
        ):
            try:
                runner._require_nonempty_output(
                    output_root, rejected_output, "contract"
                )
            except runner.RunnerFailure:
                pass
            else:
                raise RuntimeError(
                    "apple native runner output check accepted "
                    f"{label} artifact {rejected_output}"
                )


def run_check_code() -> int:
    project_root = Path(__file__).resolve().parent.parent
    env = {"MYPYPATH": str(generated_proto_root)}
    commands = [
        [sys.executable, "-m", "mypy", "--strict", "adapters"],
        [sys.executable, "-m", "black", "--check", "adapters"],
        [sys.executable, "-m", "ruff", "check", "adapters"],
    ]
    for command in commands:
        subprocess.run(command, cwd=project_root, check=True, env=env)
    _run_realness_ast_check(project_root / "adapters")
    _run_native_runner_realness_check(project_root / "native-runners")
    _run_apple_native_runner_contract_check(
        project_root / "native-runners" / "apple_native_runner.py"
    )
    return 0


def load_adapter_context(request: inference_pb2.WorkerRequest) -> AdapterContext:
    # Phase 7 Sprint 7.7 retires the ./.data/object-store/ tree, so the
    # daemon ships model metadata straight on the WorkerRequest envelope
    # instead of staging synthetic artifact-bundle / source-manifest JSON
    # files. The MinIO infernix-models bucket is now the only durable
    # source of weight artifacts, fetched lazily by
    # adapters.model_cache.get_model_path.
    bootstrap_path = Path(cast(str, request.engine_install_root)) / "bootstrap.json"
    bootstrap_ready = bootstrap_path.exists()
    return AdapterContext(
        adapter_id=cast(str, request.adapter_id),
        runtime_mode=cast(str, request.runtime_mode),
        model_id=cast(str, request.request_model_id),
        display_name=cast(str, request.display_name),
        family=cast(str, request.family),
        selected_engine=cast(str, request.selected_engine),
        artifact_type=cast(str, request.artifact_type),
        runtime_lane=cast(str, request.runtime_lane),
        input_text=normalized_input_text(cast(str, request.input_text)),
        input_object_ref=cast(str, request.input_object_ref),
        generated_output_object_prefix=cast(
            str, request.generated_output_object_prefix
        ),
        bootstrap_ready=bootstrap_ready,
        bootstrap_manifest_path=str(bootstrap_path),
    )


def short_digest(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()[:10]


def _engine_install_root(adapter_id: str) -> Path:
    # Phase 5 Sprint 5.9 follow-on (May 26, 2026): the
    # INFERNIX_ENGINE_INSTALL_ROOT env override is retired. The
    # supported setup invocation passes `--install-root` as a typed
    # CLI arg through `run_setup_from_argv`, so this fallback is
    # reached only when a direct caller invokes
    # `run_setup_bootstrap(adapter_id)` without an explicit
    # `install_root`. The supported convention is then
    # `<repoRoot>/.data/engines/<adapter_id>`.
    return _repo_root() / ".data" / "engines" / adapter_id


def _require_inference_pb2() -> Any:
    global inference_pb2
    if inference_pb2 is None:
        inference_pb2 = importlib.import_module("infernix.runtime.inference_pb2")
    return inference_pb2
