#!/bin/sh
set -eu

export INFERNIX_BUILD_ROOT="${INFERNIX_BUILD_ROOT:-/opt/build/infernix}"
export INFERNIX_CABAL_BUILDDIR="${INFERNIX_CABAL_BUILDDIR:-${INFERNIX_BUILD_ROOT}}"

CABAL_HOME_DIR="${CABAL_DIR:-${HOME:-/root}/.cabal}"
PACKAGE_INDEX_CACHE="${CABAL_HOME_DIR}/packages/hackage.haskell.org/01-index.cache"

if [ ! -f "${PACKAGE_INDEX_CACHE}" ]; then
  cabal update
fi

exec cabal run --builddir="${INFERNIX_CABAL_BUILDDIR}" exe:infernix -- "$@"
