# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: infernix/manifest/runtime_manifest.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'infernix/manifest/runtime_manifest.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(infernix/manifest/runtime_manifest.proto\x12\x11infernix.manifest\"\x94\x01\n\x14ModelMaterialization\x12\x14\n\x0cruntime_mode\x18\x01 \x01(\t\x12\x10\n\x08model_id\x18\x02 \x01(\t\x12\x17\n\x0fselected_engine\x18\x03 \x01(\t\x12\x1a\n\x12\x64urable_source_uri\x18\x04 \x01(\t\x12\x1f\n\x17materialized_cache_path\x18\x05 \x01(\t\"x\n\x11RuntimeCacheEntry\x12\x14\n\x0cruntime_mode\x18\x01 \x01(\t\x12\x10\n\x08model_id\x18\x02 \x01(\t\x12\x11\n\tcache_key\x18\x03 \x01(\t\x12\x12\n\ncache_path\x18\x04 \x01(\t\x12\x14\n\x0cmaterialized\x18\x05 \x01(\x08\"\xdc\x01\n\x0fRuntimeManifest\x12\x13\n\x0bmanifest_id\x18\x01 \x01(\t\x12\x14\n\x0cruntime_mode\x18\x02 \x01(\t\x12\x41\n\x10materializations\x18\x03 \x03(\x0b\x32\'.infernix.manifest.ModelMaterialization\x12;\n\rcache_entries\x18\x04 \x03(\x0b\x32$.infernix.manifest.RuntimeCacheEntry\x12\x1e\n\x16\x64urable_results_prefix\x18\x05 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'infernix.manifest.runtime_manifest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODELMATERIALIZATION']._serialized_start=64
  _globals['_MODELMATERIALIZATION']._serialized_end=212
  _globals['_RUNTIMECACHEENTRY']._serialized_start=214
  _globals['_RUNTIMECACHEENTRY']._serialized_end=334
  _globals['_RUNTIMEMANIFEST']._serialized_start=337
  _globals['_RUNTIMEMANIFEST']._serialized_end=557
# @@protoc_insertion_point(module_scope)
