-- | The public inference-process boundary. Launching requires a
-- runtime-refined 'ExecutableModel' and a closed operation for the selected
-- engine family. Indexed grants, live enforcers, raw process specifications,
-- rendered environments, and process handles remain in the package-internal
-- kernel.
module Infernix.Runtime.CappedEngine
  ( EngineOutputStream (..),
    EngineOutcome (..),
    EngineExecutionPlan,
    NativeArtifactCache,
    NativeArtifactInvocation,
    NativeArtifactLaunchOutcome (..),
    PythonWorkerLaunchOutcome (..),
    accountedAllocationMarginMibForTest,
    classifyCeilingRefusalForTest,
    executableEngineCeiling,
    executableWatchdogCeilingsForTest,
    nativeArtifactCache,
    nativeArtifactInvocation,
    engineExecutionRuntimePlan,
    newEngineExecutionPlan,
    runExecutableNativeArtifact,
    runExecutablePythonWorker,
    observeNvidiaDeviceVramMib,
    probeNvidiaVramSampler,
    verifyNvidiaVramSampler,
    verifyPhysicalFootprintSampler,
    verifyProcessGroupRssSampler,
    withEngineExecutionPlan,
  )
where

import Infernix.Runtime.CappedEngine.Internal
  ( EngineExecutionPlan,
    EngineOutcome (..),
    EngineOutputStream (..),
    NativeArtifactCache,
    NativeArtifactInvocation,
    NativeArtifactLaunchOutcome (..),
    PythonWorkerLaunchOutcome (..),
    accountedAllocationMarginMibForTest,
    classifyCeilingRefusalForTest,
    engineExecutionRuntimePlan,
    executableEngineCeiling,
    executableWatchdogCeilingsForTest,
    nativeArtifactCache,
    nativeArtifactInvocation,
    newEngineExecutionPlan,
    observeNvidiaDeviceVramMib,
    probeNvidiaVramSampler,
    runExecutableNativeArtifact,
    runExecutablePythonWorker,
    verifyNvidiaVramSampler,
    verifyPhysicalFootprintSampler,
    verifyProcessGroupRssSampler,
    withEngineExecutionPlan,
  )
