#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
import pathlib
import sys


def strip_banner(raw_text: str) -> str:
    lines = raw_text.splitlines()
    while lines and not lines[0].strip():
        lines = lines[1:]
    if lines and lines[0].strip() == "{- Auto-generated by infernix cluster up -}":
        return "\n".join(lines[1:])
    return "\n".join(lines)


def validate_demo_config(payload: object) -> dict:
    if not isinstance(payload, dict):
        raise ValueError("invalid demo config: top-level payload must be an object")

    runtime_mode = payload.get("runtimeMode")
    models = payload.get("models")
    if not isinstance(runtime_mode, str) or not runtime_mode:
        raise ValueError("invalid demo config: runtimeMode must be a non-empty string")
    if not isinstance(models, list) or not models:
        raise ValueError("invalid demo config: models must be a non-empty list")

    required_fields = {
        "matrixRowId": str,
        "modelId": str,
        "displayName": str,
        "family": str,
        "description": str,
        "artifactType": str,
        "referenceModel": str,
        "downloadUrl": str,
        "selectedEngine": str,
        "runtimeMode": str,
        "runtimeLane": str,
        "requiresGpu": bool,
        "notes": str,
    }
    request_field_keys = {"name", "label", "fieldType"}

    for index, model in enumerate(models):
        if not isinstance(model, dict):
            raise ValueError(f"invalid demo config: model entry {index} must be an object")
        for field_name, field_type in required_fields.items():
            value = model.get(field_name)
            if not isinstance(value, field_type) or value == "":
                raise ValueError(f"invalid demo config: model entry {index} has invalid {field_name}")
        if model["runtimeMode"] != runtime_mode:
            raise ValueError(
                f"invalid demo config: model entry {index} runtimeMode does not match top-level runtimeMode"
            )
        request_shape = model.get("requestShape")
        if not isinstance(request_shape, list) or not request_shape:
            raise ValueError(f"invalid demo config: model entry {index} requestShape must be a non-empty list")
        for field_index, request_field in enumerate(request_shape):
            if not isinstance(request_field, dict):
                raise ValueError(
                    f"invalid demo config: model entry {index} requestShape entry {field_index} must be an object"
                )
            missing_keys = [
                key for key in request_field_keys if not isinstance(request_field.get(key), str) or not request_field.get(key)
            ]
            if missing_keys:
                raise ValueError(
                    "invalid demo config: "
                    f"model entry {index} requestShape entry {field_index} is missing {', '.join(sorted(missing_keys))}"
                )

    return payload


def load_demo_config(demo_config_path: pathlib.Path) -> dict:
    if not demo_config_path.exists():
        raise FileNotFoundError(f"demo config does not exist: {demo_config_path}")
    payload = json.loads(strip_banner(demo_config_path.read_text()))
    return validate_demo_config(payload)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("demo_config")
    parser.add_argument("--list-models", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    demo_config_path = pathlib.Path(args.demo_config).resolve()

    try:
        payload = load_demo_config(demo_config_path)
    except (FileNotFoundError, ValueError, json.JSONDecodeError) as exc:
        print(f"demo-config: {exc}", file=sys.stderr)
        return 1

    if args.list_models:
        print(f"runtimeMode\t{payload['runtimeMode']}")
        for model in payload["models"]:
            print(
                "\t".join(
                    [
                        "model",
                        model["matrixRowId"],
                        model["modelId"],
                        model["selectedEngine"],
                        model["runtimeMode"],
                        "true" if model["requiresGpu"] else "false",
                    ]
                )
            )
        return 0

    print(json.dumps(payload))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
