# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: infernix/api/inference_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from infernix.runtime import inference_pb2 as infernix_dot_runtime_dot_inference__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$infernix/api/inference_service.proto\x12\x0cinfernix.api\x1a infernix/runtime/inference.proto\"*\n\x12ListCatalogRequest\x12\x14\n\x0cruntime_mode\x18\x01 \x01(\t\"E\n\x13ListCatalogResponse\x12.\n\x06models\x18\x01 \x03(\x0b\x32\x1e.infernix.runtime.CatalogEntry\"#\n\x0fGetModelRequest\x12\x10\n\x08model_id\x18\x01 \x01(\t\"M\n\x16SubmitInferenceRequest\x12\x33\n\x07request\x18\x01 \x01(\x0b\x32\".infernix.runtime.InferenceRequest\"/\n\x19GetInferenceResultRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t2\xef\x02\n\x10InferenceService\x12R\n\x0bListCatalog\x12 .infernix.api.ListCatalogRequest\x1a!.infernix.api.ListCatalogResponse\x12I\n\x08GetModel\x12\x1d.infernix.api.GetModelRequest\x1a\x1e.infernix.runtime.CatalogEntry\x12Z\n\x0fSubmitInference\x12$.infernix.api.SubmitInferenceRequest\x1a!.infernix.runtime.InferenceResult\x12`\n\x12GetInferenceResult\x12\'.infernix.api.GetInferenceResultRequest\x1a!.infernix.runtime.InferenceResultb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'infernix.api.inference_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LISTCATALOGREQUEST._serialized_start=88
  _LISTCATALOGREQUEST._serialized_end=130
  _LISTCATALOGRESPONSE._serialized_start=132
  _LISTCATALOGRESPONSE._serialized_end=201
  _GETMODELREQUEST._serialized_start=203
  _GETMODELREQUEST._serialized_end=238
  _SUBMITINFERENCEREQUEST._serialized_start=240
  _SUBMITINFERENCEREQUEST._serialized_end=317
  _GETINFERENCERESULTREQUEST._serialized_start=319
  _GETINFERENCERESULTREQUEST._serialized_end=366
  _INFERENCESERVICE._serialized_start=369
  _INFERENCESERVICE._serialized_end=736
# @@protoc_insertion_point(module_scope)
