-- | Domain-owned cluster operations and a closed lifecycle program. The runner
-- discovers configured paths and holds the real lock throughout interpretation.
-- No acquisition, payload extraction, arbitrary IO lifting, or child-fork
-- operation is part of this public authority surface.
module Infernix.Cluster
  ( AbsentConfigRecovery (..),
    RecordedNamespaceRelation (..),
    classifyAbsentConfigRecovery,
    clusterWorkloadArchitectureForHostArchitecture,
    clusterDown,
    clusterDownHarness,
    clusterStatus,
    clusterUp,
    clusterUpHarness,
    ClusterMutationLocked,
    ClusterTeardownAuthority,
    clusterTeardownAuthorityRegionWitness,
    LifecycleSession,
    LifecycleProgram,
    runClusterLifecycle,
    finishLifecycle,
    observeLifecycle,
    lifecycleOperatorUp,
    lifecycleOperatorDown,
    lifecycleHarnessUp,
    lifecycleHarnessDown,
    lifecycleHarnessGpuEngine,
    prepareLinuxGpuEngineDeployment,
    reconcileInterruptedHarnessState,
    withRuntimeConfigWriteAccess,
    RetainedReplayPlan (..),
    retainedReplayPlan,
    retainedReplayPending,
    preWorkloadRecoveryIntentMatches,
    KindKubeconfigRecoveryPlan (..),
    kindKubeconfigRecoveryPlan,
    SnapshotRecoveryAction (..),
    snapshotRecoveryPlan,
    WorkerPauseState (..),
    classifyWorkerPauseObservation,
    snapshotClaimNodeBindingsForPausedWorkers,
    withHarnessClusterSlot,
    reclaimHarnessClusterSlot,
    authorizeClusterOwnership,
    ClusterCheckoutIdentity (..),
    clusterCheckoutIdentityFromHostRoot,
    ClusterSlotIdentity (..),
    ClusterSlotAdmission (..),
    ClusterOwnershipRefusalReason (..),
    authorizeHarnessReservationAccess,
    authorizeRuntimeConfigWriteAccess,
    uncordonResultsProveReady,
    ClusterOwnershipRefusal (..),
    HelmDeployPhase (..),
    kindControlPlaneNodeName,
    linuxGpuNvkindConfigMapBug,
    linuxGpuSupportedOnHost,
    loadClusterState,
    pulsarBootstrapLogIndicatesDirtyState,
    renderHelmValues,
    renderKindConfig,
    renderFleetMachineContracts,
    clusterFleetEngineDeployments,
    finalPhaseDeployments,
    fleetSlotLabelKey,
    perEngineDeploymentNames,
    runPlaywrightPrepareEngine,
    runKubectlCompat,
  )
where

import Infernix.Cluster.Internal
import Infernix.Cluster.LifecycleProgram.Internal
  ( LifecycleProgram,
    LifecycleSession,
    finishLifecycle,
    lifecycleHarnessDown,
    lifecycleHarnessGpuEngine,
    lifecycleHarnessUp,
    lifecycleOperatorDown,
    lifecycleOperatorUp,
    observeLifecycle,
  )
