{-# LANGUAGE OverloadedStrings #-}

module Infernix.Models
  ( allModels,
    findModel,
    platformClaims,
    routeInventory,
    renderTestConfig,
  )
where

import Data.List (find)
import Data.Text (Text)
import qualified Data.Text as Text
import Infernix.Types

allModels :: [ModelDescriptor]
allModels =
  [ ModelDescriptor "echo-text" "Echo Text" "text" "Returns the input unchanged." textFields,
    ModelDescriptor "uppercase-text" "Uppercase Text" "text" "Transforms input to uppercase." textFields,
    ModelDescriptor "word-count" "Word Count" "analysis" "Returns the number of words in the input." textFields
  ]
  where
    textFields =
      [ RequestField "inputText" "Input Text" "text"
      ]

findModel :: Text -> Maybe ModelDescriptor
findModel wanted = find ((== wanted) . modelId) allModels

platformClaims :: [PersistentClaim]
platformClaims =
  [ PersistentClaim "platform" "infernix" "harbor" 0 "registry",
    PersistentClaim "platform" "infernix" "minio" 0 "data",
    PersistentClaim "platform" "infernix" "pulsar" 0 "ledger",
    PersistentClaim "platform" "infernix" "service" 0 "cache",
    PersistentClaim "platform" "infernix" "web" 0 "assets"
  ]

routeInventory :: [RouteInfo]
routeInventory =
  [ RouteInfo "/" "PureScript UI",
    RouteInfo "/api" "Service API",
    RouteInfo "/harbor" "Harbor portal",
    RouteInfo "/minio/console" "MinIO console",
    RouteInfo "/minio/s3" "MinIO S3 API",
    RouteInfo "/pulsar/admin" "Pulsar admin surface",
    RouteInfo "/pulsar/ws" "Pulsar websocket surface"
  ]

renderTestConfig :: Int -> String
renderTestConfig edgePort =
  unlines
    [ "{- Auto-generated by infernix cluster up -}",
      "{ edgePort = " <> show edgePort,
      ", models = [ " <> modelList <> " ]",
      "}"
    ]
  where
    modelList = Text.unpack $ Text.intercalate ", " (map quoted (map modelId allModels))
    quoted modelName = "\"" <> modelName <> "\""
