{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE OverloadedStrings #-}

module Infernix.Substrate
  ( decodeSubstrateConfigFile,
    demoConfigGeneratedBanner,
    demoConfigGeneratedBannerLine,
    encodeSubstrateConfig,
    renderSubstrateConfig,
    resolveRuntimeModeFromSubstrateFile,
  )
where

import Control.Exception (SomeException, displayException, try)
import Data.ByteString.Lazy.Char8 qualified as LazyChar8
import Data.Char (toLower)
import Data.List (intercalate)
import Data.Maybe (listToMaybe, maybeToList)
import Data.Text (Text)
import Data.Text qualified as Text
import Dhall qualified
import Dhall.Core qualified as DhallCore
import GHC.Generics (Generic)
import Infernix.Types

demoConfigGeneratedBannerLine :: String
demoConfigGeneratedBannerLine = "{- Auto-generated by infernix substrate materialization -}"

demoConfigGeneratedBanner :: String
demoConfigGeneratedBanner = demoConfigGeneratedBannerLine <> "\n"

encodeSubstrateConfig :: DemoConfig -> LazyChar8.ByteString
encodeSubstrateConfig demoConfig =
  LazyChar8.pack (demoConfigGeneratedBanner <> renderSubstrateConfig demoConfig)

decodeSubstrateConfigFile :: FilePath -> IO DemoConfig
decodeSubstrateConfigFile filePath = do
  decodedValue <- try (Dhall.inputFile Dhall.auto filePath :: IO DhallDemoConfig)
  case decodedValue of
    Left err -> do
      legacyDecodedValue <-
        ( try (Dhall.inputFile Dhall.auto filePath :: IO LegacyDhallDemoConfig) ::
            IO (Either SomeException LegacyDhallDemoConfig)
        )
      case legacyDecodedValue of
        Left _ ->
          ioError
            (userError ("invalid generated substrate Dhall: " <> displayException (err :: SomeException)))
        Right legacyRawConfig ->
          case legacyDemoConfigFromDhall legacyRawConfig of
            Left message -> ioError (userError ("invalid generated substrate Dhall: " <> message))
            Right demoConfig -> pure demoConfig
    Right rawConfig ->
      case demoConfigFromDhall rawConfig of
        Left message -> ioError (userError ("invalid generated substrate Dhall: " <> message))
        Right demoConfig -> pure demoConfig

resolveRuntimeModeFromSubstrateFile :: FilePath -> IO RuntimeMode
resolveRuntimeModeFromSubstrateFile filePath =
  configRuntimeMode <$> decodeSubstrateConfigFile filePath

data DhallDemoConfig = DhallDemoConfig
  { dhallConfigRuntimeMode :: Text,
    dhallEdgePort :: Int,
    dhallConfigMapName :: Text,
    dhallGeneratedPath :: Text,
    dhallMountedPath :: Text,
    dhallDemoUi :: Bool,
    dhallDaemonRole :: Text,
    -- Phase 7 Sprint 7.7 renamed Dhall fields:
    -- @clusterDaemon@ -> @coordinator@ and @hostDaemon@ -> @engine@.
    -- The Haskell record selector for the engine role daemon uses the
    -- @EngineDaemon@ suffix to avoid colliding with
    -- 'DhallEngineBinding.dhallEngine' (the engine-name string in the
    -- engine binding record); 'dhallFieldName' maps it to the @engine@
    -- key on the dhall wire side.
    dhallCoordinator :: DhallDaemonConfig,
    dhallEngineDaemon :: Maybe DhallDaemonConfig,
    dhallEngineDaemons :: [DhallDaemonConfig],
    dhallEnginePools :: [DhallEnginePool],
    dhallEngineMembers :: [DhallEngineMember],
    dhallConfigRequestTopics :: [Text],
    dhallConfigResultTopic :: Text,
    dhallModelsBucket :: Text,
    dhallModelBootstrapTopic :: Text,
    dhallEngines :: [DhallEngineBinding],
    dhallModels :: [DhallModelDescriptor]
  }
  deriving (Generic)

instance Dhall.FromDhall DhallDemoConfig where
  autoWith _ = Dhall.genericAutoWith dhallInterpretOptions

data LegacyDhallDemoConfig = LegacyDhallDemoConfig
  { legacyDhallConfigRuntimeMode :: Text,
    legacyDhallEdgePort :: Int,
    legacyDhallConfigMapName :: Text,
    legacyDhallGeneratedPath :: Text,
    legacyDhallMountedPath :: Text,
    legacyDhallDemoUi :: Bool,
    legacyDhallDaemonRole :: Text,
    legacyDhallCoordinator :: DhallDaemonConfig,
    legacyDhallEngineDaemon :: Maybe DhallDaemonConfig,
    legacyDhallConfigRequestTopics :: [Text],
    legacyDhallConfigResultTopic :: Text,
    legacyDhallModelsBucket :: Text,
    legacyDhallModelBootstrapTopic :: Text,
    legacyDhallEngines :: [DhallEngineBinding],
    legacyDhallModels :: [DhallModelDescriptor]
  }
  deriving (Generic)

instance Dhall.FromDhall LegacyDhallDemoConfig where
  autoWith _ = Dhall.genericAutoWith dhallInterpretOptions

data DhallDaemonConfig = DhallDaemonConfig
  { dhallRole :: Text,
    dhallLocation :: Text,
    dhallMemberId :: Maybe Text,
    dhallDaemonRequestTopics :: [Text],
    dhallDaemonResultTopic :: Text,
    dhallHostBatchTopic :: Maybe Text,
    dhallPulsarConnectionMode :: Text
  }
  deriving (Generic)

instance Dhall.FromDhall DhallDaemonConfig where
  autoWith _ = Dhall.genericAutoWith dhallInterpretOptions

data DhallEnginePool = DhallEnginePool
  { dhallPoolId :: Text,
    dhallPoolRuntimeMode :: Text,
    dhallPoolModelIds :: [Text],
    dhallPoolMemberIds :: [Text],
    dhallPoolSubscriptionType :: Text,
    dhallMaxInflightPerMember :: Int
  }
  deriving (Generic)

instance Dhall.FromDhall DhallEnginePool where
  autoWith _ = Dhall.genericAutoWith dhallInterpretOptions

data DhallEngineMember = DhallEngineMember
  { dhallMemberConfigId :: Text,
    dhallMemberRuntimeMode :: Text,
    dhallMemberLocation :: Text,
    dhallMemberPoolIds :: [Text]
  }
  deriving (Generic)

instance Dhall.FromDhall DhallEngineMember where
  autoWith _ = Dhall.genericAutoWith dhallInterpretOptions

data DhallEngineBinding = DhallEngineBinding
  { dhallEngine :: Text,
    dhallAdapterId :: Text,
    dhallAdapterType :: Text,
    dhallAdapterLocator :: Text,
    dhallAdapterEntrypoint :: Text,
    dhallSetupEntrypoint :: Text,
    dhallProjectDirectory :: Text,
    dhallPythonNative :: Bool
  }
  deriving (Generic)

instance Dhall.FromDhall DhallEngineBinding where
  autoWith _ = Dhall.genericAutoWith dhallInterpretOptions

data DhallModelDescriptor = DhallModelDescriptor
  { dhallMatrixRowId :: Text,
    dhallModelId :: Text,
    dhallDisplayName :: Text,
    dhallFamily :: Text,
    dhallDescription :: Text,
    dhallArtifactType :: Text,
    dhallReferenceModel :: Text,
    dhallDownloadUrl :: Text,
    dhallSelectedEngine :: Text,
    dhallRequestShape :: [DhallRequestField],
    dhallModelRuntimeMode :: Text,
    dhallRuntimeLane :: Text,
    dhallRequiresGpu :: Bool,
    dhallNotes :: Text
  }
  deriving (Generic)

instance Dhall.FromDhall DhallModelDescriptor where
  autoWith _ = Dhall.genericAutoWith dhallInterpretOptions

data DhallRequestField = DhallRequestField
  { dhallName :: Text,
    dhallLabel :: Text,
    dhallFieldType :: Text
  }
  deriving (Generic)

instance Dhall.FromDhall DhallRequestField where
  autoWith _ = Dhall.genericAutoWith dhallInterpretOptions

dhallInterpretOptions :: Dhall.InterpretOptions
dhallInterpretOptions =
  Dhall.defaultInterpretOptions {Dhall.fieldModifier = dhallFieldName}

dhallFieldName :: Text -> Text
dhallFieldName rawFieldName =
  case Text.stripPrefix "dhall" rawFieldName of
    Just suffix -> dhallFieldSuffixName suffix
    Nothing ->
      maybe
        rawFieldName
        dhallFieldSuffixName
        (Text.stripPrefix "legacyDhall" rawFieldName)

dhallFieldSuffixName :: Text -> Text
dhallFieldSuffixName suffix =
  case suffix of
    "ConfigRuntimeMode" -> "runtimeMode"
    "ConfigRequestTopics" -> "request_topics"
    "ConfigResultTopic" -> "result_topic"
    "DaemonRequestTopics" -> "request_topics"
    "DaemonResultTopic" -> "result_topic"
    "ModelRuntimeMode" -> "runtimeMode"
    "DemoUi" -> "demo_ui"
    "RequestTopics" -> "request_topics"
    "ResultTopic" -> "result_topic"
    "HostBatchTopic" -> "host_batch_topic"
    "MemberId" -> "memberId"
    "ModelsBucket" -> "models_bucket"
    "ModelBootstrapTopic" -> "model_bootstrap_topic"
    "EngineDaemon" -> "engine"
    "EngineDaemons" -> "engineDaemons"
    "EnginePools" -> "enginePools"
    "EngineMembers" -> "engineMembers"
    "PoolId" -> "id"
    "PoolRuntimeMode" -> "runtimeMode"
    "PoolModelIds" -> "models"
    "PoolMemberIds" -> "members"
    "PoolSubscriptionType" -> "subscription"
    "MemberConfigId" -> "id"
    "MemberRuntimeMode" -> "runtimeMode"
    "MemberLocation" -> "location"
    "MemberPoolIds" -> "pools"
    other -> lowerInitial other

lowerInitial :: Text -> Text
lowerInitial value =
  case Text.uncons value of
    Nothing -> value
    Just (firstCharacter, rest) -> Text.cons (toLower firstCharacter) rest

demoConfigFromDhall :: DhallDemoConfig -> Either String DemoConfig
demoConfigFromDhall rawConfig = do
  runtimeModeValue <- parseEnum "runtimeMode" parseRuntimeMode (dhallConfigRuntimeMode rawConfig)
  activeDaemonRoleValue <- parseEnum "daemonRole" parseDaemonRole (dhallDaemonRole rawConfig)
  coordinatorDaemonValue <- withDefaultConsumerSubscriptionType runtimeModeValue <$> daemonConfigFromDhall (dhallCoordinator rawConfig)
  legacyEngineDaemonValue <- traverse (fmap (withDefaultConsumerSubscriptionType runtimeModeValue) . daemonConfigFromDhall) (dhallEngineDaemon rawConfig)
  engineDaemonValues <- traverse (fmap (withDefaultConsumerSubscriptionType runtimeModeValue) . daemonConfigFromDhall) (dhallEngineDaemons rawConfig)
  enginePoolValues <- traverse enginePoolFromDhall (dhallEnginePools rawConfig)
  engineMemberValues <- traverse engineMemberFromDhall (dhallEngineMembers rawConfig)
  engineValues <- traverse engineBindingFromDhall (dhallEngines rawConfig)
  modelValues <- traverse modelDescriptorFromDhall (dhallModels rawConfig)
  pure
    DemoConfig
      { configRuntimeMode = runtimeModeValue,
        configEdgePort = dhallEdgePort rawConfig,
        configMapName = dhallConfigMapName rawConfig,
        generatedPath = Text.unpack (dhallGeneratedPath rawConfig),
        mountedPath = Text.unpack (dhallMountedPath rawConfig),
        demoUiEnabled = dhallDemoUi rawConfig,
        activeDaemonRole = activeDaemonRoleValue,
        coordinatorDaemon = coordinatorDaemonValue,
        engineDaemons =
          if null engineDaemonValues
            then maybeToList legacyEngineDaemonValue
            else engineDaemonValues,
        enginePools = enginePoolValues,
        engineMembers = engineMemberValues,
        requestTopics = dhallConfigRequestTopics rawConfig,
        resultTopic = dhallConfigResultTopic rawConfig,
        modelsBucket = dhallModelsBucket rawConfig,
        modelBootstrapTopic = dhallModelBootstrapTopic rawConfig,
        engines = engineValues,
        models = modelValues
      }

legacyDemoConfigFromDhall :: LegacyDhallDemoConfig -> Either String DemoConfig
legacyDemoConfigFromDhall rawConfig = do
  runtimeModeValue <- parseEnum "runtimeMode" parseRuntimeMode (legacyDhallConfigRuntimeMode rawConfig)
  activeDaemonRoleValue <- parseEnum "daemonRole" parseDaemonRole (legacyDhallDaemonRole rawConfig)
  coordinatorDaemonValue <- withDefaultConsumerSubscriptionType runtimeModeValue <$> daemonConfigFromDhall (legacyDhallCoordinator rawConfig)
  engineDaemonValue <- traverse (fmap (withDefaultConsumerSubscriptionType runtimeModeValue) . daemonConfigFromDhall) (legacyDhallEngineDaemon rawConfig)
  engineValues <- traverse engineBindingFromDhall (legacyDhallEngines rawConfig)
  modelValues <- traverse modelDescriptorFromDhall (legacyDhallModels rawConfig)
  pure
    DemoConfig
      { configRuntimeMode = runtimeModeValue,
        configEdgePort = legacyDhallEdgePort rawConfig,
        configMapName = legacyDhallConfigMapName rawConfig,
        generatedPath = Text.unpack (legacyDhallGeneratedPath rawConfig),
        mountedPath = Text.unpack (legacyDhallMountedPath rawConfig),
        demoUiEnabled = legacyDhallDemoUi rawConfig,
        activeDaemonRole = activeDaemonRoleValue,
        coordinatorDaemon = coordinatorDaemonValue,
        engineDaemons = maybeToList engineDaemonValue,
        enginePools = [],
        engineMembers = [],
        requestTopics = legacyDhallConfigRequestTopics rawConfig,
        resultTopic = legacyDhallConfigResultTopic rawConfig,
        modelsBucket = legacyDhallModelsBucket rawConfig,
        modelBootstrapTopic = legacyDhallModelBootstrapTopic rawConfig,
        engines = engineValues,
        models = modelValues
      }

daemonConfigFromDhall :: DhallDaemonConfig -> Either String DaemonConfig
daemonConfigFromDhall rawConfig = do
  roleValue <- parseEnum "daemon role" parseDaemonRole (dhallRole rawConfig)
  connectionModeValue <- parseEnum "pulsarConnectionMode" parsePulsarConnectionMode (dhallPulsarConnectionMode rawConfig)
  pure
    DaemonConfig
      { daemonConfigRole = roleValue,
        daemonConfigLocation = dhallLocation rawConfig,
        daemonConfigMemberId = dhallMemberId rawConfig,
        daemonConfigRequestTopics = dhallDaemonRequestTopics rawConfig,
        daemonConfigResultTopic = dhallDaemonResultTopic rawConfig,
        daemonConfigHostBatchTopic = dhallHostBatchTopic rawConfig,
        daemonConfigPulsarConnectionMode = connectionModeValue,
        daemonConfigConsumerSubscriptionType = Nothing
      }

enginePoolFromDhall :: DhallEnginePool -> Either String EnginePool
enginePoolFromDhall rawPool = do
  runtimeModeValue <- parseEnum "engine pool runtimeMode" parseRuntimeMode (dhallPoolRuntimeMode rawPool)
  subscriptionValue <- parseEnum "engine pool subscription" parseConsumerSubscriptionType (dhallPoolSubscriptionType rawPool)
  pure
    EnginePool
      { enginePoolId = dhallPoolId rawPool,
        enginePoolRuntimeMode = runtimeModeValue,
        enginePoolModelIds = dhallPoolModelIds rawPool,
        enginePoolMemberIds = dhallPoolMemberIds rawPool,
        enginePoolSubscriptionType = subscriptionValue,
        enginePoolMaxInflightPerMember = dhallMaxInflightPerMember rawPool
      }

engineMemberFromDhall :: DhallEngineMember -> Either String EngineMember
engineMemberFromDhall rawMember = do
  runtimeModeValue <- parseEnum "engine member runtimeMode" parseRuntimeMode (dhallMemberRuntimeMode rawMember)
  pure
    EngineMember
      { engineMemberId = dhallMemberConfigId rawMember,
        engineMemberRuntimeMode = runtimeModeValue,
        engineMemberLocation = dhallMemberLocation rawMember,
        engineMemberPoolIds = dhallMemberPoolIds rawMember
      }

withDefaultConsumerSubscriptionType :: RuntimeMode -> DaemonConfig -> DaemonConfig
withDefaultConsumerSubscriptionType runtimeMode daemonConfig =
  daemonConfig
    { daemonConfigConsumerSubscriptionType =
        case daemonConfigConsumerSubscriptionType daemonConfig of
          Just subscriptionType -> Just subscriptionType
          Nothing -> Just (defaultConsumerSubscriptionType runtimeMode daemonConfig)
    }

defaultConsumerSubscriptionType :: RuntimeMode -> DaemonConfig -> ConsumerSubscriptionType
defaultConsumerSubscriptionType runtimeMode daemonConfig
  | runtimeMode == AppleSilicon
      && daemonConfigRole daemonConfig == Engine
      && daemonConfigLocation daemonConfig == "control-plane-host" =
      ConsumerShared
  | otherwise = ConsumerShared

engineBindingFromDhall :: DhallEngineBinding -> Either String EngineBinding
engineBindingFromDhall rawBinding =
  pure
    EngineBinding
      { engineBindingName = dhallEngine rawBinding,
        engineBindingAdapterId = dhallAdapterId rawBinding,
        engineBindingAdapterType = dhallAdapterType rawBinding,
        engineBindingAdapterLocator = dhallAdapterLocator rawBinding,
        engineBindingAdapterEntrypoint = dhallAdapterEntrypoint rawBinding,
        engineBindingSetupEntrypoint = dhallSetupEntrypoint rawBinding,
        engineBindingProjectDirectory = Text.unpack (dhallProjectDirectory rawBinding),
        engineBindingPythonNative = dhallPythonNative rawBinding
      }

modelDescriptorFromDhall :: DhallModelDescriptor -> Either String ModelDescriptor
modelDescriptorFromDhall rawModel = do
  runtimeModeValue <- parseEnum "model runtimeMode" parseRuntimeMode (dhallModelRuntimeMode rawModel)
  runtimeLaneValue <- parseEnum "runtimeLane" parseRuntimeLane (dhallRuntimeLane rawModel)
  requestShapeValue <- traverse requestFieldFromDhall (dhallRequestShape rawModel)
  pure
    ModelDescriptor
      { matrixRowId = dhallMatrixRowId rawModel,
        modelId = dhallModelId rawModel,
        displayName = dhallDisplayName rawModel,
        family = dhallFamily rawModel,
        description = dhallDescription rawModel,
        artifactType = dhallArtifactType rawModel,
        referenceModel = dhallReferenceModel rawModel,
        downloadUrl = dhallDownloadUrl rawModel,
        selectedEngine = dhallSelectedEngine rawModel,
        requestShape = requestShapeValue,
        runtimeMode = runtimeModeValue,
        runtimeLane = runtimeLaneValue,
        requiresGpu = dhallRequiresGpu rawModel,
        notes = dhallNotes rawModel
      }

requestFieldFromDhall :: DhallRequestField -> Either String RequestField
requestFieldFromDhall rawField = do
  fieldTypeValue <- parseEnum "fieldType" parseRequestFieldType (dhallFieldType rawField)
  pure
    RequestField
      { name = dhallName rawField,
        label = dhallLabel rawField,
        fieldType = fieldTypeValue
      }

parseEnum :: String -> (Text -> Maybe a) -> Text -> Either String a
parseEnum label parser rawValue =
  case parser rawValue of
    Just parsedValue -> Right parsedValue
    Nothing -> Left ("unsupported " <> label <> ": " <> Text.unpack rawValue)

renderSubstrateConfig :: DemoConfig -> String
renderSubstrateConfig demoConfig =
  unlines
    [ "{ runtimeMode = " <> dhallText (runtimeModeId (configRuntimeMode demoConfig)),
      ", edgePort = " <> dhallInteger (configEdgePort demoConfig),
      ", configMapName = " <> dhallText (configMapName demoConfig),
      ", generatedPath = " <> dhallFilePath (generatedPath demoConfig),
      ", mountedPath = " <> dhallFilePath (mountedPath demoConfig),
      ", demo_ui = " <> dhallBool (demoUiEnabled demoConfig),
      ", daemonRole = " <> dhallText (daemonRoleId (activeDaemonRole demoConfig)),
      ", coordinator = " <> renderDaemonConfig (coordinatorDaemon demoConfig),
      ", engine = " <> dhallOptional daemonConfigType renderDaemonConfig (listToMaybe (engineDaemons demoConfig)),
      ", engineDaemons = " <> dhallList daemonConfigType renderDaemonConfig (engineDaemons demoConfig),
      ", enginePools = " <> dhallList enginePoolType renderEnginePool (enginePools demoConfig),
      ", engineMembers = " <> dhallList engineMemberType renderEngineMember (engineMembers demoConfig),
      ", request_topics = " <> dhallList "Text" dhallText (requestTopics demoConfig),
      ", result_topic = " <> dhallText (resultTopic demoConfig),
      ", models_bucket = " <> dhallText (modelsBucket demoConfig),
      ", model_bootstrap_topic = " <> dhallText (modelBootstrapTopic demoConfig),
      ", engines = " <> dhallList engineBindingType renderEngineBinding (engines demoConfig),
      ", models = " <> dhallList modelDescriptorType renderModelDescriptor (models demoConfig),
      "}"
    ]

renderDaemonConfig :: DaemonConfig -> String
renderDaemonConfig daemonConfig =
  "{ role = "
    <> dhallText (daemonRoleId (daemonConfigRole daemonConfig))
    <> ", location = "
    <> dhallText (daemonConfigLocation daemonConfig)
    <> ", memberId = "
    <> dhallOptional "Text" dhallText (daemonConfigMemberId daemonConfig)
    <> ", request_topics = "
    <> dhallList "Text" dhallText (daemonConfigRequestTopics daemonConfig)
    <> ", result_topic = "
    <> dhallText (daemonConfigResultTopic daemonConfig)
    <> ", host_batch_topic = "
    <> dhallOptional "Text" dhallText (daemonConfigHostBatchTopic daemonConfig)
    <> ", pulsarConnectionMode = "
    <> dhallText (pulsarConnectionModeId (daemonConfigPulsarConnectionMode daemonConfig))
    <> " }"

renderEnginePool :: EnginePool -> String
renderEnginePool pool =
  "{ id = "
    <> dhallText (enginePoolId pool)
    <> ", runtimeMode = "
    <> dhallText (runtimeModeId (enginePoolRuntimeMode pool))
    <> ", models = "
    <> dhallList "Text" dhallText (enginePoolModelIds pool)
    <> ", members = "
    <> dhallList "Text" dhallText (enginePoolMemberIds pool)
    <> ", subscription = "
    <> dhallText (consumerSubscriptionTypeId (enginePoolSubscriptionType pool))
    <> ", maxInflightPerMember = "
    <> dhallInteger (enginePoolMaxInflightPerMember pool)
    <> " }"

renderEngineMember :: EngineMember -> String
renderEngineMember member =
  "{ id = "
    <> dhallText (engineMemberId member)
    <> ", runtimeMode = "
    <> dhallText (runtimeModeId (engineMemberRuntimeMode member))
    <> ", location = "
    <> dhallText (engineMemberLocation member)
    <> ", pools = "
    <> dhallList "Text" dhallText (engineMemberPoolIds member)
    <> " }"

renderEngineBinding :: EngineBinding -> String
renderEngineBinding engineBinding =
  "{ engine = "
    <> dhallText (engineBindingName engineBinding)
    <> ", adapterId = "
    <> dhallText (engineBindingAdapterId engineBinding)
    <> ", adapterType = "
    <> dhallText (engineBindingAdapterType engineBinding)
    <> ", adapterLocator = "
    <> dhallText (engineBindingAdapterLocator engineBinding)
    <> ", adapterEntrypoint = "
    <> dhallText (engineBindingAdapterEntrypoint engineBinding)
    <> ", setupEntrypoint = "
    <> dhallText (engineBindingSetupEntrypoint engineBinding)
    <> ", projectDirectory = "
    <> dhallFilePath (engineBindingProjectDirectory engineBinding)
    <> ", pythonNative = "
    <> dhallBool (engineBindingPythonNative engineBinding)
    <> " }"

renderModelDescriptor :: ModelDescriptor -> String
renderModelDescriptor model =
  "{ matrixRowId = "
    <> dhallText (matrixRowId model)
    <> ", modelId = "
    <> dhallText (modelId model)
    <> ", displayName = "
    <> dhallText (displayName model)
    <> ", family = "
    <> dhallText (family model)
    <> ", description = "
    <> dhallText (description model)
    <> ", artifactType = "
    <> dhallText (artifactType model)
    <> ", referenceModel = "
    <> dhallText (referenceModel model)
    <> ", downloadUrl = "
    <> dhallText (downloadUrl model)
    <> ", selectedEngine = "
    <> dhallText (selectedEngine model)
    <> ", requestShape = "
    <> dhallList requestFieldType renderRequestField (requestShape model)
    <> ", runtimeMode = "
    <> dhallText (runtimeModeId (runtimeMode model))
    <> ", runtimeLane = "
    <> dhallText (runtimeLaneId (runtimeLane model))
    <> ", requiresGpu = "
    <> dhallBool (requiresGpu model)
    <> ", notes = "
    <> dhallText (notes model)
    <> " }"

renderRequestField :: RequestField -> String
renderRequestField requestField =
  "{ name = "
    <> dhallText (name requestField)
    <> ", label = "
    <> dhallText (label requestField)
    <> ", fieldType = "
    <> dhallText (requestFieldTypeId (fieldType requestField))
    <> " }"

dhallList :: String -> (a -> String) -> [a] -> String
dhallList itemType renderItem values =
  case values of
    [] -> "([] : List " <> itemType <> ")"
    _ -> "[ " <> intercalate ", " (map renderItem values) <> " ]"

dhallOptional :: String -> (a -> String) -> Maybe a -> String
dhallOptional itemType renderItem value =
  case value of
    Nothing -> "None " <> itemType
    Just item -> "Some " <> renderItem item

dhallBool :: Bool -> String
dhallBool value
  | value = "True"
  | otherwise = "False"

dhallInteger :: Int -> String
dhallInteger value
  | value < 0 = show value
  | otherwise = "+" <> show value

dhallFilePath :: FilePath -> String
dhallFilePath = dhallText . Text.pack

dhallText :: Text -> String
dhallText value =
  Text.unpack ("\"" <> DhallCore.escapeText value <> "\"")

daemonConfigType :: String
daemonConfigType =
  "{ role : Text, location : Text, memberId : Optional Text, request_topics : List Text, result_topic : Text, host_batch_topic : Optional Text, pulsarConnectionMode : Text }"

enginePoolType :: String
enginePoolType =
  "{ id : Text, runtimeMode : Text, models : List Text, members : List Text, subscription : Text, maxInflightPerMember : Integer }"

engineMemberType :: String
engineMemberType =
  "{ id : Text, runtimeMode : Text, location : Text, pools : List Text }"

engineBindingType :: String
engineBindingType =
  "{ engine : Text, adapterId : Text, adapterType : Text, adapterLocator : Text, adapterEntrypoint : Text, setupEntrypoint : Text, projectDirectory : Text, pythonNative : Bool }"

requestFieldType :: String
requestFieldType =
  "{ name : Text, label : Text, fieldType : Text }"

modelDescriptorType :: String
modelDescriptorType =
  "{ matrixRowId : Text, modelId : Text, displayName : Text, family : Text, description : Text, artifactType : Text, referenceModel : Text, downloadUrl : Text, selectedEngine : Text, requestShape : List "
    <> requestFieldType
    <> ", runtimeMode : Text, runtimeLane : Text, requiresGpu : Bool, notes : Text }"
