module Infernix.Workflow
  ( demoConfigGeneratedBanner,
    ensurePlaywrightBrowsers,
    ensureWebDependencies,
    platformCommandsAvailable,
    platformCommandsAvailableForE2E,
    resolveWebNpmInvocation,
  )
where

import Data.Char (isDigit)
import Data.Maybe (isJust)
import Infernix.Config (Paths (repoRoot), discoverPaths)
import System.Directory (doesDirectoryExist, doesFileExist, findExecutable)
import System.Exit (ExitCode (ExitSuccess))
import System.FilePath ((</>))
import System.Process (CreateProcess (cwd), proc, readCreateProcessWithExitCode)

demoConfigGeneratedBanner :: String
demoConfigGeneratedBanner = "{- Auto-generated by infernix cluster up -}\n"

ensureWebDependencies :: IO ()
ensureWebDependencies = do
  paths <- discoverPaths
  let webRoot = repoRoot paths </> "web"
  depsDirectoryPresent <- doesDirectoryExist (webRoot </> "node_modules")
  toolchainPresent <- webToolchainPresent webRoot
  hostNodeReady <- hostNodeSupportsWebToolchain
  if depsDirectoryPresent && toolchainPresent && hostNodeReady
    then pure ()
    else do
      (command, args) <- resolveWebNpmInvocation ["--prefix", "web", "ci"]
      runWorkflowCommand (repoRoot paths) command args

ensurePlaywrightBrowsers :: IO ()
ensurePlaywrightBrowsers = do
  paths <- discoverPaths
  (command, args) <- resolveWebNpmInvocation ["exec", "--", "playwright", "install", "chromium"]
  runWorkflowCommand (repoRoot paths </> "web") command args

platformCommandsAvailable :: IO Bool
platformCommandsAvailable = do
  availableCommands <- mapM findExecutable ["docker", "helm", "kind", "kubectl"]
  pure (all isJust availableCommands)

platformCommandsAvailableForE2E :: IO Bool
platformCommandsAvailableForE2E = do
  platformReady <- platformCommandsAvailable
  maybeDocker <- findExecutable "docker"
  pure (platformReady && isJust maybeDocker)

webToolchainPresent :: FilePath -> IO Bool
webToolchainPresent webRoot =
  and
    <$> mapM
      doesFileExist
      [ webRoot </> "node_modules" </> "playwright" </> "package.json",
        webRoot </> "node_modules" </> "purescript" </> "package.json",
        webRoot </> "node_modules" </> "spago" </> "package.json",
        webRoot </> "node_modules" </> "esbuild" </> "package.json"
      ]

resolveWebNpmInvocation :: [String] -> IO (FilePath, [String])
resolveWebNpmInvocation npmArgs = do
  supported <- hostNodeSupportsWebToolchain
  pure $
    if supported
      then ("npm", npmArgs)
      else
        ( "npm",
          [ "exec",
            "--package=node@22",
            "--package=npm@10",
            "--",
            "sh",
            "-lc",
            "npm " <> unwords (map shellQuote npmArgs)
          ]
        )

hostNodeSupportsWebToolchain :: IO Bool
hostNodeSupportsWebToolchain = do
  maybeNode <- findExecutable "node"
  maybeNpm <- findExecutable "npm"
  case (maybeNode, maybeNpm) of
    (Just _, Just _) -> do
      (exitCode, stdoutOutput, _) <- readCreateProcessWithExitCode (proc "node" ["--version"]) ""
      pure $
        case exitCode of
          ExitSuccess ->
            case parseNodeMajorVersion stdoutOutput of
              Just majorVersion -> majorVersion >= 22
              Nothing -> False
          _ -> False
    _ -> pure False

parseNodeMajorVersion :: String -> Maybe Int
parseNodeMajorVersion rawVersion =
  case dropWhile (not . isDigit) rawVersion of
    [] -> Nothing
    digits -> case span isDigit digits of
      (majorDigits, _) | not (null majorDigits) -> Just (read majorDigits)
      _ -> Nothing

shellQuote :: String -> String
shellQuote rawValue =
  "'" <> concatMap escapeCharacter rawValue <> "'"
  where
    escapeCharacter '\'' = "'\\''"
    escapeCharacter character = [character]

runWorkflowCommand :: FilePath -> FilePath -> [String] -> IO ()
runWorkflowCommand workingDirectory command args = do
  (exitCode, _, stderrOutput) <-
    readCreateProcessWithExitCode ((proc command args) {cwd = Just workingDirectory}) ""
  case exitCode of
    ExitSuccess -> pure ()
    _ -> ioError (userError ("workflow command failed: " <> command <> " " <> unwords args <> "\n" <> stderrOutput))
